#
#  Copyright 2023 Google, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at:
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

static_library("crypto_toolbox") {
  sources = [
    "src/aes.cc",
    "src/aes_cmac.cc",
    "src/crypto_toolbox.cc",
    "src/p_256_curvepara.cc",
    "src/p_256_ecc_pp.cc",
    "src/p_256_multprecision.cc",
  ]

  include_dirs = [
    "//bt/system/",
    "//bt/system/stack/crypto_toolbox/include",
  ]

  configs += [ "//bt/system:target_defaults" ]
}

config("cryto_toolbox_support_defaults") {
  include_dirs = [
    "//bt/system/",
    "//bt/system/stack/crypto_toolbox/include",
  ]
}

executable("net_test_stack_crypto_toolbox") {
  sources = [ "test/crypto_toolbox_test.cc" ]

  include_dirs = [ "//bt/system/" ]

  configs += [
    ":cryto_toolbox_support_defaults",
    "//bt/system:external_gmock_main",
    "//bt/system:target_defaults",
  ]
}
