/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_bluetooth_hap_HapRust */

#ifndef _Included_com_android_bluetooth_hap_HapRust
#define _Included_com_android_bluetooth_hap_HapRust
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_bluetooth_hap_HapRust
 * Method:    initNative
 * Signature: ()Lcom/android/bluetooth/hap/HapRust/HapClientService;
 */
JNIEXPORT jobject JNICALL Java_com_android_bluetooth_hap_HapRust_initNative
  (JNIEnv *, jclass);

/*
 * Class:     com_android_bluetooth_hap_HapRust
 * Method:    cleanupNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_bluetooth_hap_HapRust_cleanupNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
