// Top level module dumpsys data schema

// Include module flatbuffer schema here keeping sorted order
include "common/init_flags.fbs";
include "hci/hci_acl_manager.fbs";
include "hci/hci_controller.fbs";
include "l2cap/classic/l2cap_classic_module.fbs";
include "module_unittest.fbs";
include "os/wakelock_manager.fbs";
include "shim/dumpsys.fbs";

// Cpp namespace of the dumpsys data
namespace bluetooth;

// Ordered sequence of flatbuffer tables
table DumpsysData {
    title:string;
    init_flags:common.InitFlagsData;
    wakelock_manager_data:bluetooth.os.WakelockManagerData;
    shim_dumpsys_data:bluetooth.shim.DumpsysModuleData;
    l2cap_classic_dumpsys_data:bluetooth.l2cap.classic.L2capClassicModuleData;
    hci_acl_manager_dumpsys_data:bluetooth.hci.AclManagerData;
    hci_controller_dumpsys_data:bluetooth.hci.ControllerData;
    module_unittest_data:bluetooth.ModuleUnitTestData;
}

// Indicator of the root flatbuffer table
root_type DumpsysData;
