// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pandora/l2cap.proto

package pandora;

public final class L2capProto {
  private L2capProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MakeConnectionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pandora.MakeConnectionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The connection that will open the stream.
     * </pre>
     *
     * <code>.pandora.Connection connection = 1;</code>
     * @return Whether the connection field is set.
     */
    boolean hasConnection();
    /**
     * <pre>
     * The connection that will open the stream.
     * </pre>
     *
     * <code>.pandora.Connection connection = 1;</code>
     * @return The connection.
     */
    pandora.HostProto.Connection getConnection();
    /**
     * <pre>
     * The connection that will open the stream.
     * </pre>
     *
     * <code>.pandora.Connection connection = 1;</code>
     */
    pandora.HostProto.ConnectionOrBuilder getConnectionOrBuilder();
  }
  /**
   * <pre>
   * Request for the `OpenSource` method.
   * </pre>
   *
   * Protobuf type {@code pandora.MakeConnectionRequest}
   */
  public static final class MakeConnectionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pandora.MakeConnectionRequest)
      MakeConnectionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MakeConnectionRequest.newBuilder() to construct.
    private MakeConnectionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MakeConnectionRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MakeConnectionRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MakeConnectionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pandora.HostProto.Connection.Builder subBuilder = null;
              if (connection_ != null) {
                subBuilder = connection_.toBuilder();
              }
              connection_ = input.readMessage(pandora.HostProto.Connection.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(connection_);
                connection_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pandora.L2capProto.internal_static_pandora_MakeConnectionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pandora.L2capProto.internal_static_pandora_MakeConnectionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pandora.L2capProto.MakeConnectionRequest.class, pandora.L2capProto.MakeConnectionRequest.Builder.class);
    }

    public static final int CONNECTION_FIELD_NUMBER = 1;
    private pandora.HostProto.Connection connection_;
    /**
     * <pre>
     * The connection that will open the stream.
     * </pre>
     *
     * <code>.pandora.Connection connection = 1;</code>
     * @return Whether the connection field is set.
     */
    @java.lang.Override
    public boolean hasConnection() {
      return connection_ != null;
    }
    /**
     * <pre>
     * The connection that will open the stream.
     * </pre>
     *
     * <code>.pandora.Connection connection = 1;</code>
     * @return The connection.
     */
    @java.lang.Override
    public pandora.HostProto.Connection getConnection() {
      return connection_ == null ? pandora.HostProto.Connection.getDefaultInstance() : connection_;
    }
    /**
     * <pre>
     * The connection that will open the stream.
     * </pre>
     *
     * <code>.pandora.Connection connection = 1;</code>
     */
    @java.lang.Override
    public pandora.HostProto.ConnectionOrBuilder getConnectionOrBuilder() {
      return getConnection();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (connection_ != null) {
        output.writeMessage(1, getConnection());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (connection_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getConnection());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pandora.L2capProto.MakeConnectionRequest)) {
        return super.equals(obj);
      }
      pandora.L2capProto.MakeConnectionRequest other = (pandora.L2capProto.MakeConnectionRequest) obj;

      if (hasConnection() != other.hasConnection()) return false;
      if (hasConnection()) {
        if (!getConnection()
            .equals(other.getConnection())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasConnection()) {
        hash = (37 * hash) + CONNECTION_FIELD_NUMBER;
        hash = (53 * hash) + getConnection().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pandora.L2capProto.MakeConnectionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.L2capProto.MakeConnectionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.L2capProto.MakeConnectionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.L2capProto.MakeConnectionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.L2capProto.MakeConnectionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.L2capProto.MakeConnectionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.L2capProto.MakeConnectionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pandora.L2capProto.MakeConnectionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pandora.L2capProto.MakeConnectionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pandora.L2capProto.MakeConnectionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pandora.L2capProto.MakeConnectionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pandora.L2capProto.MakeConnectionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pandora.L2capProto.MakeConnectionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Request for the `OpenSource` method.
     * </pre>
     *
     * Protobuf type {@code pandora.MakeConnectionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pandora.MakeConnectionRequest)
        pandora.L2capProto.MakeConnectionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pandora.L2capProto.internal_static_pandora_MakeConnectionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pandora.L2capProto.internal_static_pandora_MakeConnectionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pandora.L2capProto.MakeConnectionRequest.class, pandora.L2capProto.MakeConnectionRequest.Builder.class);
      }

      // Construct using pandora.L2capProto.MakeConnectionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (connectionBuilder_ == null) {
          connection_ = null;
        } else {
          connection_ = null;
          connectionBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pandora.L2capProto.internal_static_pandora_MakeConnectionRequest_descriptor;
      }

      @java.lang.Override
      public pandora.L2capProto.MakeConnectionRequest getDefaultInstanceForType() {
        return pandora.L2capProto.MakeConnectionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public pandora.L2capProto.MakeConnectionRequest build() {
        pandora.L2capProto.MakeConnectionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pandora.L2capProto.MakeConnectionRequest buildPartial() {
        pandora.L2capProto.MakeConnectionRequest result = new pandora.L2capProto.MakeConnectionRequest(this);
        if (connectionBuilder_ == null) {
          result.connection_ = connection_;
        } else {
          result.connection_ = connectionBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pandora.L2capProto.MakeConnectionRequest) {
          return mergeFrom((pandora.L2capProto.MakeConnectionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pandora.L2capProto.MakeConnectionRequest other) {
        if (other == pandora.L2capProto.MakeConnectionRequest.getDefaultInstance()) return this;
        if (other.hasConnection()) {
          mergeConnection(other.getConnection());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pandora.L2capProto.MakeConnectionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pandora.L2capProto.MakeConnectionRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private pandora.HostProto.Connection connection_;
      private com.google.protobuf.SingleFieldBuilderV3<
          pandora.HostProto.Connection, pandora.HostProto.Connection.Builder, pandora.HostProto.ConnectionOrBuilder> connectionBuilder_;
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       * @return Whether the connection field is set.
       */
      public boolean hasConnection() {
        return connectionBuilder_ != null || connection_ != null;
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       * @return The connection.
       */
      public pandora.HostProto.Connection getConnection() {
        if (connectionBuilder_ == null) {
          return connection_ == null ? pandora.HostProto.Connection.getDefaultInstance() : connection_;
        } else {
          return connectionBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder setConnection(pandora.HostProto.Connection value) {
        if (connectionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          connection_ = value;
          onChanged();
        } else {
          connectionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder setConnection(
          pandora.HostProto.Connection.Builder builderForValue) {
        if (connectionBuilder_ == null) {
          connection_ = builderForValue.build();
          onChanged();
        } else {
          connectionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder mergeConnection(pandora.HostProto.Connection value) {
        if (connectionBuilder_ == null) {
          if (connection_ != null) {
            connection_ =
              pandora.HostProto.Connection.newBuilder(connection_).mergeFrom(value).buildPartial();
          } else {
            connection_ = value;
          }
          onChanged();
        } else {
          connectionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder clearConnection() {
        if (connectionBuilder_ == null) {
          connection_ = null;
          onChanged();
        } else {
          connection_ = null;
          connectionBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       */
      public pandora.HostProto.Connection.Builder getConnectionBuilder() {
        
        onChanged();
        return getConnectionFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       */
      public pandora.HostProto.ConnectionOrBuilder getConnectionOrBuilder() {
        if (connectionBuilder_ != null) {
          return connectionBuilder_.getMessageOrBuilder();
        } else {
          return connection_ == null ?
              pandora.HostProto.Connection.getDefaultInstance() : connection_;
        }
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pandora.HostProto.Connection, pandora.HostProto.Connection.Builder, pandora.HostProto.ConnectionOrBuilder> 
          getConnectionFieldBuilder() {
        if (connectionBuilder_ == null) {
          connectionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pandora.HostProto.Connection, pandora.HostProto.Connection.Builder, pandora.HostProto.ConnectionOrBuilder>(
                  getConnection(),
                  getParentForChildren(),
                  isClean());
          connection_ = null;
        }
        return connectionBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pandora.MakeConnectionRequest)
    }

    // @@protoc_insertion_point(class_scope:pandora.MakeConnectionRequest)
    private static final pandora.L2capProto.MakeConnectionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pandora.L2capProto.MakeConnectionRequest();
    }

    public static pandora.L2capProto.MakeConnectionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MakeConnectionRequest>
        PARSER = new com.google.protobuf.AbstractParser<MakeConnectionRequest>() {
      @java.lang.Override
      public MakeConnectionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MakeConnectionRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MakeConnectionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MakeConnectionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pandora.L2capProto.MakeConnectionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MakeConnectionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pandora.MakeConnectionResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * Request for the `OpenSource` method.
   * </pre>
   *
   * Protobuf type {@code pandora.MakeConnectionResponse}
   */
  public static final class MakeConnectionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pandora.MakeConnectionResponse)
      MakeConnectionResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MakeConnectionResponse.newBuilder() to construct.
    private MakeConnectionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MakeConnectionResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MakeConnectionResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MakeConnectionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pandora.L2capProto.internal_static_pandora_MakeConnectionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pandora.L2capProto.internal_static_pandora_MakeConnectionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pandora.L2capProto.MakeConnectionResponse.class, pandora.L2capProto.MakeConnectionResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pandora.L2capProto.MakeConnectionResponse)) {
        return super.equals(obj);
      }
      pandora.L2capProto.MakeConnectionResponse other = (pandora.L2capProto.MakeConnectionResponse) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pandora.L2capProto.MakeConnectionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.L2capProto.MakeConnectionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.L2capProto.MakeConnectionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.L2capProto.MakeConnectionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.L2capProto.MakeConnectionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.L2capProto.MakeConnectionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.L2capProto.MakeConnectionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pandora.L2capProto.MakeConnectionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pandora.L2capProto.MakeConnectionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pandora.L2capProto.MakeConnectionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pandora.L2capProto.MakeConnectionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pandora.L2capProto.MakeConnectionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pandora.L2capProto.MakeConnectionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Request for the `OpenSource` method.
     * </pre>
     *
     * Protobuf type {@code pandora.MakeConnectionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pandora.MakeConnectionResponse)
        pandora.L2capProto.MakeConnectionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pandora.L2capProto.internal_static_pandora_MakeConnectionResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pandora.L2capProto.internal_static_pandora_MakeConnectionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pandora.L2capProto.MakeConnectionResponse.class, pandora.L2capProto.MakeConnectionResponse.Builder.class);
      }

      // Construct using pandora.L2capProto.MakeConnectionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pandora.L2capProto.internal_static_pandora_MakeConnectionResponse_descriptor;
      }

      @java.lang.Override
      public pandora.L2capProto.MakeConnectionResponse getDefaultInstanceForType() {
        return pandora.L2capProto.MakeConnectionResponse.getDefaultInstance();
      }

      @java.lang.Override
      public pandora.L2capProto.MakeConnectionResponse build() {
        pandora.L2capProto.MakeConnectionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pandora.L2capProto.MakeConnectionResponse buildPartial() {
        pandora.L2capProto.MakeConnectionResponse result = new pandora.L2capProto.MakeConnectionResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pandora.L2capProto.MakeConnectionResponse) {
          return mergeFrom((pandora.L2capProto.MakeConnectionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pandora.L2capProto.MakeConnectionResponse other) {
        if (other == pandora.L2capProto.MakeConnectionResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pandora.L2capProto.MakeConnectionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pandora.L2capProto.MakeConnectionResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pandora.MakeConnectionResponse)
    }

    // @@protoc_insertion_point(class_scope:pandora.MakeConnectionResponse)
    private static final pandora.L2capProto.MakeConnectionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pandora.L2capProto.MakeConnectionResponse();
    }

    public static pandora.L2capProto.MakeConnectionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MakeConnectionResponse>
        PARSER = new com.google.protobuf.AbstractParser<MakeConnectionResponse>() {
      @java.lang.Override
      public MakeConnectionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MakeConnectionResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MakeConnectionResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MakeConnectionResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pandora.L2capProto.MakeConnectionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SendLEDataPacketRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pandora.SendLEDataPacketRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The connection that will open the stream.
     * </pre>
     *
     * <code>.pandora.Connection connection = 1;</code>
     * @return Whether the connection field is set.
     */
    boolean hasConnection();
    /**
     * <pre>
     * The connection that will open the stream.
     * </pre>
     *
     * <code>.pandora.Connection connection = 1;</code>
     * @return The connection.
     */
    pandora.HostProto.Connection getConnection();
    /**
     * <pre>
     * The connection that will open the stream.
     * </pre>
     *
     * <code>.pandora.Connection connection = 1;</code>
     */
    pandora.HostProto.ConnectionOrBuilder getConnectionOrBuilder();

    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code pandora.SendLEDataPacketRequest}
   */
  public static final class SendLEDataPacketRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pandora.SendLEDataPacketRequest)
      SendLEDataPacketRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SendLEDataPacketRequest.newBuilder() to construct.
    private SendLEDataPacketRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendLEDataPacketRequest() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SendLEDataPacketRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SendLEDataPacketRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pandora.HostProto.Connection.Builder subBuilder = null;
              if (connection_ != null) {
                subBuilder = connection_.toBuilder();
              }
              connection_ = input.readMessage(pandora.HostProto.Connection.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(connection_);
                connection_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pandora.L2capProto.internal_static_pandora_SendLEDataPacketRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pandora.L2capProto.internal_static_pandora_SendLEDataPacketRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pandora.L2capProto.SendLEDataPacketRequest.class, pandora.L2capProto.SendLEDataPacketRequest.Builder.class);
    }

    public static final int CONNECTION_FIELD_NUMBER = 1;
    private pandora.HostProto.Connection connection_;
    /**
     * <pre>
     * The connection that will open the stream.
     * </pre>
     *
     * <code>.pandora.Connection connection = 1;</code>
     * @return Whether the connection field is set.
     */
    @java.lang.Override
    public boolean hasConnection() {
      return connection_ != null;
    }
    /**
     * <pre>
     * The connection that will open the stream.
     * </pre>
     *
     * <code>.pandora.Connection connection = 1;</code>
     * @return The connection.
     */
    @java.lang.Override
    public pandora.HostProto.Connection getConnection() {
      return connection_ == null ? pandora.HostProto.Connection.getDefaultInstance() : connection_;
    }
    /**
     * <pre>
     * The connection that will open the stream.
     * </pre>
     *
     * <code>.pandora.Connection connection = 1;</code>
     */
    @java.lang.Override
    public pandora.HostProto.ConnectionOrBuilder getConnectionOrBuilder() {
      return getConnection();
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (connection_ != null) {
        output.writeMessage(1, getConnection());
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (connection_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getConnection());
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pandora.L2capProto.SendLEDataPacketRequest)) {
        return super.equals(obj);
      }
      pandora.L2capProto.SendLEDataPacketRequest other = (pandora.L2capProto.SendLEDataPacketRequest) obj;

      if (hasConnection() != other.hasConnection()) return false;
      if (hasConnection()) {
        if (!getConnection()
            .equals(other.getConnection())) return false;
      }
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasConnection()) {
        hash = (37 * hash) + CONNECTION_FIELD_NUMBER;
        hash = (53 * hash) + getConnection().hashCode();
      }
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pandora.L2capProto.SendLEDataPacketRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.L2capProto.SendLEDataPacketRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.L2capProto.SendLEDataPacketRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.L2capProto.SendLEDataPacketRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.L2capProto.SendLEDataPacketRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.L2capProto.SendLEDataPacketRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.L2capProto.SendLEDataPacketRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pandora.L2capProto.SendLEDataPacketRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pandora.L2capProto.SendLEDataPacketRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pandora.L2capProto.SendLEDataPacketRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pandora.L2capProto.SendLEDataPacketRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pandora.L2capProto.SendLEDataPacketRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pandora.L2capProto.SendLEDataPacketRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pandora.SendLEDataPacketRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pandora.SendLEDataPacketRequest)
        pandora.L2capProto.SendLEDataPacketRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pandora.L2capProto.internal_static_pandora_SendLEDataPacketRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pandora.L2capProto.internal_static_pandora_SendLEDataPacketRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pandora.L2capProto.SendLEDataPacketRequest.class, pandora.L2capProto.SendLEDataPacketRequest.Builder.class);
      }

      // Construct using pandora.L2capProto.SendLEDataPacketRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (connectionBuilder_ == null) {
          connection_ = null;
        } else {
          connection_ = null;
          connectionBuilder_ = null;
        }
        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pandora.L2capProto.internal_static_pandora_SendLEDataPacketRequest_descriptor;
      }

      @java.lang.Override
      public pandora.L2capProto.SendLEDataPacketRequest getDefaultInstanceForType() {
        return pandora.L2capProto.SendLEDataPacketRequest.getDefaultInstance();
      }

      @java.lang.Override
      public pandora.L2capProto.SendLEDataPacketRequest build() {
        pandora.L2capProto.SendLEDataPacketRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pandora.L2capProto.SendLEDataPacketRequest buildPartial() {
        pandora.L2capProto.SendLEDataPacketRequest result = new pandora.L2capProto.SendLEDataPacketRequest(this);
        if (connectionBuilder_ == null) {
          result.connection_ = connection_;
        } else {
          result.connection_ = connectionBuilder_.build();
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pandora.L2capProto.SendLEDataPacketRequest) {
          return mergeFrom((pandora.L2capProto.SendLEDataPacketRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pandora.L2capProto.SendLEDataPacketRequest other) {
        if (other == pandora.L2capProto.SendLEDataPacketRequest.getDefaultInstance()) return this;
        if (other.hasConnection()) {
          mergeConnection(other.getConnection());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pandora.L2capProto.SendLEDataPacketRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pandora.L2capProto.SendLEDataPacketRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private pandora.HostProto.Connection connection_;
      private com.google.protobuf.SingleFieldBuilderV3<
          pandora.HostProto.Connection, pandora.HostProto.Connection.Builder, pandora.HostProto.ConnectionOrBuilder> connectionBuilder_;
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       * @return Whether the connection field is set.
       */
      public boolean hasConnection() {
        return connectionBuilder_ != null || connection_ != null;
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       * @return The connection.
       */
      public pandora.HostProto.Connection getConnection() {
        if (connectionBuilder_ == null) {
          return connection_ == null ? pandora.HostProto.Connection.getDefaultInstance() : connection_;
        } else {
          return connectionBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder setConnection(pandora.HostProto.Connection value) {
        if (connectionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          connection_ = value;
          onChanged();
        } else {
          connectionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder setConnection(
          pandora.HostProto.Connection.Builder builderForValue) {
        if (connectionBuilder_ == null) {
          connection_ = builderForValue.build();
          onChanged();
        } else {
          connectionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder mergeConnection(pandora.HostProto.Connection value) {
        if (connectionBuilder_ == null) {
          if (connection_ != null) {
            connection_ =
              pandora.HostProto.Connection.newBuilder(connection_).mergeFrom(value).buildPartial();
          } else {
            connection_ = value;
          }
          onChanged();
        } else {
          connectionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder clearConnection() {
        if (connectionBuilder_ == null) {
          connection_ = null;
          onChanged();
        } else {
          connection_ = null;
          connectionBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       */
      public pandora.HostProto.Connection.Builder getConnectionBuilder() {
        
        onChanged();
        return getConnectionFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       */
      public pandora.HostProto.ConnectionOrBuilder getConnectionOrBuilder() {
        if (connectionBuilder_ != null) {
          return connectionBuilder_.getMessageOrBuilder();
        } else {
          return connection_ == null ?
              pandora.HostProto.Connection.getDefaultInstance() : connection_;
        }
      }
      /**
       * <pre>
       * The connection that will open the stream.
       * </pre>
       *
       * <code>.pandora.Connection connection = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pandora.HostProto.Connection, pandora.HostProto.Connection.Builder, pandora.HostProto.ConnectionOrBuilder> 
          getConnectionFieldBuilder() {
        if (connectionBuilder_ == null) {
          connectionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pandora.HostProto.Connection, pandora.HostProto.Connection.Builder, pandora.HostProto.ConnectionOrBuilder>(
                  getConnection(),
                  getParentForChildren(),
                  isClean());
          connection_ = null;
        }
        return connectionBuilder_;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pandora.SendLEDataPacketRequest)
    }

    // @@protoc_insertion_point(class_scope:pandora.SendLEDataPacketRequest)
    private static final pandora.L2capProto.SendLEDataPacketRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pandora.L2capProto.SendLEDataPacketRequest();
    }

    public static pandora.L2capProto.SendLEDataPacketRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendLEDataPacketRequest>
        PARSER = new com.google.protobuf.AbstractParser<SendLEDataPacketRequest>() {
      @java.lang.Override
      public SendLEDataPacketRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendLEDataPacketRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendLEDataPacketRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendLEDataPacketRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pandora.L2capProto.SendLEDataPacketRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SendLEDataPacketResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pandora.SendLEDataPacketResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code pandora.SendLEDataPacketResponse}
   */
  public static final class SendLEDataPacketResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pandora.SendLEDataPacketResponse)
      SendLEDataPacketResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SendLEDataPacketResponse.newBuilder() to construct.
    private SendLEDataPacketResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendLEDataPacketResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SendLEDataPacketResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SendLEDataPacketResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pandora.L2capProto.internal_static_pandora_SendLEDataPacketResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pandora.L2capProto.internal_static_pandora_SendLEDataPacketResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pandora.L2capProto.SendLEDataPacketResponse.class, pandora.L2capProto.SendLEDataPacketResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pandora.L2capProto.SendLEDataPacketResponse)) {
        return super.equals(obj);
      }
      pandora.L2capProto.SendLEDataPacketResponse other = (pandora.L2capProto.SendLEDataPacketResponse) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pandora.L2capProto.SendLEDataPacketResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.L2capProto.SendLEDataPacketResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.L2capProto.SendLEDataPacketResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.L2capProto.SendLEDataPacketResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.L2capProto.SendLEDataPacketResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.L2capProto.SendLEDataPacketResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.L2capProto.SendLEDataPacketResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pandora.L2capProto.SendLEDataPacketResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pandora.L2capProto.SendLEDataPacketResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pandora.L2capProto.SendLEDataPacketResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pandora.L2capProto.SendLEDataPacketResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pandora.L2capProto.SendLEDataPacketResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pandora.L2capProto.SendLEDataPacketResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pandora.SendLEDataPacketResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pandora.SendLEDataPacketResponse)
        pandora.L2capProto.SendLEDataPacketResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pandora.L2capProto.internal_static_pandora_SendLEDataPacketResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pandora.L2capProto.internal_static_pandora_SendLEDataPacketResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pandora.L2capProto.SendLEDataPacketResponse.class, pandora.L2capProto.SendLEDataPacketResponse.Builder.class);
      }

      // Construct using pandora.L2capProto.SendLEDataPacketResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pandora.L2capProto.internal_static_pandora_SendLEDataPacketResponse_descriptor;
      }

      @java.lang.Override
      public pandora.L2capProto.SendLEDataPacketResponse getDefaultInstanceForType() {
        return pandora.L2capProto.SendLEDataPacketResponse.getDefaultInstance();
      }

      @java.lang.Override
      public pandora.L2capProto.SendLEDataPacketResponse build() {
        pandora.L2capProto.SendLEDataPacketResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pandora.L2capProto.SendLEDataPacketResponse buildPartial() {
        pandora.L2capProto.SendLEDataPacketResponse result = new pandora.L2capProto.SendLEDataPacketResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pandora.L2capProto.SendLEDataPacketResponse) {
          return mergeFrom((pandora.L2capProto.SendLEDataPacketResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pandora.L2capProto.SendLEDataPacketResponse other) {
        if (other == pandora.L2capProto.SendLEDataPacketResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pandora.L2capProto.SendLEDataPacketResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pandora.L2capProto.SendLEDataPacketResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pandora.SendLEDataPacketResponse)
    }

    // @@protoc_insertion_point(class_scope:pandora.SendLEDataPacketResponse)
    private static final pandora.L2capProto.SendLEDataPacketResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pandora.L2capProto.SendLEDataPacketResponse();
    }

    public static pandora.L2capProto.SendLEDataPacketResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendLEDataPacketResponse>
        PARSER = new com.google.protobuf.AbstractParser<SendLEDataPacketResponse>() {
      @java.lang.Override
      public SendLEDataPacketResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendLEDataPacketResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendLEDataPacketResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendLEDataPacketResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pandora.L2capProto.SendLEDataPacketResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pandora_MakeConnectionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pandora_MakeConnectionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pandora_MakeConnectionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pandora_MakeConnectionResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pandora_SendLEDataPacketRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pandora_SendLEDataPacketRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pandora_SendLEDataPacketResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pandora_SendLEDataPacketResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023pandora/l2cap.proto\022\007pandora\032\033google/p" +
      "rotobuf/empty.proto\032\022pandora/host.proto\"" +
      "@\n\025MakeConnectionRequest\022\'\n\nconnection\030\001" +
      " \001(\0132\023.pandora.Connection\"\030\n\026MakeConnect" +
      "ionResponse\"P\n\027SendLEDataPacketRequest\022\'" +
      "\n\nconnection\030\001 \001(\0132\023.pandora.Connection\022" +
      "\014\n\004data\030\002 \001(\014\"\032\n\030SendLEDataPacketRespons" +
      "e2\371\001\n\005L2CAP\022D\n\022StartAdvertisement\022\026.goog" +
      "le.protobuf.Empty\032\026.google.protobuf.Empt" +
      "y\022Q\n\016MakeConnection\022\036.pandora.MakeConnec" +
      "tionRequest\032\037.pandora.MakeConnectionResp" +
      "onse\022W\n\020SendLEDataPacket\022 .pandora.SendL" +
      "EDataPacketRequest\032!.pandora.SendLEDataP" +
      "acketResponseB\014B\nL2capProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          pandora.HostProto.getDescriptor(),
        });
    internal_static_pandora_MakeConnectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pandora_MakeConnectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pandora_MakeConnectionRequest_descriptor,
        new java.lang.String[] { "Connection", });
    internal_static_pandora_MakeConnectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pandora_MakeConnectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pandora_MakeConnectionResponse_descriptor,
        new java.lang.String[] { });
    internal_static_pandora_SendLEDataPacketRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pandora_SendLEDataPacketRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pandora_SendLEDataPacketRequest_descriptor,
        new java.lang.String[] { "Connection", "Data", });
    internal_static_pandora_SendLEDataPacketResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pandora_SendLEDataPacketResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pandora_SendLEDataPacketResponse_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.EmptyProto.getDescriptor();
    pandora.HostProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
