// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pandora/sm.proto

package pandora;

public final class SmProto {
  private SmProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PairRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pandora.PairRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.pandora.Connection connection = 1;</code>
     * @return Whether the connection field is set.
     */
    boolean hasConnection();
    /**
     * <code>.pandora.Connection connection = 1;</code>
     * @return The connection.
     */
    pandora.HostProto.Connection getConnection();
    /**
     * <code>.pandora.Connection connection = 1;</code>
     */
    pandora.HostProto.ConnectionOrBuilder getConnectionOrBuilder();
  }
  /**
   * Protobuf type {@code pandora.PairRequest}
   */
  public static final class PairRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pandora.PairRequest)
      PairRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PairRequest.newBuilder() to construct.
    private PairRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PairRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PairRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PairRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pandora.HostProto.Connection.Builder subBuilder = null;
              if (connection_ != null) {
                subBuilder = connection_.toBuilder();
              }
              connection_ = input.readMessage(pandora.HostProto.Connection.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(connection_);
                connection_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pandora.SmProto.internal_static_pandora_PairRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pandora.SmProto.internal_static_pandora_PairRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pandora.SmProto.PairRequest.class, pandora.SmProto.PairRequest.Builder.class);
    }

    public static final int CONNECTION_FIELD_NUMBER = 1;
    private pandora.HostProto.Connection connection_;
    /**
     * <code>.pandora.Connection connection = 1;</code>
     * @return Whether the connection field is set.
     */
    @java.lang.Override
    public boolean hasConnection() {
      return connection_ != null;
    }
    /**
     * <code>.pandora.Connection connection = 1;</code>
     * @return The connection.
     */
    @java.lang.Override
    public pandora.HostProto.Connection getConnection() {
      return connection_ == null ? pandora.HostProto.Connection.getDefaultInstance() : connection_;
    }
    /**
     * <code>.pandora.Connection connection = 1;</code>
     */
    @java.lang.Override
    public pandora.HostProto.ConnectionOrBuilder getConnectionOrBuilder() {
      return getConnection();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (connection_ != null) {
        output.writeMessage(1, getConnection());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (connection_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getConnection());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pandora.SmProto.PairRequest)) {
        return super.equals(obj);
      }
      pandora.SmProto.PairRequest other = (pandora.SmProto.PairRequest) obj;

      if (hasConnection() != other.hasConnection()) return false;
      if (hasConnection()) {
        if (!getConnection()
            .equals(other.getConnection())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasConnection()) {
        hash = (37 * hash) + CONNECTION_FIELD_NUMBER;
        hash = (53 * hash) + getConnection().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pandora.SmProto.PairRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.SmProto.PairRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.SmProto.PairRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.SmProto.PairRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.SmProto.PairRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.SmProto.PairRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.SmProto.PairRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pandora.SmProto.PairRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pandora.SmProto.PairRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pandora.SmProto.PairRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pandora.SmProto.PairRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pandora.SmProto.PairRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pandora.SmProto.PairRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pandora.PairRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pandora.PairRequest)
        pandora.SmProto.PairRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pandora.SmProto.internal_static_pandora_PairRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pandora.SmProto.internal_static_pandora_PairRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pandora.SmProto.PairRequest.class, pandora.SmProto.PairRequest.Builder.class);
      }

      // Construct using pandora.SmProto.PairRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (connectionBuilder_ == null) {
          connection_ = null;
        } else {
          connection_ = null;
          connectionBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pandora.SmProto.internal_static_pandora_PairRequest_descriptor;
      }

      @java.lang.Override
      public pandora.SmProto.PairRequest getDefaultInstanceForType() {
        return pandora.SmProto.PairRequest.getDefaultInstance();
      }

      @java.lang.Override
      public pandora.SmProto.PairRequest build() {
        pandora.SmProto.PairRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pandora.SmProto.PairRequest buildPartial() {
        pandora.SmProto.PairRequest result = new pandora.SmProto.PairRequest(this);
        if (connectionBuilder_ == null) {
          result.connection_ = connection_;
        } else {
          result.connection_ = connectionBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pandora.SmProto.PairRequest) {
          return mergeFrom((pandora.SmProto.PairRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pandora.SmProto.PairRequest other) {
        if (other == pandora.SmProto.PairRequest.getDefaultInstance()) return this;
        if (other.hasConnection()) {
          mergeConnection(other.getConnection());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pandora.SmProto.PairRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pandora.SmProto.PairRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private pandora.HostProto.Connection connection_;
      private com.google.protobuf.SingleFieldBuilderV3<
          pandora.HostProto.Connection, pandora.HostProto.Connection.Builder, pandora.HostProto.ConnectionOrBuilder> connectionBuilder_;
      /**
       * <code>.pandora.Connection connection = 1;</code>
       * @return Whether the connection field is set.
       */
      public boolean hasConnection() {
        return connectionBuilder_ != null || connection_ != null;
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       * @return The connection.
       */
      public pandora.HostProto.Connection getConnection() {
        if (connectionBuilder_ == null) {
          return connection_ == null ? pandora.HostProto.Connection.getDefaultInstance() : connection_;
        } else {
          return connectionBuilder_.getMessage();
        }
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder setConnection(pandora.HostProto.Connection value) {
        if (connectionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          connection_ = value;
          onChanged();
        } else {
          connectionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder setConnection(
          pandora.HostProto.Connection.Builder builderForValue) {
        if (connectionBuilder_ == null) {
          connection_ = builderForValue.build();
          onChanged();
        } else {
          connectionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder mergeConnection(pandora.HostProto.Connection value) {
        if (connectionBuilder_ == null) {
          if (connection_ != null) {
            connection_ =
              pandora.HostProto.Connection.newBuilder(connection_).mergeFrom(value).buildPartial();
          } else {
            connection_ = value;
          }
          onChanged();
        } else {
          connectionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder clearConnection() {
        if (connectionBuilder_ == null) {
          connection_ = null;
          onChanged();
        } else {
          connection_ = null;
          connectionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       */
      public pandora.HostProto.Connection.Builder getConnectionBuilder() {
        
        onChanged();
        return getConnectionFieldBuilder().getBuilder();
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       */
      public pandora.HostProto.ConnectionOrBuilder getConnectionOrBuilder() {
        if (connectionBuilder_ != null) {
          return connectionBuilder_.getMessageOrBuilder();
        } else {
          return connection_ == null ?
              pandora.HostProto.Connection.getDefaultInstance() : connection_;
        }
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pandora.HostProto.Connection, pandora.HostProto.Connection.Builder, pandora.HostProto.ConnectionOrBuilder> 
          getConnectionFieldBuilder() {
        if (connectionBuilder_ == null) {
          connectionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pandora.HostProto.Connection, pandora.HostProto.Connection.Builder, pandora.HostProto.ConnectionOrBuilder>(
                  getConnection(),
                  getParentForChildren(),
                  isClean());
          connection_ = null;
        }
        return connectionBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pandora.PairRequest)
    }

    // @@protoc_insertion_point(class_scope:pandora.PairRequest)
    private static final pandora.SmProto.PairRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pandora.SmProto.PairRequest();
    }

    public static pandora.SmProto.PairRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PairRequest>
        PARSER = new com.google.protobuf.AbstractParser<PairRequest>() {
      @java.lang.Override
      public PairRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PairRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PairRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PairRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pandora.SmProto.PairRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PairingConfirmationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pandora.PairingConfirmationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.pandora.Connection connection = 1;</code>
     * @return Whether the connection field is set.
     */
    boolean hasConnection();
    /**
     * <code>.pandora.Connection connection = 1;</code>
     * @return The connection.
     */
    pandora.HostProto.Connection getConnection();
    /**
     * <code>.pandora.Connection connection = 1;</code>
     */
    pandora.HostProto.ConnectionOrBuilder getConnectionOrBuilder();

    /**
     * <code>bool pairing_confirmation_value = 2;</code>
     * @return The pairingConfirmationValue.
     */
    boolean getPairingConfirmationValue();
  }
  /**
   * Protobuf type {@code pandora.PairingConfirmationRequest}
   */
  public static final class PairingConfirmationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pandora.PairingConfirmationRequest)
      PairingConfirmationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PairingConfirmationRequest.newBuilder() to construct.
    private PairingConfirmationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PairingConfirmationRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PairingConfirmationRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PairingConfirmationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pandora.HostProto.Connection.Builder subBuilder = null;
              if (connection_ != null) {
                subBuilder = connection_.toBuilder();
              }
              connection_ = input.readMessage(pandora.HostProto.Connection.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(connection_);
                connection_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              pairingConfirmationValue_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pandora.SmProto.internal_static_pandora_PairingConfirmationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pandora.SmProto.internal_static_pandora_PairingConfirmationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pandora.SmProto.PairingConfirmationRequest.class, pandora.SmProto.PairingConfirmationRequest.Builder.class);
    }

    public static final int CONNECTION_FIELD_NUMBER = 1;
    private pandora.HostProto.Connection connection_;
    /**
     * <code>.pandora.Connection connection = 1;</code>
     * @return Whether the connection field is set.
     */
    @java.lang.Override
    public boolean hasConnection() {
      return connection_ != null;
    }
    /**
     * <code>.pandora.Connection connection = 1;</code>
     * @return The connection.
     */
    @java.lang.Override
    public pandora.HostProto.Connection getConnection() {
      return connection_ == null ? pandora.HostProto.Connection.getDefaultInstance() : connection_;
    }
    /**
     * <code>.pandora.Connection connection = 1;</code>
     */
    @java.lang.Override
    public pandora.HostProto.ConnectionOrBuilder getConnectionOrBuilder() {
      return getConnection();
    }

    public static final int PAIRING_CONFIRMATION_VALUE_FIELD_NUMBER = 2;
    private boolean pairingConfirmationValue_;
    /**
     * <code>bool pairing_confirmation_value = 2;</code>
     * @return The pairingConfirmationValue.
     */
    @java.lang.Override
    public boolean getPairingConfirmationValue() {
      return pairingConfirmationValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (connection_ != null) {
        output.writeMessage(1, getConnection());
      }
      if (pairingConfirmationValue_ != false) {
        output.writeBool(2, pairingConfirmationValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (connection_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getConnection());
      }
      if (pairingConfirmationValue_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, pairingConfirmationValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pandora.SmProto.PairingConfirmationRequest)) {
        return super.equals(obj);
      }
      pandora.SmProto.PairingConfirmationRequest other = (pandora.SmProto.PairingConfirmationRequest) obj;

      if (hasConnection() != other.hasConnection()) return false;
      if (hasConnection()) {
        if (!getConnection()
            .equals(other.getConnection())) return false;
      }
      if (getPairingConfirmationValue()
          != other.getPairingConfirmationValue()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasConnection()) {
        hash = (37 * hash) + CONNECTION_FIELD_NUMBER;
        hash = (53 * hash) + getConnection().hashCode();
      }
      hash = (37 * hash) + PAIRING_CONFIRMATION_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPairingConfirmationValue());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pandora.SmProto.PairingConfirmationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.SmProto.PairingConfirmationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.SmProto.PairingConfirmationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.SmProto.PairingConfirmationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.SmProto.PairingConfirmationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pandora.SmProto.PairingConfirmationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pandora.SmProto.PairingConfirmationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pandora.SmProto.PairingConfirmationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pandora.SmProto.PairingConfirmationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pandora.SmProto.PairingConfirmationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pandora.SmProto.PairingConfirmationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pandora.SmProto.PairingConfirmationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pandora.SmProto.PairingConfirmationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pandora.PairingConfirmationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pandora.PairingConfirmationRequest)
        pandora.SmProto.PairingConfirmationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pandora.SmProto.internal_static_pandora_PairingConfirmationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pandora.SmProto.internal_static_pandora_PairingConfirmationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pandora.SmProto.PairingConfirmationRequest.class, pandora.SmProto.PairingConfirmationRequest.Builder.class);
      }

      // Construct using pandora.SmProto.PairingConfirmationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (connectionBuilder_ == null) {
          connection_ = null;
        } else {
          connection_ = null;
          connectionBuilder_ = null;
        }
        pairingConfirmationValue_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pandora.SmProto.internal_static_pandora_PairingConfirmationRequest_descriptor;
      }

      @java.lang.Override
      public pandora.SmProto.PairingConfirmationRequest getDefaultInstanceForType() {
        return pandora.SmProto.PairingConfirmationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public pandora.SmProto.PairingConfirmationRequest build() {
        pandora.SmProto.PairingConfirmationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pandora.SmProto.PairingConfirmationRequest buildPartial() {
        pandora.SmProto.PairingConfirmationRequest result = new pandora.SmProto.PairingConfirmationRequest(this);
        if (connectionBuilder_ == null) {
          result.connection_ = connection_;
        } else {
          result.connection_ = connectionBuilder_.build();
        }
        result.pairingConfirmationValue_ = pairingConfirmationValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pandora.SmProto.PairingConfirmationRequest) {
          return mergeFrom((pandora.SmProto.PairingConfirmationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pandora.SmProto.PairingConfirmationRequest other) {
        if (other == pandora.SmProto.PairingConfirmationRequest.getDefaultInstance()) return this;
        if (other.hasConnection()) {
          mergeConnection(other.getConnection());
        }
        if (other.getPairingConfirmationValue() != false) {
          setPairingConfirmationValue(other.getPairingConfirmationValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pandora.SmProto.PairingConfirmationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pandora.SmProto.PairingConfirmationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private pandora.HostProto.Connection connection_;
      private com.google.protobuf.SingleFieldBuilderV3<
          pandora.HostProto.Connection, pandora.HostProto.Connection.Builder, pandora.HostProto.ConnectionOrBuilder> connectionBuilder_;
      /**
       * <code>.pandora.Connection connection = 1;</code>
       * @return Whether the connection field is set.
       */
      public boolean hasConnection() {
        return connectionBuilder_ != null || connection_ != null;
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       * @return The connection.
       */
      public pandora.HostProto.Connection getConnection() {
        if (connectionBuilder_ == null) {
          return connection_ == null ? pandora.HostProto.Connection.getDefaultInstance() : connection_;
        } else {
          return connectionBuilder_.getMessage();
        }
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder setConnection(pandora.HostProto.Connection value) {
        if (connectionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          connection_ = value;
          onChanged();
        } else {
          connectionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder setConnection(
          pandora.HostProto.Connection.Builder builderForValue) {
        if (connectionBuilder_ == null) {
          connection_ = builderForValue.build();
          onChanged();
        } else {
          connectionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder mergeConnection(pandora.HostProto.Connection value) {
        if (connectionBuilder_ == null) {
          if (connection_ != null) {
            connection_ =
              pandora.HostProto.Connection.newBuilder(connection_).mergeFrom(value).buildPartial();
          } else {
            connection_ = value;
          }
          onChanged();
        } else {
          connectionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       */
      public Builder clearConnection() {
        if (connectionBuilder_ == null) {
          connection_ = null;
          onChanged();
        } else {
          connection_ = null;
          connectionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       */
      public pandora.HostProto.Connection.Builder getConnectionBuilder() {
        
        onChanged();
        return getConnectionFieldBuilder().getBuilder();
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       */
      public pandora.HostProto.ConnectionOrBuilder getConnectionOrBuilder() {
        if (connectionBuilder_ != null) {
          return connectionBuilder_.getMessageOrBuilder();
        } else {
          return connection_ == null ?
              pandora.HostProto.Connection.getDefaultInstance() : connection_;
        }
      }
      /**
       * <code>.pandora.Connection connection = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pandora.HostProto.Connection, pandora.HostProto.Connection.Builder, pandora.HostProto.ConnectionOrBuilder> 
          getConnectionFieldBuilder() {
        if (connectionBuilder_ == null) {
          connectionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pandora.HostProto.Connection, pandora.HostProto.Connection.Builder, pandora.HostProto.ConnectionOrBuilder>(
                  getConnection(),
                  getParentForChildren(),
                  isClean());
          connection_ = null;
        }
        return connectionBuilder_;
      }

      private boolean pairingConfirmationValue_ ;
      /**
       * <code>bool pairing_confirmation_value = 2;</code>
       * @return The pairingConfirmationValue.
       */
      @java.lang.Override
      public boolean getPairingConfirmationValue() {
        return pairingConfirmationValue_;
      }
      /**
       * <code>bool pairing_confirmation_value = 2;</code>
       * @param value The pairingConfirmationValue to set.
       * @return This builder for chaining.
       */
      public Builder setPairingConfirmationValue(boolean value) {
        
        pairingConfirmationValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool pairing_confirmation_value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPairingConfirmationValue() {
        
        pairingConfirmationValue_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pandora.PairingConfirmationRequest)
    }

    // @@protoc_insertion_point(class_scope:pandora.PairingConfirmationRequest)
    private static final pandora.SmProto.PairingConfirmationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pandora.SmProto.PairingConfirmationRequest();
    }

    public static pandora.SmProto.PairingConfirmationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PairingConfirmationRequest>
        PARSER = new com.google.protobuf.AbstractParser<PairingConfirmationRequest>() {
      @java.lang.Override
      public PairingConfirmationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PairingConfirmationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PairingConfirmationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PairingConfirmationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pandora.SmProto.PairingConfirmationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pandora_PairRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pandora_PairRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pandora_PairingConfirmationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pandora_PairingConfirmationRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020pandora/sm.proto\022\007pandora\032\022pandora/hos" +
      "t.proto\032\033google/protobuf/empty.proto\"6\n\013" +
      "PairRequest\022\'\n\nconnection\030\001 \001(\0132\023.pandor" +
      "a.Connection\"i\n\032PairingConfirmationReque" +
      "st\022\'\n\nconnection\030\001 \001(\0132\023.pandora.Connect" +
      "ion\022\"\n\032pairing_confirmation_value\030\002 \001(\0102" +
      "\225\001\n\002SM\0224\n\004Pair\022\024.pandora.PairRequest\032\026.g" +
      "oogle.protobuf.Empty\022Y\n\032ProvidePairingCo" +
      "nfirmation\022#.pandora.PairingConfirmation" +
      "Request\032\026.google.protobuf.EmptyB\tB\007SmPro" +
      "tob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pandora.HostProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_pandora_PairRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pandora_PairRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pandora_PairRequest_descriptor,
        new java.lang.String[] { "Connection", });
    internal_static_pandora_PairingConfirmationRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pandora_PairingConfirmationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pandora_PairingConfirmationRequest_descriptor,
        new java.lang.String[] { "Connection", "PairingConfirmationValue", });
    pandora.HostProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
