/*
 * Copyright 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#define LOG_TAG "test"

#include <gtest/gtest.h>
#include <log/log.h>

#include "bluetooth/logger.h"
#include "truncating_buffer.h"

/// Captures the latest message generated by the android vlog
/// implementation.
static std::optional<__android_log_message> androidLogMessage;

/// Mask the implementation from liblog.
int __android_log_is_loggable(int /*prio*/, const char* /*tag*/,
                              int /*default_prio*/) {
  return true;
}

/// Mask the implementation from liblog.
void __android_log_write_log_message(
    struct __android_log_message* log_message) {
  if (log_message != nullptr) {
    androidLogMessage.emplace(*log_message);
  }
}

TEST(BluetoothLoggerTest, verbose) {
  androidLogMessage.reset();

  logger::verbose("verbose test");

  ASSERT_TRUE(androidLogMessage.has_value());
  EXPECT_EQ(androidLogMessage->priority, ANDROID_LOG_VERBOSE);
  EXPECT_STREQ(androidLogMessage->tag, LOG_TAG);
  EXPECT_STREQ(androidLogMessage->file,
               "packages/modules/Bluetooth/system/logger/src/vlog_test.cc");
  EXPECT_EQ(androidLogMessage->line, 46);
  EXPECT_STREQ(androidLogMessage->message, "TestBody: verbose test");
}

TEST(BluetoothLoggerTest, debug) {
  androidLogMessage.reset();

  logger::debug("debug test");

  ASSERT_TRUE(androidLogMessage.has_value());
  EXPECT_EQ(androidLogMessage->priority, ANDROID_LOG_DEBUG);
  EXPECT_STREQ(androidLogMessage->tag, LOG_TAG);
  EXPECT_STREQ(androidLogMessage->file,
               "packages/modules/Bluetooth/system/logger/src/vlog_test.cc");
  EXPECT_EQ(androidLogMessage->line, 60);
  EXPECT_STREQ(androidLogMessage->message, "TestBody: debug test");
}

TEST(BluetoothLoggerTest, info) {
  androidLogMessage.reset();

  logger::info("info test");

  ASSERT_TRUE(androidLogMessage.has_value());
  EXPECT_EQ(androidLogMessage->priority, ANDROID_LOG_INFO);
  EXPECT_STREQ(androidLogMessage->tag, LOG_TAG);
  EXPECT_STREQ(androidLogMessage->file,
               "packages/modules/Bluetooth/system/logger/src/vlog_test.cc");
  EXPECT_EQ(androidLogMessage->line, 74);
  EXPECT_STREQ(androidLogMessage->message, "TestBody: info test");
}

TEST(BluetoothLoggerTest, warn) {
  androidLogMessage.reset();

  logger::warn("warn test");

  ASSERT_TRUE(androidLogMessage.has_value());
  EXPECT_EQ(androidLogMessage->priority, ANDROID_LOG_WARN);
  EXPECT_STREQ(androidLogMessage->tag, LOG_TAG);
  EXPECT_STREQ(androidLogMessage->file,
               "packages/modules/Bluetooth/system/logger/src/vlog_test.cc");
  EXPECT_EQ(androidLogMessage->line, 88);
  EXPECT_STREQ(androidLogMessage->message, "TestBody: warn test");
}

TEST(BluetoothLoggerTest, error) {
  androidLogMessage.reset();

  logger::error("error test");

  ASSERT_TRUE(androidLogMessage.has_value());
  EXPECT_EQ(androidLogMessage->priority, ANDROID_LOG_ERROR);
  EXPECT_STREQ(androidLogMessage->tag, LOG_TAG);
  EXPECT_STREQ(androidLogMessage->file,
               "packages/modules/Bluetooth/system/logger/src/vlog_test.cc");
  EXPECT_EQ(androidLogMessage->line, 102);
  EXPECT_STREQ(androidLogMessage->message, "TestBody: error test");
}
