syntax = "proto3";

option java_outer_classname = "SmProto";

import "pandora/host.proto";
import "google/protobuf/empty.proto";

package pandora;

service SM {
    rpc ConnectLE(ConnectLERequest) returns (ConnectLEResponse);
    rpc Pair(PairRequest) returns (google.protobuf.Empty);
    rpc DisconnectLE(DisconnectLERequest) returns (google.protobuf.Empty);
    rpc AcceptPairingConfirmationDialog(PairingConfirmRequest) returns (google.protobuf.Empty);
}

message ConnectLERequest {
    bytes address = 1;
}

message ConnectLEResponse {
    oneof result {
        Connection connection = 1;
    }
}

message PairRequest {
    Connection connection = 1;
}

message DisconnectLERequest {
    Connection connection = 1;
}

message PairingConfirmRequest {
    Connection connection = 1;
}
