# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pandora_experimental/avrcp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pandora_experimental/avrcp.proto',
  package='pandora',
  syntax='proto3',
  serialized_options=b'B\nAvrcpProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n pandora_experimental/avrcp.proto\x12\x07pandora2\x07\n\x05\x41VRCPB\x0c\x42\nAvrcpProtob\x06proto3'
)



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_AVRCP = _descriptor.ServiceDescriptor(
  name='AVRCP',
  full_name='pandora.AVRCP',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=45,
  serialized_end=52,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_AVRCP)

DESCRIPTOR.services_by_name['AVRCP'] = _AVRCP

# @@protoc_insertion_point(module_scope)
