# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pandora_experimental/pan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pandora import host_pb2 as pandora_dot_host__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pandora_experimental/pan.proto',
  package='pandora',
  syntax='proto3',
  serialized_options=b'B\010PanProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1epandora_experimental/pan.proto\x12\x07pandora\x1a\x12pandora/host.proto\"\x18\n\x16\x45nableTetheringRequest\"\x19\n\x17\x45nableTetheringResponse\"$\n\x11\x43onnectPanRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\"=\n\x12\x43onnectPanResponse\x12\'\n\nconnection\x18\x01 \x01(\x0b\x32\x13.pandora.Connection2\xa2\x01\n\x03PAN\x12T\n\x0f\x45nableTethering\x12\x1f.pandora.EnableTetheringRequest\x1a .pandora.EnableTetheringResponse\x12\x45\n\nConnectPan\x12\x1a.pandora.ConnectPanRequest\x1a\x1b.pandora.ConnectPanResponseB\nB\x08PanProtob\x06proto3'
  ,
  dependencies=[pandora_dot_host__pb2.DESCRIPTOR,])




_ENABLETETHERINGREQUEST = _descriptor.Descriptor(
  name='EnableTetheringRequest',
  full_name='pandora.EnableTetheringRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=87,
)


_ENABLETETHERINGRESPONSE = _descriptor.Descriptor(
  name='EnableTetheringResponse',
  full_name='pandora.EnableTetheringResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=114,
)


_CONNECTPANREQUEST = _descriptor.Descriptor(
  name='ConnectPanRequest',
  full_name='pandora.ConnectPanRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='pandora.ConnectPanRequest.address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=152,
)


_CONNECTPANRESPONSE = _descriptor.Descriptor(
  name='ConnectPanResponse',
  full_name='pandora.ConnectPanResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='connection', full_name='pandora.ConnectPanResponse.connection', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=215,
)

_CONNECTPANRESPONSE.fields_by_name['connection'].message_type = pandora_dot_host__pb2._CONNECTION
DESCRIPTOR.message_types_by_name['EnableTetheringRequest'] = _ENABLETETHERINGREQUEST
DESCRIPTOR.message_types_by_name['EnableTetheringResponse'] = _ENABLETETHERINGRESPONSE
DESCRIPTOR.message_types_by_name['ConnectPanRequest'] = _CONNECTPANREQUEST
DESCRIPTOR.message_types_by_name['ConnectPanResponse'] = _CONNECTPANRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnableTetheringRequest = _reflection.GeneratedProtocolMessageType('EnableTetheringRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENABLETETHERINGREQUEST,
  '__module__' : 'pandora_experimental.pan_pb2'
  # @@protoc_insertion_point(class_scope:pandora.EnableTetheringRequest)
  })
_sym_db.RegisterMessage(EnableTetheringRequest)

EnableTetheringResponse = _reflection.GeneratedProtocolMessageType('EnableTetheringResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENABLETETHERINGRESPONSE,
  '__module__' : 'pandora_experimental.pan_pb2'
  # @@protoc_insertion_point(class_scope:pandora.EnableTetheringResponse)
  })
_sym_db.RegisterMessage(EnableTetheringResponse)

ConnectPanRequest = _reflection.GeneratedProtocolMessageType('ConnectPanRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTPANREQUEST,
  '__module__' : 'pandora_experimental.pan_pb2'
  # @@protoc_insertion_point(class_scope:pandora.ConnectPanRequest)
  })
_sym_db.RegisterMessage(ConnectPanRequest)

ConnectPanResponse = _reflection.GeneratedProtocolMessageType('ConnectPanResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTPANRESPONSE,
  '__module__' : 'pandora_experimental.pan_pb2'
  # @@protoc_insertion_point(class_scope:pandora.ConnectPanResponse)
  })
_sym_db.RegisterMessage(ConnectPanResponse)


DESCRIPTOR._options = None

_PAN = _descriptor.ServiceDescriptor(
  name='PAN',
  full_name='pandora.PAN',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=218,
  serialized_end=380,
  methods=[
  _descriptor.MethodDescriptor(
    name='EnableTethering',
    full_name='pandora.PAN.EnableTethering',
    index=0,
    containing_service=None,
    input_type=_ENABLETETHERINGREQUEST,
    output_type=_ENABLETETHERINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ConnectPan',
    full_name='pandora.PAN.ConnectPan',
    index=1,
    containing_service=None,
    input_type=_CONNECTPANREQUEST,
    output_type=_CONNECTPANRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PAN)

DESCRIPTOR.services_by_name['PAN'] = _PAN

# @@protoc_insertion_point(module_scope)
