# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pandora_experimental/pbap.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pandora_experimental/pbap.proto',
  package='pandora',
  syntax='proto3',
  serialized_options=b'B\tPbapProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fpandora_experimental/pbap.proto\x12\x07pandora2\x06\n\x04PBAPB\x0b\x42\tPbapProtob\x06proto3'
)



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_PBAP = _descriptor.ServiceDescriptor(
  name='PBAP',
  full_name='pandora.PBAP',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=44,
  serialized_end=50,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_PBAP)

DESCRIPTOR.services_by_name['PBAP'] = _PBAP

# @@protoc_insertion_point(module_scope)
