#
#  Copyright 2024 Google, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at:
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

# Generate c++ headers for each sysprop file
#
# Parameters:
#   sources: sysprop source files
template("sysprop") {
  forward_variables_from(invoker, [ "sources" ])
  assert(defined(sources), "sources must be set")

  outdir = rebase_path(target_gen_dir)

  sysprop_sources = []
  sysprop_deps = []

  foreach(source, sources) {
    rel_source = rebase_path(source, ".")

    action("${target_name}_${source}") {
      source = rebase_path(source)

      script = "//common-mk/file_generator_wrapper.py"
      args = [
        "sysprop_cpp",
        "--header-dir=${outdir}/include",
        "--public-header-dir=${outdir}/public",
        "--source-dir=${outdir}/src",
        "--include-name=${rel_source}.h",
        "${source}",
      ]

      outputs = [
        "${outdir}/include/${rel_source}.h",
        "${outdir}/src/${rel_source}.cpp",
        "${outdir}/public/${rel_source}.h",
      ]
    }

    sysprop_sources += [ "${outdir}/src/${rel_source}.cpp" ]
    sysprop_deps += [ ":${target_name}_${source}" ]
  }

  all_dependent_config_name = "_${target_name}_all_dependent_config"
  config(all_dependent_config_name) {
    include_dirs = [ "${outdir}/include" ]
  }

  static_library(target_name) {
    sources = []
    sources = sysprop_sources
    public_deps = sysprop_deps
    deps = invoker.deps
    all_dependent_configs = [ ":${all_dependent_config_name}" ]
  }
}
