/******************************************************************************
 *
 *  Copyright 1999-2012 Broadcom Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at:
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ******************************************************************************/

#ifndef BTM_BLE_API_TYPES_H
#define BTM_BLE_API_TYPES_H

#include <base/functional/callback_forward.h>
#include <bluetooth/log.h>
#include <hardware/bt_common_types.h>

#include <cstdint>
#include <vector>

#include "stack/include/bt_octets.h"
#include "stack/include/btm_status.h"
#include "stack/include/hci_error_code.h"
#include "types/ble_address_with_type.h"
#include "types/raw_address.h"

#define CHNL_MAP_LEN 5
typedef uint8_t tBTM_BLE_CHNL_MAP[CHNL_MAP_LEN];

enum : uint8_t {
  /* 0x00-0x04 only used for set advertising parameter command */
  BTM_BLE_CONNECT_EVT = 0x00,
  /* Connectable directed advertising */
  BTM_BLE_CONNECT_DIR_EVT = 0x01,
  /* Scannable undirected advertising */
  BTM_BLE_DISCOVER_EVT = 0x02,
  /* Non connectable undirected advertising */
  BTM_BLE_NON_CONNECT_EVT = 0x03,
  /* Connectable low duty cycle directed advertising  */
  BTM_BLE_CONNECT_LO_DUTY_DIR_EVT = 0x04,
};

/* 0x00 - 0x04 can be received on adv event type */
typedef enum : uint8_t {
  BTM_BLE_ADV_IND_EVT = 0x00,
  BTM_BLE_ADV_DIRECT_IND_EVT = 0x01,
  BTM_BLE_ADV_SCAN_IND_EVT = 0x02,
  BTM_BLE_ADV_NONCONN_IND_EVT = 0x03,
  BTM_BLE_SCAN_RSP_EVT = 0x04,
} tBTM_BLE_EVT;

typedef uint32_t tBTM_BLE_REF_VALUE;

#define BTM_BLE_SCAN_MODE_PASS 0
#define BTM_BLE_SCAN_MODE_ACTI 1
#define BTM_BLE_SCAN_MODE_NONE 0xff
typedef uint8_t tBLE_SCAN_MODE;

#define BTM_BLE_BATCH_SCAN_MODE_DISABLE 0
#define BTM_BLE_BATCH_SCAN_MODE_PASS 1
#define BTM_BLE_BATCH_SCAN_MODE_ACTI 2
#define BTM_BLE_BATCH_SCAN_MODE_PASS_ACTI 3

typedef uint8_t tBTM_BLE_BATCH_SCAN_MODE;

/* advertising channel map */
#define BTM_BLE_ADV_CHNL_37 (0x01 << 0)
#define BTM_BLE_ADV_CHNL_38 (0x01 << 1)
#define BTM_BLE_ADV_CHNL_39 (0x01 << 2)
typedef uint8_t tBTM_BLE_ADV_CHNL_MAP;

/*d efault advertising channel map */
#ifndef BTM_BLE_DEFAULT_ADV_CHNL_MAP
#define BTM_BLE_DEFAULT_ADV_CHNL_MAP \
  (BTM_BLE_ADV_CHNL_37 | BTM_BLE_ADV_CHNL_38 | BTM_BLE_ADV_CHNL_39)
#endif

/* advertising filter policy */
#define AP_SCAN_CONN_ALL 0x00 /* default */
#define AP_SCAN_WL_CONN_ALL 0x01
#define AP_SCAN_ALL_CONN_WL 0x02
#define AP_SCAN_CONN_WL 0x03
#define AP_SCAN_CONN_POLICY_MAX 0x04
typedef uint8_t tBTM_BLE_AFP;

/* default advertising filter policy */
#ifndef BTM_BLE_DEFAULT_AFP
#define BTM_BLE_DEFAULT_AFP AP_SCAN_CONN_ALL
#endif

/* scanning filter policy */
/* 0: accept adv packet from all, directed adv pkt not directed */
/*    to local device is ignored */
#define SP_ADV_ALL 0x00

typedef uint8_t tBTM_BLE_SFP;

#ifndef BTM_BLE_DEFAULT_SFP
#define BTM_BLE_DEFAULT_SFP SP_ADV_ALL
#endif

/* Full scan boundary values */
#define BTM_BLE_ADV_SCAN_FULL_MIN 0x00
#define BTM_BLE_ADV_SCAN_FULL_MAX 0x64

/* Partial scan boundary values */
#define BTM_BLE_ADV_SCAN_TRUNC_MAX BTM_BLE_ADV_SCAN_FULL_MAX

/* Threshold values */
#define BTM_BLE_ADV_SCAN_THR_MAX BTM_BLE_ADV_SCAN_FULL_MAX

/* connection parameter boundary values */
#define BTM_BLE_SCAN_INT_MIN 0x0004
#define BTM_BLE_SCAN_INT_MAX 0x4000
#define BTM_BLE_SCAN_WIN_MIN 0x0004
#define BTM_BLE_SCAN_WIN_MAX 0x4000
#define BTM_BLE_EXT_SCAN_INT_MAX 0x00FFFFFF
#define BTM_BLE_EXT_SCAN_WIN_MAX 0xFFFF
#define BTM_BLE_CONN_INT_MIN 0x0006
#define BTM_BLE_CONN_INT_MAX 0x0C80
#define BTM_BLE_CONN_LATENCY_MAX 500
#define BTM_BLE_CONN_SUP_TOUT_MIN 0x000A
#define BTM_BLE_CONN_SUP_TOUT_MAX 0x0C80
/* use this value when a specific value not to be overwritten */
#define BTM_BLE_CONN_PARAM_UNDEF 0xffff
#define BTM_BLE_SCAN_PARAM_UNDEF 0xffff

/* default connection parameters if not configured, use GAP recommended value
 * for auto/selective connection */
/* default scan interval */
#ifndef BTM_BLE_SCAN_FAST_INT
#define BTM_BLE_SCAN_FAST_INT 96 /* 30 ~ 60 ms (use 60)  = 96 *0.625 */
#endif
/* default scan window for background connection, applicable for auto connection
 * or selective connection */
#ifndef BTM_BLE_SCAN_FAST_WIN
#define BTM_BLE_SCAN_FAST_WIN 48 /* 30 ms = 48 *0.625 */
#endif

/* default scan paramter used in reduced power cycle (background scanning) */
#ifndef BTM_BLE_SCAN_SLOW_INT_1
#define BTM_BLE_SCAN_SLOW_INT_1 2048 /* 1.28 s   = 2048 *0.625 */
#endif
#ifndef BTM_BLE_SCAN_SLOW_WIN_1
#define BTM_BLE_SCAN_SLOW_WIN_1 48 /* 30 ms = 48 *0.625 */
#endif

/* default scan paramter used in reduced power cycle (background scanning) */
#ifndef BTM_BLE_SCAN_SLOW_INT_2
#define BTM_BLE_SCAN_SLOW_INT_2 4096 /* 2.56 s   = 4096 *0.625 */
#endif
#ifndef BTM_BLE_SCAN_SLOW_WIN_2
#define BTM_BLE_SCAN_SLOW_WIN_2 36 /* 22.5 ms = 36 *0.625 */
#endif

/* default connection interval min */
#ifndef BTM_BLE_CONN_INT_MIN_DEF
/* recommended min: 30ms  = 24 * 1.25 */
#ifndef BTM_BLE_CONN_INT_MIN_DEF
#define BTM_BLE_CONN_INT_MIN_DEF 24
#endif
#endif

/* default connectino interval max */
#ifndef BTM_BLE_CONN_INT_MAX_DEF
/* recommended max: 50 ms = 56 * 1.25 */
#ifndef BTM_BLE_CONN_INT_MAX_DEF
#define BTM_BLE_CONN_INT_MAX_DEF 40
#endif
#endif

/* default peripheral latency */
#ifndef BTM_BLE_CONN_PERIPHERAL_LATENCY_DEF
#define BTM_BLE_CONN_PERIPHERAL_LATENCY_DEF 0 /* 0 */
#endif

/* default supervision timeout */
#ifndef BTM_BLE_CONN_TIMEOUT_DEF
#define BTM_BLE_CONN_TIMEOUT_DEF 500
#endif

/* minimum supervision timeout */
#ifndef BTM_BLE_CONN_TIMEOUT_MIN_DEF
#define BTM_BLE_CONN_TIMEOUT_MIN_DEF 100
#endif

/* minimum acceptable connection interval */
#ifndef BTM_BLE_CONN_INT_MIN_LIMIT
#define BTM_BLE_CONN_INT_MIN_LIMIT 0x0009
#endif

/* minimum acceptable connection interval when there is bonded Hearing Aid
 * device */
#ifndef BTM_BLE_CONN_INT_MIN_HEARINGAID
#define BTM_BLE_CONN_INT_MIN_HEARINGAID 0x0010
#endif

#define BTM_CMAC_TLEN_SIZE 8     /* 64 bits */
#define BTM_BLE_AUTH_SIGN_LEN 12 /* BLE data signature length 8 Bytes + 4 bytes counter*/
typedef uint8_t BLE_SIGNATURE[BTM_BLE_AUTH_SIGN_LEN]; /* Device address */

#ifndef BTM_BLE_HOST_SUPPORT
#define BTM_BLE_HOST_SUPPORT 0x01
#endif

#ifndef BTM_BLE_SIMULTANEOUS_HOST
#define BTM_BLE_SIMULTANEOUS_HOST 0x01
#endif

/* Appearance Values Reported with BTM_BLE_AD_TYPE_APPEARANCE */
/* Category[15:6] 0x000 */
#define BTM_BLE_APPEARANCE_UKNOWN 0x0000

/* Category[15:6] 0x001 */
#define BTM_BLE_APPEARANCE_GENERIC_PHONE 0x0040

/* Category[15:6] 0x002 */
#define BTM_BLE_APPEARANCE_GENERIC_COMPUTER 0x0080
#define BTM_BLE_APPEARANCE_DESKTOP_WORKSTATION 0x81
#define BTM_BLE_APPEARANCE_SERVER_CLASS_COMPUTER 0x82
#define BTM_BLE_APPEARANCE_LAPTOP 0x83
#define BTM_BLE_APPEARANCE_HANDHELD_PC_PDA 0x84
#define BTM_BLE_APPEARANCE_PALM_SIZE_PC_PDA 0x85
#define BTM_BLE_APPEARANCE_WEARABLE_COMPUTER_WATCH_SIZE 0x86
#define BTM_BLE_APPEARANCE_TABLET 0x87
#define BTM_BLE_APPEARANCE_DOCKING_STATION 0x88
#define BTM_BLE_APPEARANCE_ALL_IN_ONE 0x89
#define BTM_BLE_APPEARANCE_BLADE_SERVER 0x8A
#define BTM_BLE_APPEARANCE_CONVERTIBLE 0x8B
#define BTM_BLE_APPEARANCE_DETACHABLE 0x8C
#define BTM_BLE_APPEARANCE_IOT_GATEWAY 0x8D
#define BTM_BLE_APPEARANCE_MINI_PC 0x8E
#define BTM_BLE_APPEARANCE_STICK_PC 0x8F

/* Category[15:6] 0x003 */
#define BTM_BLE_APPEARANCE_GENERIC_WATCH 0x00C0
#define BTM_BLE_APPEARANCE_SPORTS_WATCH 0x00C1
#define BTM_BLE_APPEARANCE_SMART_WATCH 0x00C2

/* Category[15:6] 0x004 */
#define BTM_BLE_APPEARANCE_GENERIC_CLOCK 0x0100

/* Category[15:6] 0x005 */
#define BTM_BLE_APPEARANCE_GENERIC_DISPLAY 0x0140

/* Category[15:6] 0x006 */
#define BTM_BLE_APPEARANCE_GENERIC_REMOTE 0x0180

/* Category[15:6] 0x007 */
#define BTM_BLE_APPEARANCE_GENERIC_EYEGLASSES 0x01C0

/* Category[15:6] 0x008 */
#define BTM_BLE_APPEARANCE_GENERIC_TAG 0x0200

/* Category[15:6] 0x009 */
#define BTM_BLE_APPEARANCE_GENERIC_KEYRING 0x0240

/* Category[15:6] 0x00A */
#define BTM_BLE_APPEARANCE_GENERIC_MEDIA_PLAYER 0x0280

/* Category[15:6] 0x00B */
#define BTM_BLE_APPEARANCE_GENERIC_BARCODE_SCANNER 0x02C0

/* Category[15:6] 0x00C */
#define BTM_BLE_APPEARANCE_GENERIC_THERMOMETER 0x0300
#define BTM_BLE_APPEARANCE_THERMOMETER_EAR 0x0301

/* Category[15:6] 0x00D */
#define BTM_BLE_APPEARANCE_GENERIC_HEART_RATE 0x0340
#define BTM_BLE_APPEARANCE_HEART_RATE_BELT 0x0341

/* Category[15:6] 0x00E */
#define BTM_BLE_APPEARANCE_GENERIC_BLOOD_PRESSURE 0x0380
#define BTM_BLE_APPEARANCE_BLOOD_PRESSURE_ARM 0x0381
#define BTM_BLE_APPEARANCE_BLOOD_PRESSURE_WRIST 0x0382

/* Category[15:6] 0x00F */
#define BTM_BLE_APPEARANCE_GENERIC_HID 0x03C0
#define BTM_BLE_APPEARANCE_HID_KEYBOARD 0x03C1
#define BTM_BLE_APPEARANCE_HID_MOUSE 0x03C2
#define BTM_BLE_APPEARANCE_HID_JOYSTICK 0x03C3
#define BTM_BLE_APPEARANCE_HID_GAMEPAD 0x03C4
#define BTM_BLE_APPEARANCE_HID_DIGITIZER_TABLET 0x03C5
#define BTM_BLE_APPEARANCE_HID_CARD_READER 0x03C6
#define BTM_BLE_APPEARANCE_HID_DIGITAL_PEN 0x03C7
#define BTM_BLE_APPEARANCE_HID_BARCODE_SCANNER 0x03C8
#define BTM_BLE_APPEARANCE_HID_TOUCHPAD 0x03C9
#define BTM_BLE_APPEARANCE_HID_PRESENTATION_REMOTE 0x03CA

/* Category[15:6] 0x010 */
#define BTM_BLE_APPEARANCE_GENERIC_GLUCOSE 0x0400

/* Category[15:6] 0x011 */
#define BTM_BLE_APPEARANCE_GENERIC_WALKING 0x0440
#define BTM_BLE_APPEARANCE_WALKING_IN_SHOE 0x0441
#define BTM_BLE_APPEARANCE_WALKING_ON_SHOE 0x0442
#define BTM_BLE_APPEARANCE_WALKING_ON_HIP 0x0443

/* Category[15:6] 0x012 */
#define BTM_BLE_APPEARANCE_GENERIC_CYCLING 0x0480
#define BTM_BLE_APPEARANCE_CYCLING_COMPUTER 0x0481
#define BTM_BLE_APPEARANCE_CYCLING_SPEED 0x0482
#define BTM_BLE_APPEARANCE_CYCLING_CADENCE 0x0483
#define BTM_BLE_APPEARANCE_CYCLING_POWER 0x0484
#define BTM_BLE_APPEARANCE_CYCLING_SPEED_CADENCE 0x0485

/* Category[15:6] 0x013 */
#define BTM_BLE_APPEARANCE_GENERIC_CONTROL_DEVICE 0x04C0
#define BTM_BLE_APPEARANCE_SWITCH 0x04C1
#define BTM_BLE_APPEARANCE_MULTI_SWITCH 0x04C2
#define BTM_BLE_APPEARANCE_SWITCH_BUTTON 0x04C3
#define BTM_BLE_APPEARANCE_SWITCH_SLIDER 0x04C4
#define BTM_BLE_APPEARANCE_ROTARY_SWITCH 0x04C5
#define BTM_BLE_APPEARANCE_TOUCH_PANEL 0x04C6
#define BTM_BLE_APPEARANCE_SINGLE_SWITCH 0x04C7
#define BTM_BLE_APPEARANCE_DOUBLE_SWITCH 0x04C8
#define BTM_BLE_APPEARANCE_TRIPLE_SWITCH 0x04C9
#define BTM_BLE_APPEARANCE_BATTERY_SWITCH 0x04CA
#define BTM_BLE_APPEARANCE_ENERGY_HARVESTING_SWITCH 0x04CB
#define BTM_BLE_APPEARANCE_SWITCH_PUSH_BUTTON 0x04CC
#define BTM_BLE_APPEARANCE_SWITCH_DIAL 0x04CD

/* Category[15:6] 0x014 */
#define BTM_BLE_APPEARANCE_GENERIC_NETWORK_DEVICE 0x0500
#define BTM_BLE_APPEARANCE_NETWORK_DEVICE_ACCESS_POINT 0x0501
#define BTM_BLE_APPEARANCE_NETWORK_DEVICE_MESH_DEVICE 0x0502
#define BTM_BLE_APPEARANCE_NETWORK_DEVICE_MESH_NETWORK_PROXY 0x0503

/* Category[15:6] 0x015 */
#define BTM_BLE_APPEARANCE_GENERIC_SENSOR 0x0540
#define BTM_BLE_APPEARANCE_MOTION_SENSOR 0x0541
#define BTM_BLE_APPEARANCE_AIR_QUALITY_SENSOR 0x0542
#define BTM_BLE_APPEARANCE_TEMPERATURE_SENSOR 0x0543
#define BTM_BLE_APPEARANCE_HUMIDITY_SENSOR 0x0544
#define BTM_BLE_APPEARANCE_LEAK_SENSOR 0x05
#define BTM_BLE_APPEARANCE_SMOKE_SENSOR 0x0546
#define BTM_BLE_APPEARANCE_OCCUPANCY_SENSOR 0x0547
#define BTM_BLE_APPEARANCE_CONTACT_SENSOR 0x0548
#define BTM_BLE_APPEARANCE_CARBON_MONOXIDE_SENSOR 0x0549
#define BTM_BLE_APPEARANCE_CARBON_DIOXIDE_SENSOR 0x054A
#define BTM_BLE_APPEARANCE_AMBIENT_LIGHT_SENSOR 0x054B
#define BTM_BLE_APPEARANCE_ENERGY_SENSOR 0x054C
#define BTM_BLE_APPEARANCE_COLOR_LIGHT_SENSOR 0x054D
#define BTM_BLE_APPEARANCE_RAIN_SENSOR 0x054E
#define BTM_BLE_APPEARANCE_FIRE_SENSOR 0x054F
#define BTM_BLE_APPEARANCE_WIND_SENSOR 0x0550
#define BTM_BLE_APPEARANCE_PROXIMITY_SENSOR 0x0551
#define BTM_BLE_APPEARANCE_MULTI_SENSOR 0x0552
#define BTM_BLE_APPEARANCE_FLUSH_MOUNTED_SENSOR 0x0553
#define BTM_BLE_APPEARANCE_CEILING_MOUNTED_SENSOR 0x0554
#define BTM_BLE_APPEARANCE_WALL_MOUNTED_SENSOR 0x0555
#define BTM_BLE_APPEARANCE_MULTISENSOR 0x0556
#define BTM_BLE_APPEARANCE_SENSOR_ENERGY_METER 0x0557
#define BTM_BLE_APPEARANCE_SENSOR_FLAME_DETECTOR 0x0558
#define BTM_BLE_APPEARANCE_VEHICLE_TIRE_PRESSURE_SENSOR 0x0559

/* Category[15:6] 0x016 */
#define BTM_BLE_APPEARANCE_GENERIC_LIGHT_FIXTURE 0x0580
#define BTM_BLE_APPEARANCE_WALL_LIGHT 0x0581
#define BTM_BLE_APPEARANCE_CEILING_LIGHT 0x0582
#define BTM_BLE_APPEARANCE_FLOOR_LIGHT 0x0583
#define BTM_BLE_APPEARANCE_CABINET_LIGHT 0x0584
#define BTM_BLE_APPEARANCE_DESK_LIGHT 0x0585
#define BTM_BLE_APPEARANCE_TROFFER_LIGHT 0x0586
#define BTM_BLE_APPEARANCE_PENDANT_LIGHT 0x0587
#define BTM_BLE_APPEARANCE_IN_GROUND_LIGHT 0x0588
#define BTM_BLE_APPEARANCE_FLOOD_LIGHT 0x0589
#define BTM_BLE_APPEARANCE_UNDERWATER_LIGHT 0x058A
#define BTM_BLE_APPEARANCE_BOLLARD_WITH_LIGHT 0x058B
#define BTM_BLE_APPEARANCE_PATHWAY_LIGHT 0x058C
#define BTM_BLE_APPEARANCE_GARDEN_LIGHT 0x058D
#define BTM_BLE_APPEARANCE_POLE_TOP_LIGHT 0x058E
#define BTM_BLE_APPEARANCE_SPOTLIGHT 0x058F
#define BTM_BLE_APPEARANCE_LINEAR_LIGHT 0x0590
#define BTM_BLE_APPEARANCE_STREET_LIGHT 0x0591
#define BTM_BLE_APPEARANCE_SHELVES_LIGHT 0x0592
#define BTM_BLE_APPEARANCE_BAY_LIGHT 0x0593
#define BTM_BLE_APPEARANCE_EMERGENCY_EXIT_LIGHT 0x0594
#define BTM_BLE_APPEARANCE_LIGHT_CONTROLLER 0x0595
#define BTM_BLE_APPEARANCE_LIGHT_DRIVER 0x0596
#define BTM_BLE_APPEARANCE_BULB 0x0597
#define BTM_BLE_APPEARANCE_LOW_BAY_LIGHT 0x0598
#define BTM_BLE_APPEARANCE_HIGH_BAY_LIGHT 0x0599

/* Category[15:6] 0x017 */
#define BTM_BLE_APPEARANCE_GENERIC_FAN 0x05C0
#define BTM_BLE_APPEARANCE_CEILING_FAN 0x05C1
#define BTM_BLE_APPEARANCE_AXIAL_FAN 0x05C2
#define BTM_BLE_APPEARANCE_EXHAUST_FAN 0x05C3
#define BTM_BLE_APPEARANCE_PEDESTAL_FAN 0x05C4
#define BTM_BLE_APPEARANCE_DESK_FAN 0x05C5
#define BTM_BLE_APPEARANCE_WALL_FAN 0x05C6

/* Category[15:6] 0x018 */
#define BTM_BLE_APPEARANCE_GENERIC_HVAC 0x0600
#define BTM_BLE_APPEARANCE_HVAC_THERMOSTAT 0x0601
#define BTM_BLE_APPEARANCE_HVAC_HUMIDIFIER 0x0602
#define BTM_BLE_APPEARANCE_HVAC_DEHUMIDIFIER 0x0603
#define BTM_BLE_APPEARANCE_HVAC_HEATER 0x0604
#define BTM_BLE_APPEARANCE_HVAC_RADIATOR 0x0605
#define BTM_BLE_APPEARANCE_HVAC_BOILER 0x0606
#define BTM_BLE_APPEARANCE_HVAC_HEAT_PUMP 0x0607
#define BTM_BLE_APPEARANCE_HVAC_INFRARED_HEATER 0x0608
#define BTM_BLE_APPEARANCE_HVAC_RADIANT_PANEL_HEATER 0x0609
#define BTM_BLE_APPEARANCE_HVAC_FAN_HEATER 0x060A
#define BTM_BLE_APPEARANCE_HVAC_AIR_CURTAIN 0x060B

/* Category[15:6] 0x019 */
#define BTM_BLE_APPEARANCE_GENERIC_AIR_CONDITIONING 0x0640

/* Category[15:6] 0x01A */
#define BTM_BLE_APPEARANCE_GENERIC_HUMIDIFIER 0x0680

/* Category[15:6] 0x01B */
#define BTM_BLE_APPEARANCE_GENERIC_HEATING 0x06C0
#define BTM_BLE_APPEARANCE_HEATING_RADIATOR 0x06C1
#define BTM_BLE_APPEARANCE_HEATING_BOILER 0x06C2
#define BTM_BLE_APPEARANCE_HEATING_HEAT_PUMP 0x06C3
#define BTM_BLE_APPEARANCE_HEATING_INFRARED_HEATER 0x06C4
#define BTM_BLE_APPEARANCE_HEATING_RADIANT_PANEL_HEATER 0x06C5
#define BTM_BLE_APPEARANCE_HEATING_FAN_HEATER 0x06C6
#define BTM_BLE_APPEARANCE_HEATING_AIR_CURTAIN 0x06C7

/* Category[15:6] 0x01C */
#define BTM_BLE_APPEARANCE_GENERIC_ACCESS_CONTROL 0x0700
#define BTM_BLE_APPEARANCE_ACCESS_DOOR 0x0701
#define BTM_BLE_APPEARANCE_ACCESS_CONTROL_GARAGE_DOOR 0x0702
#define BTM_BLE_APPEARANCE_ACCESS_CONTROL_EMERGENCY_EXIT_DOOR 0x0703
#define BTM_BLE_APPEARANCE_ACCESS_CONTROL_ACCESS_LOCK 0x0704
#define BTM_BLE_APPEARANCE_ACCESS_CONTROL_ELEVATOR 0x0705
#define BTM_BLE_APPEARANCE_ACCESS_CONTROL_WINDOW 0x0706
#define BTM_BLE_APPEARANCE_ACCESS_CONTROL_ENTRANCE_GATE 0x0707
#define BTM_BLE_APPEARANCE_ACCESS_CONTROL_DOOR_LOCK 0x0708
#define BTM_BLE_APPEARANCE_ACCESS_CONTROL_LOCKER 0x0709

/* Category[15:6] 0x01D */
#define BTM_BLE_APPEARANCE_GENERIC_MOTORIZED_DEVICE 0x0740
#define BTM_BLE_APPEARANCE_MOTORIZED_GATE 0x0741
#define BTM_BLE_APPEARANCE_MOTORIZED_AWNING 0x0742
#define BTM_BLE_APPEARANCE_MOTORIZED_BLINDS_OR_SHADES 0x0743
#define BTM_BLE_APPEARANCE_MOTORIZED_CURTAINS 0x0744
#define BTM_BLE_APPEARANCE_MOTORIZED_SCREEN 0x0745

/* Category[15:6] 0x01E */
#define BTM_BLE_APPEARANCE_GENERIC_POWER_DEVICE 0x0780
#define BTM_BLE_APPEARANCE_POWER_OUTLET 0x0781
#define BTM_BLE_APPEARANCE_POWER_STRIP 0x0782
#define BTM_BLE_APPEARANCE_POWER_PLUG 0x0783
#define BTM_BLE_APPEARANCE_POWER_SUPPLY 0x0784

/* Category[15:6] 0x01F */
#define BTM_BLE_APPEARANCE_GENERIC_LIGHT_SOURCE 0x07C0
#define BTM_BLE_APPEARANCE_LIGHT_SOURCE_INCANDESCENT_LIGHT_BULB 0x07C1
#define BTM_BLE_APPEARANCE_LIGHT_SOURCE_LED_LAMP 0x07C2
#define BTM_BLE_APPEARANCE_LIGHT_SOURCE_HID_LAMP 0x07C3
#define BTM_BLE_APPEARANCE_LIGHT_SOURCE_FLUORESCENT_LAMP 0x07C4
#define BTM_BLE_APPEARANCE_LIGHT_SOURCE_LED_ARRAY 0x07C5
#define BTM_BLE_APPEARANCE_LIGHT_SOURCE_MULTI_COLOR_LED_ARRAY 0x07C6
#define BTM_BLE_APPEARANCE_LIGHT_SOURCE_LOW_VOLTAGE_HALOGEN 0x07C7
#define BTM_BLE_APPEARANCE_LIGHT_SOURCE_ORGANIC_LIGHT_EMITTING_DIODE_OLED 0x07C8

/* Category[15:6] 0x020 */
#define BTM_BLE_APPEARANCE_GENERIC_WINDOW_COVERING 0x0800
#define BTM_BLE_APPEARANCE_WINDOW_COVERING_WINDOW_SHADES 0x0801
#define BTM_BLE_APPEARANCE_WINDOW_COVERING_WINDOW_BLINDS 0x0802
#define BTM_BLE_APPEARANCE_WINDOW_COVERING_WINDOW_AWNING 0x0803
#define BTM_BLE_APPEARANCE_WINDOW_COVERING_WINDOW_CURTAIN 0x0804
#define BTM_BLE_APPEARANCE_WINDOW_COVERING_EXTERIOR_SHUTTER 0x0805
#define BTM_BLE_APPEARANCE_WINDOW_COVERING_EXTERIOR_SCREEN 0x0806

/* Category[15:6] 0x021 */
#define BTM_BLE_APPEARANCE_GENERIC_AUDIO_SINK 0x0840
#define BTM_BLE_APPEARANCE_AUDIO_SINK_STANDALONE_SPEAKER 0x0841
#define BTM_BLE_APPEARANCE_AUDIO_SINK_SOUNDBAR 0x0842
#define BTM_BLE_APPEARANCE_AUDIO_SINK_BOOKSHELF_SPEAKER 0x0843
#define BTM_BLE_APPEARANCE_AUDIO_SINK_STANDMOUNTED_SPEAKER 0x0844
#define BTM_BLE_APPEARANCE_AUDIO_SINK_SPEAKERPHONE 0x0845

/* Category[15:6] 0x022 */
#define BTM_BLE_APPEARANCE_GENERIC_AUDIO_SOURCE 0x0880
#define BTM_BLE_APPEARANCE_AUDIO_SOURCE_MICROPHONE 0x0881
#define BTM_BLE_APPEARANCE_AUDIO_SOURCE_ALARM 0x0882
#define BTM_BLE_APPEARANCE_AUDIO_SOURCE_BELL 0x0883
#define BTM_BLE_APPEARANCE_AUDIO_SOURCE_HORN 0x0884
#define BTM_BLE_APPEARANCE_AUDIO_SOURCE_BROADCASTING_DEVICE 0x0885
#define BTM_BLE_APPEARANCE_AUDIO_SOURCE_SERVICE_DESK 0x0886
#define BTM_BLE_APPEARANCE_AUDIO_SOURCE_KIOSK 0x0887
#define BTM_BLE_APPEARANCE_AUDIO_SOURCE_BROADCASTING_ROOM 0x0888
#define BTM_BLE_APPEARANCE_AUDIO_SOURCE_AUDITORIUM 0x0889

/* Category[15:6] 0x023 */
#define BTM_BLE_APPEARANCE_GENERIC_MOTORIZED_VEHICLE 0x08C0
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_CAR 0x08C1
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_LARGE_GOODS 0x08C2
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_2_WHEELED 0x08C3
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_MOTORBIKE 0x08C4
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_SCOOTER 0x08C5
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_MOPED 0x08C6
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_3_WHEELED 0x08C7
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_LIGHT_VEHICLE 0x08C8
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_QUAD_BIKE 0x08C9
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_MINIBUS 0x08CA
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_BUS 0x08CB
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_TROLLEY 0x08CC
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_AGRICULTURAL_VEHICLE 0x08CD
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_CAMPER_CARAVAN 0x08CE
#define BTM_BLE_APPEARANCE_MOTORIZED_VEHICLE_RECREATIONAL_VEHICLE_MOTOR_HOME 0x08CF

/* Category[15:6] 0x024 */
#define BTM_BLE_APPEARANCE_GENERIC_DOMESTIC_APPLIANCE 0x0900
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_REFRIGERATOR 0x0901
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_FREEZER 0x0902
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_OVEN 0x0903
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_MICROWAVE 0x0904
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_TOASTER 0x0905
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_WASHING_MACHINE 0x0906
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_DRYER 0x0907
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_COFFEE_MAKER 0x0908
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_CLOTHES_IRON 0x0909
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_CURLING_IRON 0x090A
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_HAIR_DRYER 0x090B
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_VACUUM_CLEANER 0x090C
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_ROBOTIC_VACUUM_CLEANER 0x090D
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_RICE_COOKER 0x090E
#define BTM_BLE_APPEARANCE_DOMESTIC_APPLIANCE_CLOTHES_STEAMER 0x090F

/* Category[15:6] 0x025 */
#define BTM_BLE_APPEARANCE_GENERIC_WEARABLE_AUDIO_DEVICE 0x0940
#define BTM_BLE_APPEARANCE_WEARABLE_AUDIO_DEVICE_EARBUD 0x0941
#define BTM_BLE_APPEARANCE_WEARABLE_AUDIO_DEVICE_HEADSET 0x0942
#define BTM_BLE_APPEARANCE_WEARABLE_AUDIO_DEVICE_HEADPHONES 0x0943
#define BTM_BLE_APPEARANCE_WEARABLE_AUDIO_DEVICE_NECK_BAND 0x0944

/* Category[15:6] 0x026 */
#define BTM_BLE_APPEARANCE_GENERIC_AIRCRAFT 0x0980
#define BTM_BLE_APPEARANCE_AIRCRAFT_LIGHT 0x0981
#define BTM_BLE_APPEARANCE_AIRCRAFT_MICROLIGHT 0x0982
#define BTM_BLE_APPEARANCE_AIRCRAFT_PARAGLIDER 0x0983
#define BTM_BLE_APPEARANCE_AIRCRAFT_LARGE_PASSENGER 0x0984

/* Category[15:6] 0x027 */
#define BTM_BLE_APPEARANCE_GENERIC_AV_EQUIPMENT 0x09C0
#define BTM_BLE_APPEARANCE_AV_EQUIPMENT_AMPLIFIER 0x09C1
#define BTM_BLE_APPEARANCE_AV_EQUIPMENT_RECEIVER 0x09C2
#define BTM_BLE_APPEARANCE_AV_EQUIPMENT_RADIO 0x09C3
#define BTM_BLE_APPEARANCE_AV_EQUIPMENT_TUNER 0x09C4
#define BTM_BLE_APPEARANCE_AV_EQUIPMENT_TURNTABLE 0x09C5
#define BTM_BLE_APPEARANCE_AV_EQUIPMENT_CD_PLAYER 0x09C6
#define BTM_BLE_APPEARANCE_AV_EQUIPMENT_DVD_PLAYER 0x09C7
#define BTM_BLE_APPEARANCE_AV_EQUIPMENT_BLU_RAY_PLAYER 0x09C8
#define BTM_BLE_APPEARANCE_AV_EQUIPMENT_OPTICAL_DISC_PLAYER 0x09C9
#define BTM_BLE_APPEARANCE_AV_EQUIPMENT_SET_TOP_BOX 0x09CA

/* Category[15:6] 0x028 */
#define BTM_BLE_APPEARANCE_GENERIC_DISPLAY_EQUIPMENT 0x0A00
#define BTM_BLE_APPEARANCE_DISPLAY_EQUIPMENT_TELEVISION 0x0A01
#define BTM_BLE_APPEARANCE_DISPLAY_EQUIPMENT_MONITOR 0x0A02
#define BTM_BLE_APPEARANCE_DISPLAY_EQUIPMENT_PROJECTOR 0x0A03

/* Category[15:6] 0x029 */
#define BTM_BLE_APPEARANCE_GENERIC_HEARING_AID 0x0A40
#define BTM_BLE_APPEARANCE_HEARING_AID_IN_EAR 0x0A41
#define BTM_BLE_APPEARANCE_HEARING_AID_BEHIND_EAR 0x0A42
#define BTM_BLE_APPEARANCE_HEARING_AID_COCHLLEAR_IMPLANT 0x0A43

/* Category[15:6] 0x02A */
#define BTM_BLE_APPEARANCE_GENERIC_GAMING 0x0A80
#define BTM_BLE_APPEARANCE_GAMING_HOME_VIDEO_GAME_CONSOLE 0x0A81
#define BTM_BLE_APPEARANCE_GAMING_PORTABLE_HANDHELD_CONSOLE 0x0A82

/* Category[15:6] 0x02B */
#define BTM_BLE_APPEARANCE_GENERIC_SIGNAGE 0x0AC0
#define BTM_BLE_APPEARANCE_SIGNAGE_DIGITAL 0x0AC1
#define BTM_BLE_APPEARANCE_SIGNAGE_ELECTRONIC_LABEL 0x0AC2

/* Category[15:6] 0x031 */
#define BTM_BLE_APPEARANCE_GENERIC_PULSE_OXIMETER 0x0C40
#define BTM_BLE_APPEARANCE_PULSE_OXIMETER_FINGERTIP 0x0C41
#define BTM_BLE_APPEARANCE_PULSE_OXIMETER_WRIST 0x0C42

/* Category[15:6] 0x032 */
#define BTM_BLE_APPEARANCE_GENERIC_WEIGHT 0x0C80

/* Category[15:6] 0x033 */
#define BTM_BLE_APPEARANCE_GENERIC_PERSONAL_MOBILITY_DEVICE 0x0CC0
#define BTM_BLE_APPEARANCE_PERSONAL_MOBILITY_DEVICE_POWERED_WHEELCHAIR 0x0CC1
#define BTM_BLE_APPEARANCE_PERSONAL_MOBILITY_DEVICE_MOBILITY_SCOOTER 0x0CC2

/* Category[15:6] 0x034 */
#define BTM_BLE_APPEARANCE_GENERIC_CONTINUOUS_GLUCOSE_MONITOR 0x0D00

/* Category[15:6] 0x035 */
#define BTM_BLE_APPEARANCE_GENERIC_INSULIN_PUMP 0x0D40
#define BTM_BLE_APPEARANCE_INSULIN_PUMP_DURABLE 0x0D41
#define BTM_BLE_APPEARANCE_INSULIN_PUMP_PATCH 0x0D44
#define BTM_BLE_APPEARANCE_INSULIN_PUMP_PEN 0x0D48

/* Category[15:6] 0x036 */
#define BTM_BLE_APPEARANCE_GENERIC_MEDICATION_DELIVERY 0x0D80

/* Category[15:6] 0x037 */
#define BTM_BLE_APPEARANCE_GENERIC_SPIROMETER 0x0DC0
#define BTM_BLE_APPEARANCE_SPIROMETER_HANDHELD 0x0DC1

/* Category[15:6] 0x051 */
#define BTM_BLE_APPEARANCE_GENERIC_OUTDOOR_SPORTS 0x1440
#define BTM_BLE_APPEARANCE_OUTDOOR_SPORTS_LOCATION 0x1441
#define BTM_BLE_APPEARANCE_OUTDOOR_SPORTS_LOCATION_AND_NAV 0x1442
#define BTM_BLE_APPEARANCE_OUTDOOR_SPORTS_LOCATION_POD 0x1443
#define BTM_BLE_APPEARANCE_OUTDOOR_SPORTS_LOCATION_POD_AND_NAV 0x1444

/* Category[15:6] 0x052 */
#define BTM_BLE_APPEARANCE_GENERIC_INDUSTRIAL_MEASUREMENT_DEVICE 0x1480
#define BTM_BLE_APPEARANCE_INDUSTRIAL_MEASUREMENT_DEVICE_TORQUE_TESTING 0x1481
#define BTM_BLE_APPEARANCE_INDUSTRIAL_MEASUREMENT_DEVICE_CALIPER 0x1482
#define BTM_BLE_APPEARANCE_INDUSTRIAL_MEASUREMENT_DEVICE_DIAL_INDICATOR 0x1483
#define BTM_BLE_APPEARANCE_INDUSTRIAL_MEASUREMENT_DEVICE_MICROMETER 0x1484
#define BTM_BLE_APPEARANCE_INDUSTRIAL_MEASUREMENT_DEVICE_HEIGHT_GAUGE 0x1485
#define BTM_BLE_APPEARANCE_INDUSTRIAL_MEASUREMENT_DEVICE_FORCE_GAUGE 0x1486

/* Category[15:6] 0x053 */
#define BTM_BLE_APPEARANCE_GENERIC_INDUSTRIAL_TOOLS 0x14C0
#define BTM_BLE_APPEARANCE_INDUSTRIAL_TOOLS_MACHINE_TOOL_HOLDER 0x14C1
#define BTM_BLE_APPEARANCE_INDUSTRIAL_TOOLS_GENERIC_CLAMPING_DEVICE 0x14C2
#define BTM_BLE_APPEARANCE_INDUSTRIAL_TOOLS_CLAMPING_JAWS_JAWS_CHUCK 0x14C3
#define BTM_BLE_APPEARANCE_INDUSTRIAL_TOOLS_CLAMPING_COLLET_CHUCK 0x14C4
#define BTM_BLE_APPEARANCE_INDUSTRIAL_TOOLS_CLAMPING_MANDREL 0x14C5
#define BTM_BLE_APPEARANCE_INDUSTRIAL_TOOLS_VISE 0x14C6
#define BTM_BLE_APPEARANCE_INDUSTRIAL_TOOLS_ZERO_POINT_CLAMPING_SYSTEM 0x14C7
#define BTM_BLE_APPEARANCE_INDUSTRIAL_TOOLS_TORQUE_WRENCH 0x14C8
#define BTM_BLE_APPEARANCE_INDUSTRIAL_TOOLS_TORQUE_SCREWDRIVER 0x14C9

/* Structure returned with Rand/Encrypt complete callback */
typedef struct {
  uint8_t status;
  uint8_t param_len;
  uint16_t opcode;
  uint8_t param_buf[OCTET16_LEN];
} tBTM_RAND_ENC;

/* General callback function for notifying an application that a synchronous
 * BTM function is complete. The pointer contains the address of any returned
 * data.
 */
typedef void(tBTM_RAND_ENC_CB)(tBTM_RAND_ENC* p1);

/* ADV data flag bit definition used for BTM_BLE_AD_TYPE_FLAG */
#define BTM_BLE_LIMIT_DISC_FLAG (0x01 << 0)
#define BTM_BLE_GEN_DISC_FLAG (0x01 << 1)
#define BTM_BLE_BREDR_NOT_SPT (0x01 << 2)
/* 4.1 spec adv flag for simultaneous BR/EDR+LE connection support */
#define BTM_BLE_DMT_CONTROLLER_SPT (0x01 << 3)
#define BTM_BLE_DMT_HOST_SPT (0x01 << 4)

// TODO(jpawlowski): this should be removed with code that depend on it.
#define BTM_BLE_AD_BIT_FLAGS (0x00000001 << 1)

#define BTM_BLE_AD_TYPE_FLAG HCI_EIR_FLAGS_TYPE /* 0x01 */
#define BTM_BLE_AD_TYPE_16SRV_CMPL                                          \
  HCI_EIR_COMPLETE_16BITS_UUID_TYPE                                 /* 0x03 \
                                                                     */
#define BTM_BLE_AD_TYPE_SERVICE_DATA_TYPE HCI_EIR_SERVICE_DATA_TYPE /* 0x16 */
#define BTM_BLE_AD_TYPE_APPEARANCE 0x19
#define BTM_BLE_AD_TYPE_RSI HCI_EIR_RSI_TYPE /* 0x2E */
#define BTM_BLE_AD_TYPE_BROADCAST_NAME 0x30

/*  Min/max Preferred  number of payload octets that the local Controller
    should include in a single Link Layer Data Channel PDU. */
#define BTM_BLE_DATA_SIZE_MAX 0x00fb
#define BTM_BLE_DATA_SIZE_MIN 0x001b

/*  Preferred maximum number of microseconds that the local Controller
    should use to transmit a single Link Layer Data Channel PDU. */
#define BTM_BLE_DATA_TX_TIME_MAX_LEGACY 0x0848
#define BTM_BLE_DATA_TX_TIME_MAX 0x4290

/* adv tx power in dBm */
typedef struct {
  uint8_t adv_inst_max; /* max adv instance supported in controller */
  uint8_t rpa_offloading;
  uint16_t tot_scan_results_strg;
  uint8_t max_irk_list_sz;
  uint8_t filter_support;
  uint8_t max_filter;
  uint8_t energy_support;
  bool values_read;
  uint16_t version_supported;
  uint16_t total_trackable_advertisers;
  uint8_t extended_scan_support;
  uint8_t debug_logging_supported;
  uint8_t le_address_generation_offloading_support;
  uint32_t a2dp_source_offload_capability_mask;
  uint8_t quality_report_support;
  uint32_t dynamic_audio_buffer_support;
  uint16_t adv_filter_extended_features_mask;
  uint8_t a2dp_offload_v2_support;
} tBTM_BLE_VSC_CB;

/* Stored the default/maximum/minimum buffer time for dynamic audio buffer.
 * For A2DP offload usage, the unit is millisecond.
 * For A2DP legacy usage, the unit is buffer queue size*/
typedef struct {
  uint16_t default_buffer_time;
  uint16_t maximum_buffer_time;
  uint16_t minimum_buffer_time;
} tBTM_BT_DYNAMIC_AUDIO_BUFFER_CB;

typedef void(tBTM_BLE_ADV_DATA_CMPL_CBACK)(tBTM_STATUS status);

#ifndef BTM_BLE_MULTI_ADV_MAX
#define BTM_BLE_MULTI_ADV_MAX                           \
  16 /* controller returned adv_inst_max should be less \
        than this number */
#endif

typedef uint16_t tCONN_ID;
typedef uint8_t tGATT_IF;
typedef uint8_t tTCB_IDX;

inline constexpr tGATT_IF GATT_IF_INVALID = static_cast<tGATT_IF>(0);
// 0xF1 ~ 0xFF are reserved for special use cases.
inline constexpr tGATT_IF GATT_IF_MAX = static_cast<tGATT_IF>(0xf8);
/* connection manager doesn't generate its own IDs. Instead, all GATT clients
 * use their gatt_if to identify against connection manager. When stack tries to
 * create l2cap connection, it will use this fixed ID. */
inline constexpr tGATT_IF CONN_MGR_ID_L2CAP = static_cast<tGATT_IF>(0xf9);

typedef enum : uint8_t {
  BTM_BLE_DIRECT_CONNECTION = 0x00,
  BTM_BLE_BKG_CONNECT_ALLOW_LIST = 0x01,
  BTM_BLE_BKG_CONNECT_TARGETED_ANNOUNCEMENTS = 0x02,
} tBTM_BLE_CONN_TYPE;

typedef void(tBTM_BLE_SCAN_THRESHOLD_CBACK)(tBTM_BLE_REF_VALUE ref_value);
using tBTM_BLE_SCAN_REP_CBACK =
        base::Callback<void(tBTM_STATUS /* status */, uint8_t /* report_format */,
                            uint8_t /* num_reports */, std::vector<uint8_t>)>;

#ifndef BTM_BLE_BATCH_SCAN_MAX
#define BTM_BLE_BATCH_SCAN_MAX 5
#endif

#ifndef BTM_BLE_BATCH_REP_MAIN_Q_SIZE
#define BTM_BLE_BATCH_REP_MAIN_Q_SIZE 2
#endif

typedef enum {
  BTM_BLE_SCAN_INVALID_STATE = 0,
  BTM_BLE_SCAN_ENABLE_CALLED = 1,
  BTM_BLE_SCAN_ENABLED_STATE = 2,
  BTM_BLE_SCAN_DISABLE_CALLED = 3,
  BTM_BLE_SCAN_DISABLED_STATE = 4
} tBTM_BLE_BATCH_SCAN_STATE;

enum { BTM_BLE_DISCARD_OLD_ITEMS, BTM_BLE_DISCARD_LOWER_RSSI_ITEMS };
typedef uint8_t tBTM_BLE_DISCARD_RULE;

typedef struct {
  tBTM_BLE_BATCH_SCAN_STATE cur_state;
  tBTM_BLE_BATCH_SCAN_MODE scan_mode;
  uint32_t scan_interval;
  uint32_t scan_window;
  tBLE_ADDR_TYPE addr_type;
  tBTM_BLE_DISCARD_RULE discard_rule;
  tBTM_BLE_SCAN_THRESHOLD_CBACK* p_thres_cback;
  tBTM_BLE_REF_VALUE ref_value;
} tBTM_BLE_BATCH_SCAN_CB;

/* filter selection bit index  */
#define BTM_BLE_PF_ADDR_FILTER 0
#define BTM_BLE_PF_SRVC_DATA 1
#define BTM_BLE_PF_SRVC_UUID 2
#define BTM_BLE_PF_SRVC_SOL_UUID 3
#define BTM_BLE_PF_LOCAL_NAME 4
#define BTM_BLE_PF_MANU_DATA 5
#define BTM_BLE_PF_SRVC_DATA_PATTERN 6
/* when passed in payload filter type all, only clear action is applicable */
#define BTM_BLE_PF_TYPE_ALL 7
#define BTM_BLE_PF_TYPE_MAX 8

/* max number of filter spot for different filter type */
#ifndef BTM_BLE_MAX_UUID_FILTER
#define BTM_BLE_MAX_UUID_FILTER 8
#endif
#ifndef BTM_BLE_MAX_ADDR_FILTER
#define BTM_BLE_MAX_ADDR_FILTER 8
#endif
#ifndef BTM_BLE_PF_STR_COND_MAX
#define BTM_BLE_PF_STR_COND_MAX 4 /* apply to manu data , or local name */
#endif
#ifndef BTM_BLE_PF_STR_LEN_MAX
#define BTM_BLE_PF_STR_LEN_MAX 29 /* match for first 29 bytes */
#endif

typedef uint8_t tBTM_BLE_PF_COND_TYPE;

#define BTM_BLE_PF_LOGIC_OR 0
#define BTM_BLE_PF_LOGIC_AND 1
typedef uint8_t tBTM_BLE_PF_LOGIC_TYPE;

#define BTM_BLE_PF_ENABLE 1
#define BTM_BLE_PF_CONFIG 2

typedef uint8_t tBTM_BLE_PF_FILT_INDEX;

enum { BTM_BLE_SCAN_COND_ADD, BTM_BLE_SCAN_COND_DELETE, BTM_BLE_SCAN_COND_CLEAR = 2 };
typedef uint8_t tBTM_BLE_SCAN_COND_OP;

/* BLE adv payload filtering config complete callback */
using tBTM_BLE_PF_CFG_CBACK =
        base::Callback<void(uint8_t /* avbl_space */, tBTM_BLE_SCAN_COND_OP /* action */,
                            tBTM_STATUS /* btm_status */)>;

/* BLE adv payload filtering status setup complete callback */
using tBTM_BLE_PF_STATUS_CBACK =
        base::Callback<void(tBTM_BLE_SCAN_COND_OP /*action*/, tBTM_STATUS /* btm_status */)>;

/* BLE adv payload filtering param setup complete callback */
using tBTM_BLE_PF_PARAM_CB =
        base::Callback<void(uint8_t /* avbl_space */, tBTM_BLE_SCAN_COND_OP /* action */,
                            tBTM_STATUS /* btm_status */)>;

#ifndef BTM_CS_IRK_LIST_MAX
#define BTM_CS_IRK_LIST_MAX 0x20
#endif

typedef struct {
  bool in_use;
  RawAddress bd_addr;
  uint8_t pf_counter[BTM_BLE_PF_TYPE_MAX]; /* number of filter indexed by
                                              tBTM_BLE_PF_COND_TYPE */
} tBTM_BLE_PF_COUNT;

typedef struct {
  bool enable;
  uint8_t op_type;
  tBTM_BLE_PF_COUNT* p_addr_filter_count; /* per BDA filter array */
  tBLE_BD_ADDR cur_filter_target;
} tBTM_BLE_ADV_FILTER_CB;

/* Sub codes */
#define BTM_BLE_META_PF_ENABLE 0x00
#define BTM_BLE_META_PF_FEAT_SEL 0x01
#define BTM_BLE_META_PF_ADDR 0x02
#define BTM_BLE_META_PF_UUID 0x03
#define BTM_BLE_META_PF_SOL_UUID 0x04
#define BTM_BLE_META_PF_LOCAL_NAME 0x05
#define BTM_BLE_META_PF_MANU_DATA 0x06
#define BTM_BLE_META_PF_SRVC_DATA 0x07
#define BTM_BLE_META_PF_ALL 0x08

#define ADV_INFO_PRESENT 0x00
#define NO_ADV_INFO_PRESENT 0x01

typedef btgatt_track_adv_info_t tBTM_BLE_TRACK_ADV_DATA;

typedef void(tBTM_BLE_TRACK_ADV_CBACK)(tBTM_BLE_TRACK_ADV_DATA* p_track_adv_data);

typedef struct {
  tBTM_BLE_REF_VALUE ref_value;
  tBTM_BLE_TRACK_ADV_CBACK* p_track_cback;
} tBTM_BLE_ADV_TRACK_CB;

typedef uint32_t tBTM_BLE_TX_TIME_MS;
typedef uint32_t tBTM_BLE_RX_TIME_MS;
typedef uint32_t tBTM_BLE_IDLE_TIME_MS;
typedef uint32_t tBTM_BLE_ENERGY_USED;

typedef void(tBTM_BLE_ENERGY_INFO_CBACK)(tBTM_BLE_TX_TIME_MS tx_time, tBTM_BLE_RX_TIME_MS rx_time,
                                         tBTM_BLE_IDLE_TIME_MS idle_time,
                                         tBTM_BLE_ENERGY_USED energy_used, tHCI_STATUS status);

typedef struct {
  tBTM_BLE_ENERGY_INFO_CBACK* p_ener_cback;
} tBTM_BLE_ENERGY_INFO_CB;

typedef void(tBTM_BLE_CTRL_FEATURES_CBACK)(tHCI_STATUS status);

namespace std {
template <>
struct formatter<tBTM_BLE_CONN_TYPE> : enum_formatter<tBTM_BLE_CONN_TYPE> {};
}  // namespace std

#endif  // BTM_BLE_API_TYPES_H
