/*
 * Copyright 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import("//common-mk/generate-dbus-adaptors.gni")
import("//common-mk/generate-dbus-proxies.gni")


generate_dbus_adaptors("mmc_dbus_adaptors") {
  dbus_adaptors_out_dir = "include/mmc/dbus_adaptors"
  dbus_service_config = "dbus-service-config.json"
  sources = [
    "org.chromium.mmc.CodecManager.xml",
  ]
}

generate_dbus_proxies("mmc_dbus_proxies") {
  proxy_output_file = "include/mmc/dbus-proxies.h"
  sources = [
    "org.chromium.mmc.CodecManager.xml",
  ]
}
