# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pandora/asha.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from pandora import host_pb2 as pandora_dot_host__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12pandora/asha.proto\x12\x0cpandora.asha\x1a\x1bgoogle/protobuf/empty.proto\x1a\x12pandora/host.proto\"7\n\x0fRegisterRequest\x12\x12\n\ncapability\x18\x01 \x01(\r\x12\x10\n\x08hisyncid\x18\x02 \x03(\r\">\n\x13\x43\x61ptureAudioRequest\x12\'\n\nconnection\x18\x01 \x01(\x0b\x32\x13.pandora.Connection\"$\n\x14\x43\x61ptureAudioResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"7\n\x0cStartRequest\x12\'\n\nconnection\x18\x01 \x01(\x0b\x32\x13.pandora.Connection\"\x0f\n\rStartResponse\"M\n\x14PlaybackAudioRequest\x12\'\n\nconnection\x18\x01 \x01(\x0b\x32\x13.pandora.Connection\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x17\n\x15PlaybackAudioResponse\"6\n\x0bStopRequest\x12\'\n\nconnection\x18\x01 \x01(\x0b\x32\x13.pandora.Connection\"\x0e\n\x0cStopResponse\"@\n\x15WaitPeripheralRequest\x12\'\n\nconnection\x18\x01 \x01(\x0b\x32\x13.pandora.Connection\"A\n\x16WaitPeripheralResponse\x12\'\n\nconnection\x18\x01 \x01(\x0b\x32\x13.pandora.Connection2\xdc\x03\n\x04\x41sha\x12\x41\n\x08Register\x12\x1d.pandora.asha.RegisterRequest\x1a\x16.google.protobuf.Empty\x12W\n\x0c\x43\x61ptureAudio\x12!.pandora.asha.CaptureAudioRequest\x1a\".pandora.asha.CaptureAudioResponse0\x01\x12@\n\x05Start\x12\x1a.pandora.asha.StartRequest\x1a\x1b.pandora.asha.StartResponse\x12Z\n\rPlaybackAudio\x12\".pandora.asha.PlaybackAudioRequest\x1a#.pandora.asha.PlaybackAudioResponse(\x01\x12=\n\x04Stop\x12\x19.pandora.asha.StopRequest\x1a\x1a.pandora.asha.StopResponse\x12[\n\x0eWaitPeripheral\x12#.pandora.asha.WaitPeripheralRequest\x1a$.pandora.asha.WaitPeripheralResponseB\x0b\x42\tAshaProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pandora.asha_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\tAshaProto'
  _globals['_REGISTERREQUEST']._serialized_start=85
  _globals['_REGISTERREQUEST']._serialized_end=140
  _globals['_CAPTUREAUDIOREQUEST']._serialized_start=142
  _globals['_CAPTUREAUDIOREQUEST']._serialized_end=204
  _globals['_CAPTUREAUDIORESPONSE']._serialized_start=206
  _globals['_CAPTUREAUDIORESPONSE']._serialized_end=242
  _globals['_STARTREQUEST']._serialized_start=244
  _globals['_STARTREQUEST']._serialized_end=299
  _globals['_STARTRESPONSE']._serialized_start=301
  _globals['_STARTRESPONSE']._serialized_end=316
  _globals['_PLAYBACKAUDIOREQUEST']._serialized_start=318
  _globals['_PLAYBACKAUDIOREQUEST']._serialized_end=395
  _globals['_PLAYBACKAUDIORESPONSE']._serialized_start=397
  _globals['_PLAYBACKAUDIORESPONSE']._serialized_end=420
  _globals['_STOPREQUEST']._serialized_start=422
  _globals['_STOPREQUEST']._serialized_end=476
  _globals['_STOPRESPONSE']._serialized_start=478
  _globals['_STOPRESPONSE']._serialized_end=492
  _globals['_WAITPERIPHERALREQUEST']._serialized_start=494
  _globals['_WAITPERIPHERALREQUEST']._serialized_end=558
  _globals['_WAITPERIPHERALRESPONSE']._serialized_start=560
  _globals['_WAITPERIPHERALRESPONSE']._serialized_end=625
  _globals['_ASHA']._serialized_start=628
  _globals['_ASHA']._serialized_end=1104
def unwrap(x):
  assert x
  return x
# @@protoc_insertion_point(module_scope)
