// Copyright (C) 2025 The Android Open Source Project
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package pandora;

import "pandora/host.proto";
option java_outer_classname = "GmapProto";
import "google/protobuf/empty.proto";

service GMAP {
  // Start an opened stream.
  rpc GmaStart(GmaStartRequest) returns (google.protobuf.Empty);
  // Play Audio
  rpc GmaPlaybackAudio(stream GmaPlaybackAudioRequest) returns (GmaPlaybackAudioResponse);
}

message GmaStartRequest {
    Connection connection = 1;
}

message GmaPlaybackAudioRequest {
    bytes data = 1;
}

message GmaPlaybackAudioResponse {}
