syntax = "proto3";

option java_outer_classname = "HfpProto";

package pandora.hfp;

import "pandora/host.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";

// Service to trigger HFP (Hands Free Profile) procedures.
service HFP {
  // Open the service level connection as **Hands-Free** to the
  // remote **Audio Gateway** device.
  //
  // The rpc must block until the SLC initialization has completed.
  //
  // A cancellation of this call must result in aborting the current
  // HFP procedure.
  rpc OpenHandsFree(OpenHandsFreeRequest) returns (OpenHandsFreeResponse);

  // Open the service level connection as **Audio-Gateway** to the
  // remote **Hands-Free** device.
  //
  // The rpc may return before the SLC initialization has completed.
  //
  // A cancellation of this call must result in aborting the current
  // HFP procedure.
  rpc OpenAudioGateway(OpenAudioGatewayRequest) returns (OpenAudioGatewayResponse);

  // Close the selected service level connection.
  rpc Close(CloseRequest) returns (CloseResponse);

  // Setup the audio connection for the selected service level connection.
  //
  // The rpc shall block until the synchronous connection is opened and
  // the audio connection setup.
  rpc OpenAudio(OpenAudioRequest) returns (OpenAudioResponse);

  // Wait for the peer to setup the audio connection for the selected service
  // level connection.
  //
  // The rpc shall block until the synchronous connection is opened and
  // the audio connection setup.
  rpc WaitAudio(WaitAudioRequest) returns (WaitAudioResponse);

  // Close the audio connection for the selected service level connection.
  // Calling this method shall result in the synchronous connection being
  // disconnected.
  rpc CloseAudio(CloseAudioRequest) returns (CloseAudioResponse);

  // Return if the audio connection is setup for the selected service level
  // connection.
  rpc IsAudioOpen(IsAudioOpenRequest) returns (google.protobuf.BoolValue);

  // Clear the call history on the selected Audio Gateway such that
  // there are zero records of any numbers dialed, then click Ok.
//  rpc ClearCallHistory(ClearCallHistoryRequest) returns (ClearCallHistoryResponse);

  rpc PlaceCall(PlaceCallRequest) returns (PlaceCallResponse);
  rpc AnswerCall(AnswerCallRequest) returns (AnswerCallResponse);
  rpc TerminateCall(TerminateCallRequest) returns (TerminateCallResponse);
  rpc RejectCall(RejectCallRequest) returns (RejectCallResponse);

//  rpc HoldCall(HoldCallRequest) returns (HoldCallResponse);

//  rpc ActivateVoiceRecognition(ActivateVoiceRecognitionRequest) returns (ActivateVoiceRecognitionResponse);
//  rpc SendDtmf(SendDtmfRequest) returns (SendDtmfResponse);

/*
  // Change the battery level to the one requested
  rpc SetBatteryLevel(SetBatteryLevelRequest) returns (google.protobuf.Empty);

  // Swap the active and held call
  rpc SwapActiveCall(SwapActiveCallRequest) returns (SwapActiveCallResponse);
  // Set in-band ringtone
  rpc SetInBandRingtone(SetInBandRingtoneRequest) returns (SetInBandRingtoneResponse);
  // Clear the call history

  // Connect a call on hold, and disconnect the current call (as a handsfree)
  rpc CallTransferAsHandsFree(CallTransferAsHandsFreeRequest) returns (CallTransferAsHandsFreeResponse);
*/
}

// A Token representing an Hands-Free connection.
// It is obtained as result to a call to OpenHandsFree on the HFP service.
message HandsFree {
  // Opaque value filled by the GRPC server, must not
  // be modified nor crafted.
  bytes cookie = 1;
}

// A Token representing an Audio-Gateway connection.
// It is obtained as result to a call to OpenAudioGateway on the HFP service.
message AudioGateway {
  // Opaque value filled by the GRPC server, must not
  // be modified nor crafted.
  bytes cookie = 1;
}

// A Token representing either an Hands-Free or Audio-Gateway
// service level connection. It is obtained as result to a call
// to OpenHandsFree or OpenAudioGateway on the HFP service.
message ServiceLevelConnection {
  oneof slc {
    HandsFree handsfree = 1;
    AudioGateway audiogateway = 2;
  }
}

// Request for the `OpenHandsFree` method.
message OpenHandsFreeRequest {
  // The connection that will open the channel.
  Connection connection = 1;
}

// Response for the `OpenHandsFree` method.
message OpenHandsFreeResponse {
  // Result of the `OpenHandsFree` call.
  oneof result {
    HandsFree handsfree = 1;
    google.protobuf.Empty disconnected = 2;
  }
}

// Request for the `OpenAudioGateway` method.
message OpenAudioGatewayRequest {
  // The connection that will open the channel.
  Connection connection = 1;
}

// Response for the `OpenAudioGateway` method.
message OpenAudioGatewayResponse {
  // Result of the `OpenAudioGateway` call.
  oneof result {
    AudioGateway audiogateway = 1;
    google.protobuf.Empty disconnected = 2;
  }
}

// Request for the `Close` method.
message CloseRequest {
  ServiceLevelConnection slc = 1;
}

// Response for the `Close` method.
message CloseResponse {
}

// Request for the `OpenAudio` method.
message OpenAudioRequest {
  ServiceLevelConnection slc = 1;
}

// Response for the `OpenAudio` method.
message OpenAudioResponse {
  oneof result {
    google.protobuf.Empty opened = 1;
    google.protobuf.Empty already_opened = 2;
    google.protobuf.Empty disconnected = 3;
  }
}

// Request for the `WaitAudio` method.
message WaitAudioRequest {
  ServiceLevelConnection slc = 1;
}

// Response for the `WaitAudio` method.
message WaitAudioResponse {
  oneof result {
    google.protobuf.Empty opened = 1;
    google.protobuf.Empty already_opened = 2;
    google.protobuf.Empty disconnected = 3;
  }
}

// Request for the `CloseAudio` method.
message CloseAudioRequest {
  ServiceLevelConnection slc = 1;
}

// Response for the `CloseAudio` method.
message CloseAudioResponse {
  oneof result {
    google.protobuf.Empty closed = 1;
    google.protobuf.Empty already_closed = 2;
    google.protobuf.Empty disconnected = 3;
  }
}

// Request for the `IsAudioOpen` method.
message IsAudioOpenRequest {
  ServiceLevelConnection slc = 1;
}

// Request for the `PlaceCall` method.
message PlaceCallRequest {
  ServiceLevelConnection slc = 1;
  oneof dial {
    google.protobuf.Empty last = 2;
    string number = 3;
    string memory = 4;
  }
}

// Response for the `PlaceCall` method.
message PlaceCallResponse {
}

// Request for the `AnswerCall` method.
message AnswerCallRequest {
  ServiceLevelConnection slc = 1;
}

// Response for the `AnswerCall` method.
message AnswerCallResponse {
}

// Request for the `TerminateCall` method.
message TerminateCallRequest {
  ServiceLevelConnection slc = 1;
}

// Response for the `TerminateCall` method.
message TerminateCallResponse {
}

// Request for the `RejectCall` method.
message RejectCallRequest {
  ServiceLevelConnection slc = 1;
}

// Response for the `RejectCall` method.
message RejectCallResponse {
}
