# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pandora/hid.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11pandora/hid.proto\x12\x07pandora\"e\n\x15SendHostReportRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12+\n\x0breport_type\x18\x02 \x01(\x0e\x32\x16.pandora.HidReportType\x12\x0e\n\x06report\x18\x03 \x01(\t\"\x18\n\x16SendHostReportResponse*\x84\x01\n\rHidReportType\x12\x1f\n\x1bHID_REPORT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15HID_REPORT_TYPE_INPUT\x10\x01\x12\x1a\n\x16HID_REPORT_TYPE_OUTPUT\x10\x02\x12\x1b\n\x17HID_REPORT_TYPE_FEATURE\x10\x03\x32X\n\x03HID\x12Q\n\x0eSendHostReport\x12\x1e.pandora.SendHostReportRequest\x1a\x1f.pandora.SendHostReportResponseB\nB\x08HidProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pandora.hid_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\010HidProto'
  _globals['_HIDREPORTTYPE']._serialized_start=160
  _globals['_HIDREPORTTYPE']._serialized_end=292
  _globals['_SENDHOSTREPORTREQUEST']._serialized_start=30
  _globals['_SENDHOSTREPORTREQUEST']._serialized_end=131
  _globals['_SENDHOSTREPORTRESPONSE']._serialized_start=133
  _globals['_SENDHOSTREPORTRESPONSE']._serialized_end=157
  _globals['_HID']._serialized_start=294
  _globals['_HID']._serialized_end=382
def unwrap(x):
  assert x
  return x
class HidReportType: ...

# @@protoc_insertion_point(module_scope)
