# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pandora/l2cap.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from pandora import host_pb2 as pandora_dot_host__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13pandora/l2cap.proto\x12\x07pandora\x1a\x1bgoogle/protobuf/empty.proto\x1a\x12pandora/host.proto\"i\n!CreateLECreditBasedChannelRequest\x12\'\n\nconnection\x18\x01 \x01(\x0b\x32\x13.pandora.Connection\x12\x0b\n\x03psm\x18\x02 \x01(\x05\x12\x0e\n\x06secure\x18\x03 \x01(\x08\"$\n\"CreateLECreditBasedChannelResponse\"H\n\x0fSendDataRequest\x12\'\n\nconnection\x18\x01 \x01(\x0b\x32\x13.pandora.Connection\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x12\n\x10SendDataResponse\"=\n\x12ReceiveDataRequest\x12\'\n\nconnection\x18\x01 \x01(\x0b\x32\x13.pandora.Connection\"#\n\x13ReceiveDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"T\n\x19ListenL2CAPChannelRequest\x12\'\n\nconnection\x18\x01 \x01(\x0b\x32\x13.pandora.Connection\x12\x0e\n\x06secure\x18\x02 \x01(\x08\"\x1c\n\x1aListenL2CAPChannelResponse\"D\n\x19\x41\x63\x63\x65ptL2CAPChannelRequest\x12\'\n\nconnection\x18\x01 \x01(\x0b\x32\x13.pandora.Connection\"\x1c\n\x1a\x41\x63\x63\x65ptL2CAPChannelResponse2\xc7\x03\n\x05L2CAP\x12u\n\x1a\x43reateLECreditBasedChannel\x12*.pandora.CreateLECreditBasedChannelRequest\x1a+.pandora.CreateLECreditBasedChannelResponse\x12?\n\x08SendData\x12\x18.pandora.SendDataRequest\x1a\x19.pandora.SendDataResponse\x12H\n\x0bReceiveData\x12\x1b.pandora.ReceiveDataRequest\x1a\x1c.pandora.ReceiveDataResponse\x12]\n\x12ListenL2CAPChannel\x12\".pandora.ListenL2CAPChannelRequest\x1a#.pandora.ListenL2CAPChannelResponse\x12]\n\x12\x41\x63\x63\x65ptL2CAPChannel\x12\".pandora.AcceptL2CAPChannelRequest\x1a#.pandora.AcceptL2CAPChannelResponseB\x0c\x42\nL2capProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pandora.l2cap_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\nL2capProto'
  _globals['_CREATELECREDITBASEDCHANNELREQUEST']._serialized_start=81
  _globals['_CREATELECREDITBASEDCHANNELREQUEST']._serialized_end=186
  _globals['_CREATELECREDITBASEDCHANNELRESPONSE']._serialized_start=188
  _globals['_CREATELECREDITBASEDCHANNELRESPONSE']._serialized_end=224
  _globals['_SENDDATAREQUEST']._serialized_start=226
  _globals['_SENDDATAREQUEST']._serialized_end=298
  _globals['_SENDDATARESPONSE']._serialized_start=300
  _globals['_SENDDATARESPONSE']._serialized_end=318
  _globals['_RECEIVEDATAREQUEST']._serialized_start=320
  _globals['_RECEIVEDATAREQUEST']._serialized_end=381
  _globals['_RECEIVEDATARESPONSE']._serialized_start=383
  _globals['_RECEIVEDATARESPONSE']._serialized_end=418
  _globals['_LISTENL2CAPCHANNELREQUEST']._serialized_start=420
  _globals['_LISTENL2CAPCHANNELREQUEST']._serialized_end=504
  _globals['_LISTENL2CAPCHANNELRESPONSE']._serialized_start=506
  _globals['_LISTENL2CAPCHANNELRESPONSE']._serialized_end=534
  _globals['_ACCEPTL2CAPCHANNELREQUEST']._serialized_start=536
  _globals['_ACCEPTL2CAPCHANNELREQUEST']._serialized_end=604
  _globals['_ACCEPTL2CAPCHANNELRESPONSE']._serialized_start=606
  _globals['_ACCEPTL2CAPCHANNELRESPONSE']._serialized_end=634
  _globals['_L2CAP']._serialized_start=637
  _globals['_L2CAP']._serialized_end=1092
def unwrap(x):
  assert x
  return x
# @@protoc_insertion_point(module_scope)
