# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pandora/le_audio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pandora import host_pb2 as pandora_dot_host__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16pandora/le_audio.proto\x12\x07pandora\x1a\x12pandora/host.proto\x1a\x1bgoogle/protobuf/empty.proto\"6\n\x0bOpenRequest\x12\'\n\nconnection\x18\x01 \x01(\x0b\x32\x13.pandora.Connection2?\n\x07LeAudio\x12\x34\n\x04Open\x12\x14.pandora.OpenRequest\x1a\x16.google.protobuf.EmptyB\x0e\x42\x0cLeAudioProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pandora.le_audio_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\014LeAudioProto'
  _globals['_OPENREQUEST']._serialized_start=84
  _globals['_OPENREQUEST']._serialized_end=138
  _globals['_LEAUDIO']._serialized_start=140
  _globals['_LEAUDIO']._serialized_end=203
def unwrap(x):
  assert x
  return x
# @@protoc_insertion_point(module_scope)
