# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pandora/mediaplayer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19pandora/mediaplayer.proto\x12\x07pandora\x1a\x1bgoogle/protobuf/empty.proto\";\n\x15SetShuffleModeRequest\x12\"\n\x04mode\x18\x01 \x01(\x0e\x32\x14.pandora.ShuffleMode\"<\n\x16GetShuffleModeResponse\x12\"\n\x04mode\x18\x01 \x01(\x0e\x32\x14.pandora.ShuffleMode*+\n\x0bShuffleMode\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03\x41LL\x10\x01\x12\t\n\x05GROUP\x10\x02\x32\xc7\x06\n\x0bMediaPlayer\x12\x36\n\x04Play\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x36\n\x04Stop\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x37\n\x05Pause\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x38\n\x06Rewind\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12=\n\x0b\x46\x61stForward\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x39\n\x07\x46orward\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n\x08\x42\x61\x63kward\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x42\n\x10SetLargeMetadata\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12=\n\x0bUpdateQueue\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12I\n\x0eGetShuffleMode\x12\x16.google.protobuf.Empty\x1a\x1f.pandora.GetShuffleModeResponse\x12H\n\x0eSetShuffleMode\x12\x1e.pandora.SetShuffleModeRequest\x1a\x16.google.protobuf.Empty\x12\x43\n\x11StartTestPlayback\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x42\n\x10StopTestPlayback\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\x12\x42\x10MediaPlayerProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pandora.mediaplayer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\020MediaPlayerProto'
  _globals['_SHUFFLEMODE']._serialized_start=190
  _globals['_SHUFFLEMODE']._serialized_end=233
  _globals['_SETSHUFFLEMODEREQUEST']._serialized_start=67
  _globals['_SETSHUFFLEMODEREQUEST']._serialized_end=126
  _globals['_GETSHUFFLEMODERESPONSE']._serialized_start=128
  _globals['_GETSHUFFLEMODERESPONSE']._serialized_end=188
  _globals['_MEDIAPLAYER']._serialized_start=236
  _globals['_MEDIAPLAYER']._serialized_end=1075
def unwrap(x):
  assert x
  return x
class ShuffleMode: ...

# @@protoc_insertion_point(module_scope)
