// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

option java_outer_classname = "ModemProto";

package pandora.modem;

service Modem {
  // Hangs up all active calls.
  rpc Close(CloseRequest) returns (CloseResponse);

  // Makes a phone call.
  rpc Call(CallRequest) returns (CallResponse);

  // Answers a phone call.
  rpc AnswerCall(AnswerCallRequest) returns (AnswerCallResponse);
}

// Request for the `Close` method.
message CloseRequest {}

// Response for the `Close` method.
message CloseResponse {}

// Request for the `Call` method.
message CallRequest {
  string phone_number = 1;
  string remote_phone_number = 2;
}

// Response for the `Call` method.
message CallResponse {}

// Request for the `AnswerCall` method.
message AnswerCallRequest {
  string phone_number = 1;
  string remote_phone_number = 2;
  AnswerCallAction action = 3;
}

// Response for the `AnswerCall` method.
message AnswerCallResponse {}

enum AnswerCallAction {
  ANSWER = 0;
  REJECT = 1;
  HOLD = 2;
}