# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pandora/os.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pandora import host_pb2 as pandora_dot_host__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pandora/os.proto\x12\x07pandora\x1a\x12pandora/host.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1a\n\nLogRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\r\n\x0bLogResponse\"W\n\x1aSetAccessPermissionRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12(\n\x0b\x61\x63\x63\x65ss_type\x18\x02 \x01(\x0e\x32\x13.pandora.AccessType\";\n\x15InternalConnectionRef\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12\x11\n\ttransport\x18\x02 \x01(\x05\"%\n\x0fSendPingRequest\x12\x12\n\nip_address\x18\x01 \x01(\t*F\n\nAccessType\x12\x12\n\x0e\x41\x43\x43\x45SS_MESSAGE\x10\x00\x12\x14\n\x10\x41\x43\x43\x45SS_PHONEBOOK\x10\x01\x12\x0e\n\nACCESS_SIM\x10\x02\x32\xc8\x01\n\x02Os\x12\x30\n\x03Log\x12\x13.pandora.LogRequest\x1a\x14.pandora.LogResponse\x12R\n\x13SetAccessPermission\x12#.pandora.SetAccessPermissionRequest\x1a\x16.google.protobuf.Empty\x12<\n\x08SendPing\x12\x18.pandora.SendPingRequest\x1a\x16.google.protobuf.EmptyB\tB\x07OsProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pandora.os_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\007OsProto'
  _globals['_ACCESSTYPE']._serialized_start=310
  _globals['_ACCESSTYPE']._serialized_end=380
  _globals['_LOGREQUEST']._serialized_start=78
  _globals['_LOGREQUEST']._serialized_end=104
  _globals['_LOGRESPONSE']._serialized_start=106
  _globals['_LOGRESPONSE']._serialized_end=119
  _globals['_SETACCESSPERMISSIONREQUEST']._serialized_start=121
  _globals['_SETACCESSPERMISSIONREQUEST']._serialized_end=208
  _globals['_INTERNALCONNECTIONREF']._serialized_start=210
  _globals['_INTERNALCONNECTIONREF']._serialized_end=269
  _globals['_SENDPINGREQUEST']._serialized_start=271
  _globals['_SENDPINGREQUEST']._serialized_end=308
  _globals['_OS']._serialized_start=383
  _globals['_OS']._serialized_end=583
def unwrap(x):
  assert x
  return x
class AccessType: ...

# @@protoc_insertion_point(module_scope)
