# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pandora/pan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pandora import host_pb2 as pandora_dot_host__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11pandora/pan.proto\x12\x07pandora\x1a\x12pandora/host.proto\"\x18\n\x16\x45nableTetheringRequest\"\x19\n\x17\x45nableTetheringResponse\"$\n\x11\x43onnectPanRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\"=\n\x12\x43onnectPanResponse\x12\'\n\nconnection\x18\x01 \x01(\x0b\x32\x13.pandora.Connection2\xa2\x01\n\x03PAN\x12T\n\x0f\x45nableTethering\x12\x1f.pandora.EnableTetheringRequest\x1a .pandora.EnableTetheringResponse\x12\x45\n\nConnectPan\x12\x1a.pandora.ConnectPanRequest\x1a\x1b.pandora.ConnectPanResponseB\nB\x08PanProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pandora.pan_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\010PanProto'
  _globals['_ENABLETETHERINGREQUEST']._serialized_start=50
  _globals['_ENABLETETHERINGREQUEST']._serialized_end=74
  _globals['_ENABLETETHERINGRESPONSE']._serialized_start=76
  _globals['_ENABLETETHERINGRESPONSE']._serialized_end=101
  _globals['_CONNECTPANREQUEST']._serialized_start=103
  _globals['_CONNECTPANREQUEST']._serialized_end=139
  _globals['_CONNECTPANRESPONSE']._serialized_start=141
  _globals['_CONNECTPANRESPONSE']._serialized_end=202
  _globals['_PAN']._serialized_start=205
  _globals['_PAN']._serialized_end=367
def unwrap(x):
  assert x
  return x
# @@protoc_insertion_point(module_scope)
