import asyncio
import time
from typing import AsyncGenerator

from floss.pandora.floss import adapter_client
from floss.pandora.floss import utils
from floss.pandora.floss import audio_utils
from floss.pandora.floss import cras_utils
from floss.pandora.server import bluetooth as bluetooth_module
from google.protobuf import wrappers_pb2, empty_pb2
import grpc
import json
from pandora import a2dp_grpc_aio
from pandora import a2dp_pb2


class A2DPService(a2dp_grpc_aio.A2DPServicer):
    """Service to trigger Bluetooth A2DP procedures.

        This class implements the Pandora bluetooth test interfaces,
        where the meta class definition is automatically generated by the protobuf.
        The interface definition can be found in:
        https://cs.android.com/android/platform/superproject/+/main:external
        /pandora/bt-test-interfaces/pandora/a2dp.proto
        """

    def __init__(self, bluetooth: bluetooth_module.Bluetooth):
        self.bluetooth = bluetooth
        self._cras_test_client = cras_utils.CrasTestClient()

    def check_target_connection(self, target, message):
        if target == 'source':
            if not audio_utils.test_select_audio_input_node_bluetooth():
                raise RuntimeError(message)
        elif target == 'sink':
            if not audio_utils.test_select_audio_output_node_bluetooth():
                raise RuntimeError(message)
        raise RuntimeError(f'Invalid target type: {target}')

    async def OpenSource(self, request: a2dp_pb2.OpenSourceRequest,
                         context: grpc.ServicerContext) -> a2dp_pb2.OpenSourceResponse:
        class ConnectionObserver(adapter_client.BluetoothConnectionCallbacks):
            """Observer to observe the a2dp device connection state."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_device_connected(self, remote_device):
                print('OpenSource: on_device_connected')
                address, _ = remote_device
                if address != self.task['address']:
                    return

                future = self.task['open_source']
                future.get_loop().call_soon_threadsafe(future.set_result, True)

        address = utils.address_from(request.connection.cookie.value)
        if not audio_utils.test_select_audio_input_node_bluetooth():
            try:
                print('OpenSource: not connected')
                open_source = asyncio.get_running_loop().create_future()
                observer = ConnectionObserver({'open_source': open_source, 'address': address})
                name = utils.create_observer_name(observer)
                self.bluetooth.adapter_client.register_callback_observer(name, observer)
                self.bluetooth.connect_device(address)
                success = await open_source
                print(f'OpenSource: success: {success}')
                if not success:
                    raise RuntimeError(f'Failed to connect to the address: {address}.')
            finally:
                self.bluetooth.adapter_client.unregister_callback_observer(name, observer)

        time.sleep(2)
        cookie = utils.address_to(address)
        return a2dp_pb2.OpenSourceResponse(source=a2dp_pb2.Source(cookie=cookie))


    async def OpenSink(self, request: a2dp_pb2.OpenSinkRequest,
                       context: grpc.ServicerContext) -> a2dp_pb2.OpenSinkResponse:
        class ConnectionObserver(adapter_client.BluetoothConnectionCallbacks):
            """Observer to observe the a2dp device connection state."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_device_connected(self, remote_device):
                print('OpenSink: on_device_connected')
                address, _ = remote_device
                if address != self.task['address']:
                    return

                future = self.task['open_sink']
                future.get_loop().call_soon_threadsafe(future.set_result, True)

        address = utils.address_from(request.connection.cookie.value)
        if not audio_utils.test_select_audio_output_node_bluetooth():
            try:
                print('OpenSink: not connected')
                open_sink = asyncio.get_running_loop().create_future()
                observer = ConnectionObserver({'open_sink': open_sink, 'address': address})
                name = utils.create_observer_name(observer)
                self.bluetooth.adapter_client.register_callback_observer(name, observer)
                self.bluetooth.connect_device(address)
                success = await open_sink
                print(f'OpenSink: success: {success}')
                if not success:
                    raise RuntimeError(f'Failed to connect to the address: {address}.')
            finally:
                self.bluetooth.adapter_client.unregister_callback_observer(name, observer)

        time.sleep(2)
        cookie = utils.address_to(address)
        return a2dp_pb2.OpenSinkResponse(sink=a2dp_pb2.Sink(cookie=cookie))


    async def WaitSource(self, request: a2dp_pb2.WaitSourceRequest,
                         context: grpc.ServicerContext) -> a2dp_pb2.WaitSourceResponse:
        class ConnectionObserver(adapter_client.BluetoothConnectionCallbacks):
            """Observer to observe the a2dp device connection state."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_device_connected(self, remote_device):
                print('WaitSource: on_device_connected')
                address, _ = remote_device
                if address != self.task['address']:
                    return

                future = self.task['open_sink']
                future.get_loop().call_soon_threadsafe(future.set_result, True)

        address = utils.address_from(request.connection.cookie.value)
        print(f'WaitSource: address {address}')
        if not address:
            raise ValueError('Request address field must be set.')

        if not audio_utils.test_select_audio_input_node_bluetooth():
            try:
                print('WaitSource: not connected')
                wait_source = asyncio.get_running_loop().create_future()
                observer = ConnectionObserver({'wait_source': wait_source, 'address': address})
                name = utils.create_observer_name(observer)
                self.bluetooth.adapter_client.register_callback_observer(name, observer)

                await wait_source
            finally:
                self.bluetooth.adapter_client.unregister_callback_observer(name, observer)

        cookie = utils.address_to(address)
        return a2dp_pb2.WaitSourceResponse(source=a2dp_pb2.Source(cookie=cookie))


    async def WaitSink(self, request: a2dp_pb2.WaitSinkRequest,
                       context: grpc.ServicerContext) -> a2dp_pb2.WaitSinkResponse:
        class ConnectionObserver(adapter_client.BluetoothConnectionCallbacks):
            """Observer to observe the a2dp device connection state."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_device_connected(self, remote_device):
                print('WaitSink: on_device_connected')
                address, _ = remote_device
                if address != self.task['address']:
                    return

                future = self.task['open_sink']
                future.get_loop().call_soon_threadsafe(future.set_result, True)

        address = utils.address_from(request.connection.cookie.value)
        if not address:
            raise ValueError('Request address field must be set.')

        if not audio_utils.test_select_audio_output_node_bluetooth():
            try:
                print('WaitSink: not connected')
                wait_sink = asyncio.get_running_loop().create_future()
                observer = ConnectionObserver({'wait_sink': wait_sink, 'address': address})
                name = utils.create_observer_name(observer)
                self.bluetooth.adapter_client.register_callback_observer(name, observer)

                await wait_sink
            finally:
                self.bluetooth.adapter_client.unregister_callback_observer(name, observer)

        cookie = utils.address_to(address)
        return a2dp_pb2.WaitSinkResponse(sink=a2dp_pb2.Sink(cookie=cookie))


    async def IsSuspended(self, request: a2dp_pb2.IsSuspendedRequest,
                          context: grpc.ServicerContext) -> wrappers_pb2.BoolValue:
        target = request.WhichOneof('target')
        print(f'IsSuspended: target {target}')
        message = 'A2dp device is not connected, cannot get suspend state'
        self.check_target_connection(target, message)

        is_suspended = cras_utils.get_active_stream_count() == 0
        print(f'IsSuspended: is_suspended {is_suspended}')
        return wrappers_pb2.BoolValue(value=is_suspended)


    async def Start(self, request: a2dp_pb2.StartRequest,
                    context: grpc.ServicerContext) -> a2dp_pb2.StartResponse:
        target = request.WhichOneof('target')
        print(f'Start: target {target}')
        message = 'A2dp device is not connected, cannot start'
        self.check_target_connection(target, message)

        audio_data = json.dumps(audio_utils.a2dp_test_data)
        audio_data = json.loads(audio_data)
        print(f'Start: audio_data {audio_data}')

        if target == 'source':
            try:
                self._cras_test_client.start_playing_subprocess(
                    audio_data['file'],
                    channels=audio_data['channels'],
                    rate=audio_data['rate'],
                    duration=audio_data['duration']
                )
            except Exception as e:
                raise RuntimeError(f'start_playing_subprocess() failed: {e}')
        elif target == 'sink':
            try:
                self._cras_test_client.start_capturing_subprocess(
                    audio_data['recorded_by_sink'],
                    sample_format=audio_data['format'],
                    channels=audio_data['channels'],
                    rate=audio_data['rate'],
                    duration=audio_data['duration']
                )
            except Exception as e:
                raise RuntimeError(f'start_capturing_subprocess() failed: {e}')

        return a2dp_pb2.StartResponse(started=empty_pb2.Empty())


    async def Suspend(self, request: a2dp_pb2.SuspendRequest,
                      context: grpc.ServicerContext) -> a2dp_pb2.SuspendResponse:
        target = request.WhichOneof('target')
        print(f'Suspend: target {target}')
        message = 'A2dp device is not connected, cannot suspend'
        self.check_target_connection(target, message)

        if cras_utils.get_active_stream_count() == 0:
            raise RuntimeError('Device is already suspended, cannot suspend')

        if target == 'source':
            try:
                self._cras_test_client.stop_playing_subprocess()
            except Exception as e:
                raise RuntimeError(f'stop_playing_subprocess() failed: {e}')
        elif target == 'sink':
            try:
                self._cras_test_client.stop_capturing_subprocess()
            except Exception as e:
                raise RuntimeError(f'stop_capturing_subprocess() failed: {e}')

        return a2dp_pb2.SuspendResponse(suspended=empty_pb2.Empty())


    async def Close(self, request: a2dp_pb2.CloseRequest,
                    context: grpc.ServicerContext) -> a2dp_pb2.CloseResponse:
        class ConnectionObserver(adapter_client.BluetoothConnectionCallbacks):
            """Observer to observe the a2dp device connection state."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_device_disconnected(self, remote_device):
                print(f'Close: on_device_disconnected')
                address, _ = remote_device
                if address != self.task['address']:
                    return

                future = self.task['close_stream']
                future.get_loop().call_soon_threadsafe(future.set_result, True)

        target = request.WhichOneof('target')
        print(f'Close: target {target}')
        address = utils.address_from(request.target.cookie)
        print(f'Close: address {address}')
        message = 'A2dp device is not connected, cannot close'
        self.check_target_connection(target, message)

        try:
            close_stream = asyncio.get_running_loop().create_future()
            observer = ConnectionObserver({'close_stream': close_stream, 'address': address})
            name = utils.create_observer_name(observer)
            self.bluetooth.adapter_client.register_callback_observer(name, observer)
            self.bluetooth.disconnect_device(address)
            success = await close_stream
            print(f'Close: success {success}')
            if not success:
                raise RuntimeError(f'Failed to disconnect the address: {address}.')
        finally:
            self.bluetooth.adapter_client.unregister_callback_observer(name, observer)
        return a2dp_pb2.CloseResponse()


    async def GetAudioEncoding(self, request: a2dp_pb2.GetAudioEncodingRequest,
                               context: grpc.ServicerContext) -> a2dp_pb2.GetAudioEncodingResponse:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)  # type: ignore
        context.set_details('Method not implemented!')  # type: ignore
        raise NotImplementedError('Method not implemented!')


    async def PlaybackAudio(self, request: a2dp_pb2.PlaybackAudioRequest,
                            context: grpc.ServicerContext) -> a2dp_pb2.PlaybackAudioResponse:
        audio_data = request.data
        print(f'PlaybackAudio: audio_data {audio_data}')

        try:
            self._cras_test_client.play(audio_data)
        except Exception as e:
            raise RuntimeError(f'PlaybackAudio failed: {e}')

        return a2dp_pb2.PlaybackAudioResponse()

    async def CaptureAudio(self, request: a2dp_pb2.CaptureAudioRequest,
                           context: grpc.ServicerContext) -> AsyncGenerator[a2dp_pb2.CaptureAudioResponse, None]:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)  # type: ignore
        context.set_details('Method not implemented!')  # type: ignore
        raise NotImplementedError('Method not implemented!')
