import asyncio
import time
from typing import AsyncGenerator
from typing import AsyncIterator

from floss.pandora.floss import adapter_client
from floss.pandora.floss import utils
from floss.pandora.floss import floss_enums
from floss.pandora.floss import audio_utils
from floss.pandora.floss import cras_utils
from floss.pandora.server import bluetooth as bluetooth_module
from google.protobuf import wrappers_pb2, empty_pb2
import grpc
import json
import logging
from pandora import a2dp_grpc_aio
from pandora import a2dp_pb2
from pandora import security_grpc_aio

class A2DPService(a2dp_grpc_aio.A2DPServicer):
    """Service to trigger Bluetooth A2DP procedures.

    This class implements the Pandora bluetooth test interfaces,
    where the meta class definition is automatically generated by the protobuf.
    The interface definition can be found in:
    https://cs.android.com/android/platform/superproject/+/main:external
    /pandora/bt-test-interfaces/pandora/a2dp.proto
    """

    def __init__(self, bluetooth: bluetooth_module.Bluetooth, security: security_grpc_aio.SecurityServicer):
        self.bluetooth = bluetooth
        self.security = security
        self.audio_signals_count = 0
        self._cras_test_client = cras_utils.CrasTestClient()
        cras_utils.set_floss_enabled(True)

    class PairingObserver(adapter_client.BluetoothCallbacks):
        """Observer to observe the bond state."""

        def __init__(self, client: adapter_client, security: security_grpc_aio.SecurityServicer, task):
            self.client = client
            self.security = security
            self.task = task

        @utils.glib_callback()
        def on_bond_state_changed(self, status, address, state):
            logging.info('on_bond_state_changed')
            logging.info(f'status: {status}, address: {address}, state: {state}, task: {self.task}')
            if address != self.task['address']:
                return

            if status != 0:
                future = self.task['wait_bond']
                future.get_loop().call_soon_threadsafe(
                    future.set_result, (False, f'{address} failed to bond. Status: {status}, State: {state}'))
                return

            if state == floss_enums.BondState.BONDED:
                logging.info('PairingObserver : bonded')
                if not self.client.is_connected(self.task['address']):
                    logging.info('%s calling connect_all_enabled_profiles', address)
                    if not self.client.connect_all_enabled_profiles(self.task['address']):
                        logging.info('PairingObserver : not_connected')
                        future = self.task['wait_bond']
                        future.get_loop().call_soon_threadsafe(
                            future.set_result,
                            (False, f'{self.task["address"]} failed on connect_all_enabled_profiles'))
                else:
                    future = self.task['wait_bond']
                    future.get_loop().call_soon_threadsafe(future.set_result, (True, None))

        @utils.glib_callback()
        def on_ssp_request(self, remote_device, class_of_device, variant, passkey):
            logging.info('on_ssp_request')
            logging.info(f'variant: {variant}, passkey: {passkey}')
            if self.security.manually_confirm:
                return

            address, _ = remote_device
            if address != self.task['address']:
                return

            if variant in (floss_enums.PairingVariant.CONSENT, floss_enums.PairingVariant.PASSKEY_CONFIRMATION):
                self.client.set_pairing_confirmation(address,
                                                     True,
                                                     method_callback=self.on_set_pairing_confirmation)

        @utils.glib_callback()
        def on_set_pairing_confirmation(self, err, result):
            logging.info('on_set_pairing_confirmation')
            if err or not result:
                future = self.task['wait_bond']
                future.get_loop().call_soon_threadsafe(
                    future.set_result, (False, f'Pairing confirmation failed: err: {err}, result: {result}'))

    async def OpenSource(self, request: a2dp_pb2.OpenSourceRequest,
                         context: grpc.ServicerContext) -> a2dp_pb2.OpenSourceResponse:

        class ConnectionObserver(adapter_client.BluetoothConnectionCallbacks):
            """Observer to observe the a2dp device connection state."""

            def __init__(self, client: adapter_client, task):
                self.client = client
                self.task = task

            @utils.glib_callback()
            def on_device_connected(self, remote_device):
                logging.info('OpenSource: on_device_connected')
                address, _ = remote_device
                if address != self.task['address']:
                    return

                if self.client.is_bonded(address):
                    future = self.task['open_source']
                    future.get_loop().call_soon_threadsafe(future.set_result, (True, None))

        connection = utils.connection_from(request.connection)
        address = connection.address

        if not self.bluetooth.is_connected(address):
            name = None
            observer = None
            try:
                if self.bluetooth.is_bonded(address):
                    logging.info(f'OpenSource is_bonded: {self.bluetooth.is_bonded(address)}')
                    open_source = asyncio.get_running_loop().create_future()
                    observer = ConnectionObserver(self.bluetooth.adapter_client, {
                        'open_source': open_source,
                        'address': address
                    })
                    name = utils.create_observer_name(observer)
                    self.bluetooth.adapter_client.register_callback_observer(name, observer)

                    self.bluetooth.connect_device(address)
                    success, reason = await open_source

                    if not success:
                        raise RuntimeError(f'Failed to connect to the {address}. Reason: {reason}')
                else:
                    logging.info(f'OpenSource: bonded')
                    wait_bond = asyncio.get_running_loop().create_future()
                    observer = self.PairingObserver(
                        self.bluetooth.adapter_client,
                        self.security,
                        {
                            'wait_bond': wait_bond,
                            'address': address
                        },
                    )
                    name = utils.create_observer_name(observer)
                    self.bluetooth.adapter_client.register_callback_observer(name, observer)

                    if not self.bluetooth.create_bond(address, floss_enums.BtTransport.BREDR):
                        raise RuntimeError('Failed to call create_bond.')

                    success, reason = await wait_bond
                    print(success)

                    if not success:
                        raise RuntimeError(f'Failed to connect to the {address}. Reason: {reason}')
            finally:
                self.bluetooth.adapter_client.unregister_callback_observer(name, observer)

        time.sleep(2)
        cookie = utils.address_to(address)
        logging.info(f'OpenSource: cookie {cookie}')
        return a2dp_pb2.OpenSourceResponse(source=a2dp_pb2.Source(cookie=cookie))

    async def OpenSink(self, request: a2dp_pb2.OpenSinkRequest,
                       context: grpc.ServicerContext) -> a2dp_pb2.OpenSinkResponse:

        class ConnectionObserver(adapter_client.BluetoothConnectionCallbacks):
            """Observer to observe the a2dp device connection state."""

            def __init__(self, client: adapter_client, task):
                self.client = client
                self.task = task

            @utils.glib_callback()
            def on_device_connected(self, remote_device):
                logging.info('OpenSink: on_device_connected')
                address, _ = remote_device
                if address != self.task['address']:
                    return

                if self.client.is_bonded(address):
                    future = self.task['open_sink']
                    future.get_loop().call_soon_threadsafe(future.set_result, (True, None))

        connection = utils.connection_from(request.connection)
        address = connection.address
        if not self.bluetooth.is_connected(address):
            name = None
            observer = None
            try:
                if self.bluetooth.is_bonded(address):
                    logging.info(f'OpenSink is_bonded: {self.bluetooth.is_bonded(address)}')
                    open_source = asyncio.get_running_loop().create_future()
                    observer = ConnectionObserver(self.bluetooth.adapter_client, {
                        'open_source': open_source,
                        'address': address
                    })
                    name = utils.create_observer_name(observer)
                    self.bluetooth.adapter_client.register_callback_observer(name, observer)

                    self.bluetooth.connect_device(address)
                    success, reason = await open_source

                    if not success:
                        raise RuntimeError(f'Failed to connect to the {address}. Reason: {reason}')
                else:
                    logging.info(f'OpenSink: bonded')
                    wait_bond = asyncio.get_running_loop().create_future()
                    observer = self.PairingObserver(
                        self.bluetooth.adapter_client,
                        self.security,
                        {
                            'wait_bond': wait_bond,
                            'address': address
                        },
                    )
                    name = utils.create_observer_name(observer)
                    self.bluetooth.adapter_client.register_callback_observer(name, observer)

                    if not self.bluetooth.create_bond(address, floss_enums.BtTransport.BREDR):
                        raise RuntimeError('Failed to call create_bond.')

                    success, reason = await wait_bond
                    print(success)

                    if not success:
                        raise RuntimeError(f'Failed to connect to the {address}. Reason: {reason}')
            finally:
                self.bluetooth.adapter_client.unregister_callback_observer(name, observer)

        time.sleep(2)
        cookie = utils.address_to(address)
        return a2dp_pb2.OpenSinkResponse(sink=a2dp_pb2.Sink(cookie=cookie))

    async def WaitSource(self, request: a2dp_pb2.WaitSourceRequest,
                         context: grpc.ServicerContext) -> a2dp_pb2.WaitSourceResponse:

        class ConnectionObserver(adapter_client.BluetoothConnectionCallbacks):
            """Observer to observe the a2dp device connection state."""

            def __init__(self, client: adapter_client, task):
                self.task = task
                self.client = client

            @utils.glib_callback()
            def on_device_connected(self, remote_device):
                logging.info('WaitSource: on_device_connected')
                address, _ = remote_device
                if address != self.task['address']:
                    return

                if self.client.is_bonded(address):
                    future = self.task['wait_source']
                    future.get_loop().call_soon_threadsafe(future.set_result, (True, None))

        connection = utils.connection_from(request.connection)
        address = connection.address
        if not address:
            raise ValueError('Request address field must be set.')

        logging.info(f'WaitSource {self.bluetooth.is_connected(address)} {address}')
        if not self.bluetooth.is_connected(address):
            logging.info('not connected')
            try:
                if self.bluetooth.is_bonded(address):
                    logging.info('bonded')
                    wait_source = asyncio.get_running_loop().create_future()
                    observer = ConnectionObserver(self.bluetooth.adapter_client, {
                        'wait_source': wait_source,
                        'address': address
                    })
                    name = utils.create_observer_name(observer)
                    self.bluetooth.adapter_client.register_callback_observer(name, observer)

                    await wait_source
                else:
                    logging.info('not bonded')
                    wait_bond = asyncio.get_running_loop().create_future()
                    observer = self.PairingObserver(
                        self.bluetooth.adapter_client,
                        self.security,
                        {
                            'wait_bond': wait_bond,
                            'address': address
                        }
                    )
                    name = utils.create_observer_name(observer)
                    self.bluetooth.adapter_client.register_callback_observer(name, observer)

                    success, reason = await wait_bond
                    if not success:
                        raise RuntimeError(f'Failed to connect to the {address}. Reason: {reason}')
            finally:
                self.bluetooth.adapter_client.unregister_callback_observer(name, observer)

        time.sleep(2)
        cookie = utils.address_to(address)
        logging.info(cookie)
        return a2dp_pb2.WaitSourceResponse(source=a2dp_pb2.Source(cookie=cookie))

    async def WaitSink(self, request: a2dp_pb2.WaitSinkRequest,
                       context: grpc.ServicerContext) -> a2dp_pb2.WaitSinkResponse:

        class ConnectionObserver(adapter_client.BluetoothConnectionCallbacks):
            """Observer to observe the a2dp device connection state."""

            def __init__(self, client: adapter_client, task):
                self.task = task
                self.client = client

            @utils.glib_callback()
            def on_device_connected(self, remote_device):
                logging.info('WaitSink: on_device_connected')
                address, _ = remote_device
                if address != self.task['address']:
                    return

                if self.client.is_bonded(address):
                    future = self.task['wait_sink']
                    future.get_loop().call_soon_threadsafe(future.set_result, (True, None))

        connection = utils.connection_from(request.connection)
        address = connection.address
        if not address:
            raise ValueError('Request address field must be set.')

        logging.info(f'WaitSink {self.bluetooth.is_connected(address)} {address}')
        if not self.bluetooth.is_connected(address):
            try:
                if self.bluetooth.is_bonded(address):
                    logging.info(f'WaitSink isbonded')
                    wait_sink = asyncio.get_running_loop().create_future()
                    observer = ConnectionObserver(self.bluetooth.adapter_client, {
                        'wait_sink': wait_sink,
                        'address': address
                    })
                    name = utils.create_observer_name(observer)
                    self.bluetooth.adapter_client.register_callback_observer(name, observer)
                    await wait_sink
                else:
                    logging.info(f'WaitSink not isbonded')
                    wait_bond = asyncio.get_running_loop().create_future()
                    observer = self.PairingObserver(
                        self.bluetooth.adapter_client,
                        self.security,
                        {
                            'wait_bond': wait_bond,
                            'address': address
                        }
                    )
                    name = utils.create_observer_name(observer)
                    self.bluetooth.adapter_client.register_callback_observer(name, observer)
                    success, reason = await wait_bond
                    if not success:
                        raise RuntimeError(f'Failed to connect to the {address}. Reason: {reason}')
            finally:
                self.bluetooth.adapter_client.unregister_callback_observer(name, observer)

        time.sleep(2)
        cookie = utils.address_to(address)
        logging.info(cookie)
        return a2dp_pb2.WaitSinkResponse(sink=a2dp_pb2.Sink(cookie=cookie))

    async def IsSuspended(self, request: a2dp_pb2.IsSuspendedRequest,
                          context: grpc.ServicerContext) -> wrappers_pb2.BoolValue:

        address = utils.address_from(request.target.cookie)
        if not self.bluetooth.is_connected(address):
            raise RuntimeError('A2dp device is not connected, cannot get suspend state')

        is_suspended = cras_utils.get_active_stream_count() == 0
        logging.info(f'IsSuspended: is_suspended {is_suspended}')
        return wrappers_pb2.BoolValue(value=is_suspended)

    async def Start(self, request: a2dp_pb2.StartRequest,
                    context: grpc.ServicerContext) -> a2dp_pb2.StartResponse:

        audio_data = json.dumps(audio_utils.a2dp_test_data)
        audio_data = json.loads(audio_data)
        logging.info(f'Start: audio_data {audio_data}')

        target = request.WhichOneof('target')
        logging.info(f'Start target: {target}')

        try:
            if request.HasField('source'):
                address = utils.address_from(request.source.cookie)
                logging.info(f'request.source: {request.source}')
                logging.info(f'request.source.cookie: {request.source.cookie}')
                if not self.bluetooth.is_connected(address):
                    raise RuntimeError('A2dp device is not connected, cannot start')

                audio_utils.select_audio_output_node()
                self._cras_test_client.start_playing_subprocess(
                    audio_data['file'],
                    channels=audio_data['channels'],
                    rate=audio_data['rate'],
                    duration=audio_data['duration']
                )
            elif request.HasField('sink'):
                logging.info('Start sink')
                address = utils.address_from(request.sink.cookie)
                logging.info(f'Start sink address : {address}')
                if not self.bluetooth.is_connected(address):
                    raise RuntimeError('A2dp device is not connected, cannot start')

                self._cras_test_client.start_capturing_subprocess(
                    audio_data['recorded_by_sink'],
                    sample_format=audio_data['format'],
                    channels=audio_data['channels'],
                    rate=audio_data['rate'],
                    duration=audio_data['duration']
                )
            else:
                raise ValueError(f'Invalid target type.')
        except Exception as e:
            raise RuntimeError(f'Failed to start subprocess: {e}')

        return a2dp_pb2.StartResponse(started=empty_pb2.Empty())

    async def Suspend(self, request: a2dp_pb2.SuspendRequest,
                      context: grpc.ServicerContext) -> a2dp_pb2.SuspendResponse:

        target = request.WhichOneof('target')
        address = utils.address_from(request.target.cookie)
        if not self.bluetooth.is_connected(address):
            raise RuntimeError('A2dp device is not connected, cannot suspend')

        if cras_utils.get_active_stream_count() == 0:
            raise RuntimeError('Device is already suspended, cannot suspend')

        try:
            if target == 'source':
                self._cras_test_client.stop_playing_subprocess()
            elif target == 'sink':
                self._cras_test_client.stop_capturing_subprocess()
            else:
                raise ValueError(f'Invalid target type: {target}.')
        except Exception as e:
            raise RuntimeError(f'Failed to stop {target} subprocess: {e}')

        return a2dp_pb2.SuspendResponse(suspended=empty_pb2.Empty())

    async def Close(self, request: a2dp_pb2.CloseRequest,
                    context: grpc.ServicerContext) -> a2dp_pb2.CloseResponse:

        class ConnectionObserver(adapter_client.BluetoothConnectionCallbacks):
            """Observer to observe the a2dp device connection state."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_device_disconnected(self, remote_device):
                logging.info('Close on_device_disconnected')
                address, _ = remote_device
                if address != self.task['address']:
                    return

                future = self.task['close_stream']
                future.get_loop().call_soon_threadsafe(future.set_result, True)

        address = utils.address_from(request.target.cookie)
        if not self.bluetooth.is_connected(address):
            raise RuntimeError('A2dp device is not connected, cannot close')
        logging.info(f'Close address: {address}')
        try:
            close_stream = asyncio.get_running_loop().create_future()
            observer = ConnectionObserver({'close_stream': close_stream, 'address': address})
            name = utils.create_observer_name(observer)
            self.bluetooth.adapter_client.register_callback_observer(name, observer)
            self.bluetooth.disconnect_device(address)
            success = await close_stream
            if not success:
                raise RuntimeError(f'Failed to disconnect the address: {address}.')
        finally:
            self.bluetooth.adapter_client.unregister_callback_observer(name, observer)
        return a2dp_pb2.CloseResponse()

    async def GetAudioEncoding(self, request: a2dp_pb2.GetAudioEncodingRequest,
                               context: grpc.ServicerContext) -> a2dp_pb2.GetAudioEncodingResponse:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)  # type: ignore
        context.set_details('Method not implemented!')  # type: ignore
        raise NotImplementedError('Method not implemented!')

    async def PlaybackAudio(self, request: AsyncIterator[a2dp_pb2.PlaybackAudioRequest],
                            context: grpc.ServicerContext) -> a2dp_pb2.PlaybackAudioResponse:

        audio_signals = request
        audio_signal_id = self.audio_signals_count
        self.audio_signals_count = self.audio_signals_count + 1

        logging.info('PlaybackAudio[%s]: Wait for audio signal...', audio_signal_id)
        audio_signal = await utils.anext(audio_signals)
        logging.info(f'audio_signal: {audio_signal}')
        logging.info(f'data: {audio_signal.data}')

        source = audio_signal.source
        data = audio_signal.data

        if cras_utils.get_active_stream_count() == 0:
            raise RuntimeError('Audio track is not started')

        try:
            self._cras_test_client.play(data)
        except Exception as e:
            logging.info(e)
            raise RuntimeError(f'PlaybackAudio failed: {e}')

        return a2dp_pb2.PlaybackAudioResponse()

    async def CaptureAudio(self, request: a2dp_pb2.CaptureAudioRequest,
                           context: grpc.ServicerContext) -> AsyncGenerator[a2dp_pb2.CaptureAudioResponse, None]:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)  # type: ignore
        context.set_details('Method not implemented!')  # type: ignore
        raise NotImplementedError('Method not implemented!')
