import asyncio
import time
from typing import AsyncGenerator
from typing import AsyncIterator

from floss.pandora.floss import adapter_client
from floss.pandora.floss import media_client
from floss.pandora.floss import utils
from floss.pandora.floss import floss_enums
from floss.pandora.floss import audio_utils
from floss.pandora.floss import cras_utils
from floss.pandora.server import bluetooth as bluetooth_module
from google.protobuf import wrappers_pb2, empty_pb2
import grpc
import json
import logging
from pandora import a2dp_grpc_aio
from pandora import a2dp_pb2
from pandora import security_grpc_aio

class A2DPService(a2dp_grpc_aio.A2DPServicer):
    """Service to trigger Bluetooth A2DP procedures.

    This class implements the Pandora bluetooth test interfaces,
    where the meta class definition is automatically generated by the protobuf.
    The interface definition can be found in:
    https://cs.android.com/android/platform/superproject/+/main:external
    /pandora/bt-test-interfaces/pandora/a2dp.proto
    """

    def __init__(self, bluetooth: bluetooth_module.Bluetooth, security: security_grpc_aio.SecurityServicer):
        self.bluetooth = bluetooth
        self.security = security
        self.audio_signals_count = 0
        self._cras_test_client = cras_utils.CrasTestClient()
        cras_utils.set_floss_enabled(True)

    async def OpenSource(self, request: a2dp_pb2.OpenSourceRequest,
                         context: grpc.ServicerContext) -> a2dp_pb2.OpenSourceResponse:

        class ConnectionObserver(media_client.BluetoothMediaCallbacks):
            """Observer to observe the a2dp profile connection state."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_bluetooth_audio_device_added(self, remote_device):
                logging.info(f'OpenSource on_bluetooth_audio_device_added, {remote_device}')
                if remote_device['address'] != self.task['address']:
                    return

                future = self.task['open_source']
                future.get_loop().call_soon_threadsafe(future.set_result, address)

        connection = utils.connection_from(request.connection)
        address = connection.address

        connected_devices = self.bluetooth.get_connected_audio_devices()
        logging.info(f'OpenSource: connected {self.bluetooth.is_connected(address)}')
        logging.info(f'OpenSource connected_devices: {connected_devices}')

        if not self.bluetooth.is_connected(address) or address not in connected_devices:
            try:
                open_source = asyncio.get_running_loop().create_future()
                observer = ConnectionObserver({'open_source': open_source, 'address': address})
                name = utils.create_observer_name(observer)
                self.bluetooth.media_client.register_callback_observer(name, observer)
                self.bluetooth.connect_device(address)
                success = await asyncio.wait_for(open_source, timeout=10)

                if not success:
                    raise RuntimeError(f'Failed to connect to the address {address}.')
            except asyncio.TimeoutError as e:
                print(f'OpenSource: timeout for waiting a2dp connection. {e}')
                logging.error(f'OpenSource: timeout for waiting a2dp connection. {e}')
            finally:
                self.bluetooth.media_client.unregister_callback_observer(name, observer)

        time.sleep(2)
        cookie = utils.address_to(address)
        logging.info(f'OpenSource: cookie {cookie}')
        return a2dp_pb2.OpenSourceResponse(source=a2dp_pb2.Source(cookie=cookie))

    async def OpenSink(self, request: a2dp_pb2.OpenSinkRequest,
                       context: grpc.ServicerContext) -> a2dp_pb2.OpenSinkResponse:

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)  # type: ignore
        context.set_details('Method not implemented!')  # type: ignore
        raise NotImplementedError('Method not implemented!')

    async def WaitSource(self, request: a2dp_pb2.WaitSourceRequest,
                         context: grpc.ServicerContext) -> a2dp_pb2.WaitSourceResponse:

        class ConnectionObserver(media_client.BluetoothMediaCallbacks):
            """Observer to observe the a2dp profile connection state."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_bluetooth_audio_device_added(self, remote_device):
                print(f'WaitSource on_bluetooth_audio_device_added, {remote_device}')
                logging.info(f'WaitSource on_bluetooth_audio_device_added, {remote_device}')
                if remote_device['address'] != self.task['address']:
                    return

                future = self.task['wait_source']
                future.get_loop().call_soon_threadsafe(future.set_result, address)

        connection = utils.connection_from(request.connection)
        address = connection.address

        if not address:
            raise ValueError('Request address field must be set.')

        connected_devices = self.bluetooth.get_connected_audio_devices()
        logging.info(f'WaitSource {self.bluetooth.is_connected(address)} {address}')
        logging.info(f'WaitSource connected_devices: {connected_devices}')
        print(f'WaitSource {self.bluetooth.is_connected(address)} {address}')
        print(f'WaitSource connected_devices: {connected_devices}')
        if not self.bluetooth.is_connected(address) or address not in connected_devices:
            try:
                wait_source = asyncio.get_running_loop().create_future()
                observer = ConnectionObserver({'wait_source': wait_source, 'address': address})
                name = utils.create_observer_name(observer)
                self.bluetooth.media_client.register_callback_observer(name, observer)
                await asyncio.wait_for(wait_source, timeout=10)
            except asyncio.TimeoutError as e:
                print(f'WaitSource: timeout for waiting a2dp connection. {e}')
                logging.error(f'WaitSource: timeout for waiting a2dp connection. {e}')
            finally:
                self.bluetooth.media_client.unregister_callback_observer(name, observer)

        time.sleep(2)
        cookie = utils.address_to(address)
        logging.info(cookie)
        print(cookie)
        return a2dp_pb2.WaitSourceResponse(source=a2dp_pb2.Source(cookie=cookie))

    async def WaitSink(self, request: a2dp_pb2.WaitSinkRequest,
                       context: grpc.ServicerContext) -> a2dp_pb2.WaitSinkResponse:

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)  # type: ignore
        context.set_details('Method not implemented!')  # type: ignore
        raise NotImplementedError('Method not implemented!')

    async def IsSuspended(self, request: a2dp_pb2.IsSuspendedRequest,
                          context: grpc.ServicerContext) -> wrappers_pb2.BoolValue:

        address = utils.address_from(request.target.cookie)
        connected_audio_devices = self.bluetooth.get_connected_audio_devices()
        if address not in connected_audio_devices:
            raise RuntimeError('A2dp device is not connected, cannot get suspend state')

        is_suspended = cras_utils.get_active_stream_count() == 0
        logging.info(f'IsSuspended: is_suspended {is_suspended}')
        return wrappers_pb2.BoolValue(value=is_suspended)

    async def Start(self, request: a2dp_pb2.StartRequest,
                    context: grpc.ServicerContext) -> a2dp_pb2.StartResponse:

        target = request.WhichOneof('target')
        logging.info(f'start target: {target}')
        address = utils.address_from(request.target.cookie)
        connected_audio_devices = self.bluetooth.get_connected_audio_devices()
        if address not in connected_audio_devices:
            raise RuntimeError('A2dp device is not connected, cannot start')

        audio_data = json.dumps(audio_utils.a2dp_test_data)
        audio_data = json.loads(audio_data)
        logging.info(f'Start: audio_data {audio_data}')

        time.sleep(2)
        audio_utils.select_audio_output_node()

        try:
            if target == 'source':
                logging.info('Start source')
                self._cras_test_client.start_playing_subprocess(
                    audio_data['file'],
                    channels=audio_data['channels'],
                    rate=audio_data['rate'],
                    duration=audio_data['duration']
                )
            else:
                raise ValueError(f'Invalid target type: {target}.')
        except Exception as e:
            raise RuntimeError(f'Failed to start {target} subprocess: {e}')

        return a2dp_pb2.StartResponse(started=empty_pb2.Empty())

    async def Suspend(self, request: a2dp_pb2.SuspendRequest,
                      context: grpc.ServicerContext) -> a2dp_pb2.SuspendResponse:

        target = request.WhichOneof('target')
        address = utils.address_from(request.target.cookie)
        connected_audio_devices = self.bluetooth.get_connected_audio_devices()
        if address not in connected_audio_devices:
            raise RuntimeError('A2dp device is not connected, cannot suspend')

        if cras_utils.get_active_stream_count() == 0:
            raise RuntimeError('A2dp Device is already suspended, cannot suspend')

        logging.info(f'cras_utils.get_active_stream_count(): {cras_utils.get_active_stream_count()}')
        try:
            if target == 'source':
                logging.info('Suspend source')
                self._cras_test_client.stop_playing_subprocess()
            else:
                raise ValueError(f'Invalid target type: {target}.')
        except Exception as e:
            raise RuntimeError(f'Failed to stop {target} subprocess: {e}')

        return a2dp_pb2.SuspendResponse(suspended=empty_pb2.Empty())

    async def Close(self, request: a2dp_pb2.CloseRequest,
                    context: grpc.ServicerContext) -> a2dp_pb2.CloseResponse:

        class ConnectionObserver(media_client.BluetoothMediaCallbacks):
            """Observer to observe the a2dp profile connection state."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_bluetooth_audio_device_removed(self, address):
                logging.info('on_bluetooth_audio_device_removed')
                logging.info(address)
                if address != self.task['address']:
                    return

                future = self.task['close_stream']
                future.get_loop().call_soon_threadsafe(future.set_result, True)

        address = utils.address_from(request.target.cookie)
        connected_audio_devices = self.bluetooth.get_connected_audio_devices()
        logging.info(f'Close connected_audio_devices: {connected_audio_devices}')
        if address not in connected_audio_devices:
            raise RuntimeError('A2dp device is not connected, cannot close')

        try:
            close_stream = asyncio.get_running_loop().create_future()
            observer = ConnectionObserver({'close_stream': close_stream, 'address': address})
            name = utils.create_observer_name(observer)
            self.bluetooth.media_client.register_callback_observer(name, observer)
            self.bluetooth.media_disconnect(address)
            success = await close_stream
            if not success:
                raise RuntimeError(f'Failed to disconnect the address: {address}.')
        finally:
            self.bluetooth.media_client.unregister_callback_observer(name, observer)
        return a2dp_pb2.CloseResponse()

    async def GetAudioEncoding(self, request: a2dp_pb2.GetAudioEncodingRequest,
                               context: grpc.ServicerContext) -> a2dp_pb2.GetAudioEncodingResponse:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)  # type: ignore
        context.set_details('Method not implemented!')  # type: ignore
        raise NotImplementedError('Method not implemented!')

    async def PlaybackAudio(self, request: AsyncIterator[a2dp_pb2.PlaybackAudioRequest],
                            context: grpc.ServicerContext) -> a2dp_pb2.PlaybackAudioResponse:

        audio_signals = request
        audio_signal_id = self.audio_signals_count
        self.audio_signals_count = self.audio_signals_count + 1

        logging.info('PlaybackAudio[%s]: Wait for audio signal...', audio_signal_id)
        audio_signal = await utils.anext(audio_signals)
        logging.info(f'audio_signal: {audio_signal}')
        logging.info(f'data: {audio_signal.data}')

        source = audio_signal.source
        data = audio_signal.data

        if cras_utils.get_active_stream_count() == 0:
            raise RuntimeError('Audio track is not started')

        try:
            self._cras_test_client.play(data)
        except Exception as e:
            print(e)
            raise RuntimeError(f'PlaybackAudio failed: {e}')

        return a2dp_pb2.PlaybackAudioResponse()

    async def CaptureAudio(self, request: a2dp_pb2.CaptureAudioRequest,
                           context: grpc.ServicerContext) -> AsyncGenerator[a2dp_pb2.CaptureAudioResponse, None]:
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)  # type: ignore
        context.set_details('Method not implemented!')  # type: ignore
        raise NotImplementedError('Method not implemented!')
