# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""L2CAP grpc interface."""

import asyncio
import logging
import socket

from floss.pandora.floss import floss_enums
from floss.pandora.floss import socket_manager
from floss.pandora.floss import utils
from floss.pandora.server import bluetooth as bluetooth_module
from google.protobuf import empty_pb2
import grpc
from pandora_experimental import l2cap_grpc_aio
from pandora_experimental import l2cap_pb2


class L2CAPService(l2cap_grpc_aio.L2CAPServicer):
    """Service to trigger Bluetooth L2CAP procedures.

    This class implements the Pandora bluetooth test interfaces,
    where the meta class definition is automatically generated by the protobuf.
    The interface definition can be found in:
    https://cs.android.com/android/platform/superproject/main/+/main:packages/modules/Bluetooth/pandora/interfaces/pandora_experimental/l2cap.proto
    """

    def __init__(self, bluetooth: bluetooth_module.Bluetooth):
        self.bluetooth = bluetooth
        self.connection_server_socket = dict()
        self.connection_stream = dict()
        self.BUFFER_SIZE = 512

    async def ListenL2CAPChannel(self, request: l2cap_pb2.ListenL2CAPChannelRequest,
                                 context: grpc.ServicerContext) -> l2cap_pb2.ListenL2CAPChannelResponse:

        class ListenL2CAPObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe listen on the L2CAP channel."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_incoming_socket_ready(self, socket, status):
                if socket and 'id' in socket:
                    socket_id = socket['id']

                if socket_id != self.task['socket_id']:
                    return

                if status is None or floss_enums.BtStatus(status) != floss_enums.BtStatus.SUCCESS:
                    logging.error('Failed to listen on the L2CAP channel. Status: %s', status)

                future = self.task['listen_l2cap_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, socket)

        try:
            if not request.secure:
                channel_type = 'insecure'
                socket_result = self.bluetooth.listen_using_insecure_l2cap_channel()
            else:
                channel_type = 'secure'
                socket_result = self.bluetooth.listen_using_l2cap_channel()

            if socket_result is None:
                raise RuntimeError(f'Failed to call listen_using_{channel_type}_l2cap_channel.')

            l2cap_channel_listener = {
                'listen_l2cap_channel': asyncio.get_running_loop().create_future(),
                'socket_id': socket_result['id']
            }
            observer = ListenL2CAPObserver(l2cap_channel_listener)
            name = utils.create_observer_name(observer)
            self.bluetooth.socket_manager.register_callback_observer(name, observer)
            socket = await asyncio.wait_for(l2cap_channel_listener['listen_l2cap_channel'], timeout=5)
            self.connection_server_socket[request.connection.cookie.value] = socket
        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return empty_pb2.Empty()

    async def CreateLECreditBasedChannel(self, request: l2cap_pb2.CreateLECreditBasedChannelRequest,
                                         context: grpc.ServicerContext) -> l2cap_pb2.CreateLECreditBasedChannelResponse:

        class CreateL2CAPObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe creates L2CAP channel."""

            def __init__(self, client: socket_manager, task):
                self.client = client
                self.task = task

            @utils.glib_callback()
            def on_outgoing_connection_result(self, connecting_id, result, socket, *, dbus_unix_fd_list=None):
                if connecting_id != self.task['connecting_id']:
                    return

                if result is None or floss_enums.BtStatus(result) != floss_enums.BtStatus.SUCCESS:
                    logging.error('Failed to create the L2CAP channel. Status: %s', result)

                socket_info = self.client.connecting_sockets.get(connecting_id)
                if socket_info is None:
                    logging.error('Connecting_id: %s not found in connecting_sockets: %s', connecting_id,
                                  self.client.connecting_sockets)
                    return

                _, _, fd = socket_info
                future = self.task['create_l2cap_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, fd)

        connection_value = request.connection.cookie.value
        address = utils.address_from(connection_value)
        try:
            if not request.secure:
                channel_type = 'insecure'
                socket_result = self.bluetooth.create_insecure_l2cap_channel(address, request.psm)
            else:
                channel_type = 'secure'
                socket_result = self.bluetooth.create_l2cap_channel(address, request.psm)

            if socket_result is None:
                raise RuntimeError(f'Failed to call create_{channel_type}_l2cap_channel.')

            l2cap_channel_creation = {
                'create_l2cap_channel': asyncio.get_running_loop().create_future(),
                'connecting_id': socket_result['id']
            }
            observer = CreateL2CAPObserver(self.bluetooth.socket_manager, l2cap_channel_creation)
            name = utils.create_observer_name(observer)
            self.bluetooth.socket_manager.register_callback_observer(name, observer)
            fd = await asyncio.wait_for(l2cap_channel_creation['create_l2cap_channel'], timeout=5)
            client_socket = socket.fromfd(fd, socket.AF_UNIX, socket.SOCK_STREAM)
            self.connection_stream[connection_value] = client_socket
        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return empty_pb2.Empty()

    async def AcceptL2CAPChannel(self, request: l2cap_pb2.AcceptL2CAPChannelRequest,
                                 context: grpc.ServicerContext) -> l2cap_pb2.AcceptL2CAPChannelResponse:

        class AcceptL2CAPObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe the accept L2CAP channel."""

            def __init__(self, client: socket_manager, task):
                self.client = client
                self.task = task

            @utils.glib_callback()
            def on_handle_incoming_connection(self, listener_id, connection, *, dbus_unix_fd_list=None):
                if listener_id != self.task['listener_id']:
                    return

                connections_info = self.client.listening_sockets.get(listener_id, ([], None))[1]
                if connections_info is None:
                    logging.error('Listener id: %s not found in listening sockets: %s', listener_id,
                                  self.client.listening_sockets)
                    return

                _, fd = connections_info[0]
                future = self.task['accept_l2cap_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, fd)

        connection_value = request.connection.cookie.value
        try:
            if connection_value in self.connection_server_socket:
                socket_result = self.connection_server_socket.get(connection_value)
                if socket_result is None:
                    raise ValueError(
                        f'Socket_result: {socket_result} not found for the connection_value: {connection_value}.')

                socket_id = socket_result['id']
                l2cap_channel_acceptance = {
                    'accept_l2cap_channel': asyncio.get_running_loop().create_future(),
                    'listener_id': socket_id
                }
                observer = AcceptL2CAPObserver(self.bluetooth.socket_manager, l2cap_channel_acceptance)
                name = utils.create_observer_name(observer)
                self.bluetooth.socket_manager.register_callback_observer(name, observer)

                accept_socket_status = self.bluetooth.accept(socket_id, timeout_ms=5)
                if accept_socket_status != floss_enums.BtStatus.SUCCESS:
                    raise RuntimeError(f'Failed to accept the L2CAP socket. Status: {accept_socket_status}.')

                fd = await asyncio.wait_for(l2cap_channel_acceptance['accept_l2cap_channel'], timeout=5)
                server_socket = socket.fromfd(fd, socket.AF_UNIX, socket.SOCK_STREAM)
                self.connection_stream[connection_value] = server_socket
        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return empty_pb2.Empty()

    async def SendData(self, request: l2cap_pb2.SendDataRequest,
                       context: grpc.ServicerContext) -> l2cap_pb2.SendDataResponse:
        connection_value = request.connection.cookie.value
        output_stream = self.connection_stream.get(connection_value)
        if output_stream:
            try:
                output_stream.send(request.data)
            except Exception as e:
                logging.error('Exception during writing to output stream: %s', e)
        else:
            logging.error('Output stream: %s not found for the connection_value: %s', output_stream, connection_value)

        return empty_pb2.Empty()

    async def ReceiveData(self, request: l2cap_pb2.ReceiveDataRequest,
                          context: grpc.ServicerContext) -> l2cap_pb2.ReceiveDataResponse:
        connection_value = request.connection.cookie.value
        input_stream = self.connection_stream.get(connection_value)
        if input_stream:
            try:
                data = input_stream.recv(self.BUFFER_SIZE)

                if data:
                    return l2cap_pb2.ReceiveDataResponse(data=bytes(data))
            except Exception as e:
                logging.error('Exception during reading from input stream: %s', e)
        else:
            logging.error('Input stream: %s not found for the connection_value: %s', input_stream, connection_value)

        # Return an empty byte array or an error response.
        return l2cap_pb2.ReceiveDataResponse(data=b"")
