# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""L2CAP grpc interface."""

import asyncio
import logging

from floss.pandora.floss import socket_manager
from floss.pandora.floss import floss_enums
from floss.pandora.floss import utils
from floss.pandora.server import bluetooth as bluetooth_module
import grpc
import socket

from pandora_experimental import l2cap_grpc_aio
from pandora_experimental import l2cap_pb2
from google.protobuf import empty_pb2


class L2CAPService(l2cap_grpc_aio.L2CAPServicer):
    """Service to trigger Bluetooth L2CAP procedures.

    This class implements the Pandora bluetooth test interfaces,
    where the meta class definition is automatically generated by the protobuf.
    The interface definition can be found in:
    https://cs.android.com/android/platform/superproject/+/main:external
    /pandora/bt-test-interfaces/pandora/l2cap.proto
    """

    def __init__(self, server: grpc.aio.Server, bluetooth: bluetooth_module.Bluetooth):
        self.server = server
        self.bluetooth = bluetooth
        self.connection_server_socket = dict()
        self.connection_in_stream = dict()
        self.connection_out_stream = dict()

    async def ListenL2CAPChannel(self, request: l2cap_pb2.ListenL2CAPChannelRequest,
                                 context: grpc.ServicerContext) -> l2cap_pb2.ListenL2CAPChannelResponse:

        class ListenL2CAPObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe the listen L2CAP channel."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_incoming_socket_ready(self, socket, status):
                print("hiiiiii")
                if socket and 'id' in socket:
                    print("ooooooooo")
                    print(socket)
                    socket_id = socket['id']

                if status is None or floss_enums.BtStatus(status) != floss_enums.BtStatus.SUCCESS:
                    logging.error('Failed to listen L2CAP channel.')
                    socket_id = None
                    print("jjjjjjjjjjj")

                future = self.task['listen_l2cap_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, socket_id)

        try:
            print("rajaa")
            listen_l2cap_channel = asyncio.get_running_loop().create_future()
            observer = ListenL2CAPObserver({'listen_l2cap_channel': listen_l2cap_channel})
            name = utils.create_observer_name(observer)
            self.bluetooth.socket_manager.register_callback_observer(name, observer)
            print("rajaa2")

            if not request.secure:
                socket_result = self.bluetooth.listen_using_insecure_l2cap_channel()
                print("uuuuuu")
                print(socket_result)
            else:
                socket_result = self.bluetooth.listen_using_l2cap_channel()

            print("kkkkkkkkkkkk")
            socket_id = await asyncio.wait_for(listen_l2cap_channel, timeout=5)
            if socket_id != socket_result['id']:
                raise RuntimeError("Failed to listen the correct L2CAP channel.")
            self.connection_server_socket[request.connection.cookie.value] = socket_result

        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return empty_pb2.Empty()

    async def CreateLECreditBasedChannel(self, request: l2cap_pb2.CreateLECreditBasedChannelRequest,
                                         context: grpc.ServicerContext) -> l2cap_pb2.CreateLECreditBasedChannelResponse:

        class CreateL2CAPObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe create L2CAP channel."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_outgoing_connection_result(self, connecting_id, result, socket):

                if result is None or floss_enums.BtStatus(result) != floss_enums.BtStatus.SUCCESS:
                    logging.error('Failed to create L2CAP channel.')

                future = self.task['create_l2cap_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, (connecting_id, socket))

        address = utils.address_from(request.connection.cookie.value)

        try:
            create_l2cap_channel = asyncio.get_running_loop().create_future()
            observer = CreateL2CAPObserver({'create_l2cap_channel': create_l2cap_channel})
            name = utils.create_observer_name(observer)
            self.bluetooth.socket_manager.register_callback_observer(name, observer)

            if not request.secure:
                socket_result = self.bluetooth.create_insecure_l2cap_channel(address, request.psm)
            else:
                socket_result = self.bluetooth.create_l2cap_channel(address, request.psm)

            socket_id, bluetooth_socket = await asyncio.wait_for(create_l2cap_channel, timeout=5)

            if socket_id != socket_result['id']:
                raise RuntimeError("Failed to create the correct L2CAP channel")

            if bluetooth_socket is not None and 'optional_value' in bluetooth_socket and 'fd' in bluetooth_socket[
                    'optional_value'] and 'optional_value' in bluetooth_socket['optional_value']['fd']:

                file_descriptor_info = bluetooth_socket['optional_value']['fd']['optional_value']
                if file_descriptor_info == 0:
                    logging.error("The file descriptor is not valid or not open")
                else:

                    server_socket = socket.fromfd(file_descriptor_info["inode"], file_descriptor_info["address family"],
                                                  socket.SOCK_STREAM)
                    # server_socket.connect()
                    self.connection_in_stream[request.connection.cookie.value] = server_socket.makefile('rb')
                    self.connection_out_stream[request.connection.cookie.value] = server_socket.makefile('wb')

            else:
                logging.error("The 'fd' attribute or 'optional_value' attribute is missing")

        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return empty_pb2.Empty()

    async def AcceptL2CAPChannel(self, request: l2cap_pb2.AcceptL2CAPChannelRequest,
                                 context: grpc.ServicerContext) -> l2cap_pb2.AcceptL2CAPChannelResponse:

        class AcceptL2CAPObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe the accept L2CAP channel."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_handle_incoming_connection(self, listener_id, connection, *, dbus_unix_fd_list=None):
                future = self.task['accept_l2cap_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, (listener_id, connection))

                print("rajaa dbus unix")
                print(dbus_unix_fd_list)
                print("rajaa dbus unix")

        try:
            print("accept11111")
            accept_l2cap_channel = asyncio.get_running_loop().create_future()
            observer = AcceptL2CAPObserver({'accept_l2cap_channel': accept_l2cap_channel})
            name = utils.create_observer_name(observer)
            self.bluetooth.socket_manager.register_callback_observer(name, observer)

            print("accept22222")

            socket_result = self.connection_server_socket[request.connection.cookie.value]
            print("socket_result")
            print(socket_result)
            print("socket_result")
            socket_id = socket_result['id']

            accept_socket_status = self.bluetooth.accept(socket_id, 5)

            print("accept_socket_status")
            print(accept_socket_status)
            print("accept_socket_status")

            if floss_enums.BtStatus(accept_socket_status) != floss_enums.BtStatus.SUCCESS:
                print("failed accept")
                raise RuntimeError("Failed to accept the L2cap socket")

            listener_id, socket_connection = await asyncio.wait_for(accept_l2cap_channel, timeout=10)
            print("kkkkkkkkkkk")
            print(socket_connection)
            print("kkkkkkkkkkk")
            if listener_id != socket_id:
                raise RuntimeError("Failed to listen the correct L2CAP channel.")

            if 'fd' in socket_connection and 'optional_value' in socket_connection['fd']:
                file_descriptor_info = socket_connection['fd']['optional_value']
                if file_descriptor_info == 0:
                    logging.error("The file descriptor is not valid or not open")

                else:
                    client_socket = socket.fromfd(file_descriptor_info["inode"], file_descriptor_info["address family"],
                                                  socket.SOCK_STREAM)
                    self.connection_in_stream[request.connection.cookie.value] = client_socket.makefile('rb')
                    self.connection_out_stream[request.connection.cookie.value] = client_socket.makefile('wb')
            else:
                logging.error("The 'fd' attribute or 'optional_value' attribute is missing")

        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return empty_pb2.Empty()

    async def sendData(self, request: l2cap_pb2.SendDataRequest,
                       context: grpc.ServicerContext) -> l2cap_pb2.SendDataResponse:

        output_stream = self.connection_out_stream.get(request.connection.cookie.value)
        if output_stream:
            try:
                output_stream.write(request.data)
                output_stream.flush()

            except Exception as e:
                logging.error("Exception during writing to sendDataPacket output stream", e)
        else:
            logging.error("Output stream not found for the connection")

        return empty_pb2.Empty()

    async def receiveData(self, request: l2cap_pb2.ReceiveDataRequest,
                          context: grpc.ServicerContext) -> l2cap_pb2.ReceiveDataResponse:
        BUFFER_SIZE = 512

        input_stream = self.connection_in_stream.get(request.connection.cookie.value)
        if input_stream:
            try:
                data = input_stream.read(BUFFER_SIZE)
                if data:
                    return l2cap_pb2.ReceiveDataResponse(data=data)
            except Exception as e:
                logging.error("Exception during reading from input stream", e)
        else:
            logging.error("Input stream not found for the connection")
        # Return an empty byte array or an error response
        return l2cap_pb2.ReceiveDataResponse(data=b"")
