# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""L2CAP grpc interface."""

import asyncio
import logging
import socket

from floss.pandora.floss import floss_enums
from floss.pandora.floss import socket_manager
from floss.pandora.floss import utils
from floss.pandora.server import bluetooth as bluetooth_module
from google.protobuf import empty_pb2
import grpc
from pandora_experimental import l2cap_grpc_aio
from pandora_experimental import l2cap_pb2


class L2CAPService(l2cap_grpc_aio.L2CAPServicer):
    """Service to trigger Bluetooth L2CAP procedures.

    This class implements the Pandora bluetooth test interfaces,
    where the meta class definition is automatically generated by the protobuf.
    The interface definition can be found in:
    https://cs.android.com/android/platform/superproject/main/+/main:packages/modules/Bluetooth/pandora/interfaces/pandora_experimental/l2cap.proto
    """

    def __init__(self, bluetooth: bluetooth_module.Bluetooth):
        self.bluetooth = bluetooth
        self.connection_server_socket = dict()
        self.connection_stream = dict()
        self.BUFFER_SIZE = 512

    async def ListenL2CAPChannel(self, request: l2cap_pb2.ListenL2CAPChannelRequest,
                                 context: grpc.ServicerContext) -> l2cap_pb2.ListenL2CAPChannelResponse:

        class ListenL2CAPObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe the listen L2CAP channel."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_incoming_socket_ready(self, socket, status):
                if socket and 'id' in socket:
                    socket_id = socket['id']

                if status is None or floss_enums.BtStatus(status) != floss_enums.BtStatus.SUCCESS:
                    logging.error('Failed to listen L2CAP channel. Status: %s', status)
                    socket_id = None

                future = self.task['listen_l2cap_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, socket_id)

        try:
            listen_l2cap_channel = asyncio.get_running_loop().create_future()
            observer = ListenL2CAPObserver({'listen_l2cap_channel': listen_l2cap_channel})
            name = utils.create_observer_name(observer)
            self.bluetooth.socket_manager.register_callback_observer(name, observer)

            if not request.secure:
                socket_result = self.bluetooth.listen_using_insecure_l2cap_channel()
            else:
                socket_result = self.bluetooth.listen_using_l2cap_channel()

            socket_id = await asyncio.wait_for(listen_l2cap_channel, timeout=5)
            if socket_id != socket_result['id']:
                raise RuntimeError(f'Failed to listen to the L2CAP channel with socket_id: {socket_id}.')
            self.connection_server_socket[request.connection.cookie.value] = socket_result

        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return empty_pb2.Empty()

    async def CreateLECreditBasedChannel(self, request: l2cap_pb2.CreateLECreditBasedChannelRequest,
                                         context: grpc.ServicerContext) -> l2cap_pb2.CreateLECreditBasedChannelResponse:

        class CreateL2CAPObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe create L2CAP channel."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_outgoing_connection_result(self, connecting_id, result, socket, *, dbus_unix_fd_list=None):
                if result is None or floss_enums.BtStatus(result) != floss_enums.BtStatus.SUCCESS:
                    logging.error('Failed to create L2CAP channel. status: %s', result)

                future = self.task['create_l2cap_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, connecting_id)

        address = utils.address_from(request.connection.cookie.value)
        # address ='F0:B6:1E:74:7D:58'
        try:
            create_l2cap_channel = asyncio.get_running_loop().create_future()
            observer = CreateL2CAPObserver({'create_l2cap_channel': create_l2cap_channel})
            name = utils.create_observer_name(observer)
            self.bluetooth.socket_manager.register_callback_observer(name, observer)

            if not request.secure:
                socket_result = self.bluetooth.create_insecure_l2cap_channel(address, request.psm)
            else:
                socket_result = self.bluetooth.create_l2cap_channel(address, request.psm)

            socket_id = await asyncio.wait_for(create_l2cap_channel, timeout=5)
            _, _, fd = self.bluetooth.socket_manager.connecting_sockets[socket_id]

            if socket_id != socket_result['id']:
                raise RuntimeError(f'Failed to create the L2CAP channel with socket_id: {socket_id}.')

            server_socket = socket.fromfd(fd, socket.AF_UNIX, socket.SOCK_STREAM)
            self.connection_stream[request.connection.cookie.value] = server_socket

        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return empty_pb2.Empty()

    async def AcceptL2CAPChannel(self, request: l2cap_pb2.AcceptL2CAPChannelRequest,
                                 context: grpc.ServicerContext) -> l2cap_pb2.AcceptL2CAPChannelResponse:

        class AcceptL2CAPObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe the accept L2CAP channel."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_handle_incoming_connection(self, listener_id, connection, *, dbus_unix_fd_list=None):

                future = self.task['accept_l2cap_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, listener_id)

        try:
            accept_l2cap_channel = asyncio.get_running_loop().create_future()
            observer = AcceptL2CAPObserver({'accept_l2cap_channel': accept_l2cap_channel})
            name = utils.create_observer_name(observer)
            self.bluetooth.socket_manager.register_callback_observer(name, observer)
            socket_result = self.connection_server_socket[request.connection.cookie.value]
            socket_id = socket_result['id']

            accept_socket_status = self.bluetooth.accept(socket_id, 5)

            if floss_enums.BtStatus(accept_socket_status) != floss_enums.BtStatus.SUCCESS:
                raise RuntimeError(f'Failed to accept the L2CAP socket. Status: {accept_socket_status}.')

            listener_id = await asyncio.wait_for(accept_l2cap_channel, timeout=5)
            connections_list = self.bluetooth.socket_manager.listening_sockets[listener_id][1]
            _, fd = connections_list[0]

            if listener_id != socket_id:
                raise RuntimeError(f'Failed to accept the correct L2CAP channel with socket_id: {socket_id}.')

            client_socket = socket.fromfd(fd, socket.AF_UNIX, socket.SOCK_STREAM)
            self.connection_stream[request.connection.cookie.value] = client_socket

        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return empty_pb2.Empty()

    async def SendData(self, request: l2cap_pb2.SendDataRequest,
                       context: grpc.ServicerContext) -> l2cap_pb2.SendDataResponse:

        output_stream = self.connection_stream.get(request.connection.cookie.value)
        if output_stream:
            try:
                output_stream.send(request.data)

            except Exception as e:
                logging.error('Exception during writing to sendDataPacket output stream', e)
        else:
            logging.error('Output stream not found for the connection')

        return empty_pb2.Empty()

    async def ReceiveData(self, request: l2cap_pb2.ReceiveDataRequest,
                          context: grpc.ServicerContext) -> l2cap_pb2.ReceiveDataResponse:
        input_stream = self.connection_stream.get(request.connection.cookie.value)
        if input_stream:
            try:
                data = input_stream.recv(self.BUFFER_SIZE)

                if data:
                    return l2cap_pb2.ReceiveDataResponse(data=bytes(data))
            except Exception as e:
                logging.error('Exception during reading from input stream', e)
        else:
            logging.error('Input stream not found for the connection')

        # Return an empty byte array or an error response
        return l2cap_pb2.ReceiveDataResponse(data=b"")
