# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""RFCOMM grpc interface."""

import asyncio
import logging
import socket
import uuid as uuid_module

from floss.pandora.floss import floss_enums
from floss.pandora.floss import socket_manager
from floss.pandora.floss import utils
from floss.pandora.server import bluetooth as bluetooth_module
from google.protobuf import empty_pb2
import grpc
from pandora_experimental import rfcomm_grpc_aio
from pandora_experimental import rfcomm_pb2


class RFCOMMService(rfcomm_grpc_aio.RFCOMMServicer):
    """Service to trigger Bluetooth RFCOMM procedures.

    This class implements the Pandora bluetooth test interfaces,
    where the meta class definition is automatically generated by the protobuf.
    The interface definition can be found in:
    https://cs.android.com/android/platform/superproject/main/+/main:packages/modules/Bluetooth/pandora/interfaces/pandora_experimental/rfcomm.proto
    """

    def __init__(self, bluetooth: bluetooth_module.Bluetooth):
        self.bluetooth = bluetooth
        self.connection_map = dict()
        self.server_map = dict()
        self.BUFFER_SIZE = 512

    async def ConnectToServer(self, request: rfcomm_pb2.ConnectionRequest,
                              context: grpc.ServicerContext) -> rfcomm_pb2.ConnectionResponse:

        class CreateRFCOMMObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe the connection state."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_outgoing_connection_result(self, connecting_id, result, socket, *, dbus_unix_fd_list=None):

                if result is None or floss_enums.BtStatus(result) != floss_enums.BtStatus.SUCCESS:
                    logging.error('Failed to create RFCOMM channel. status: %s', result)

                future = self.task['create_rfcomm_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, connecting_id)

        if request.address is None:
            raise ValueError('Request address field must be set.')
        address = utils.address_from(request.address)
        # address = 'F0:B6:1E:74:7D:58'

        try:
            create_rfcomm_channel = asyncio.get_running_loop().create_future()
            observer = CreateRFCOMMObserver({'create_rfcomm_channel': create_rfcomm_channel})
            name = utils.create_observer_name(observer)
            self.bluetooth.socket_manager.register_callback_observer(name, observer)
            uuid = list(uuid_module.UUID(request.uuid).bytes)
            socket_result = self.bluetooth.create_insecure_rfcomm_socket_to_service_record(address, uuid)
            if socket_result is None:
                raise RuntimeError('Failed to create_insecure_rfcomm_socket_to_service_record.')

            socket_id = await asyncio.wait_for(create_rfcomm_channel, timeout=5)
            _, _, fd = self.bluetooth.socket_manager.connecting_sockets[socket_id]

            client_socket = socket.fromfd(fd, socket.AF_UNIX, socket.SOCK_STREAM)
            self.connection_map[socket_id] = client_socket

        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return rfcomm_pb2.ConnectionResponse(connection=rfcomm_pb2.RfcommConnection(id=socket_id))

    async def Disconnect(self, request: rfcomm_pb2.DisconnectionRequest,
                         context: grpc.ServicerContext) -> rfcomm_pb2.DisconnectionResponse:

        class CloseRFCOMMSocket(socket_manager.SocketManagerCallbacks):
            """Observer to observe the disconnection state."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_incoming_socket_closed(self, listener_id, reason):

                if reason is None or floss_enums.BtStatus(reason) != floss_enums.BtStatus.SUCCESS:
                    logging.error('Failed to create RFCOMM channel. status: %s', reason)

                future = self.task['close_rfcomm_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, listener_id)

        socket_id = request.connection.id

        try:
            if socket_id in self.connection_map and socket_id in self.bluetooth.socket_manager.listening_sockets:
                print("stop server")
                close_rfcomm_channel = asyncio.get_running_loop().create_future()
                observer = CloseRFCOMMSocket({'close_rfcomm_channel': close_rfcomm_channel})
                name = utils.create_observer_name(observer)
                self.bluetooth.socket_manager.register_callback_observer(name, observer)

                socket_close_status = self.bluetooth.close(socket_id)
                logging.info('socket close status : %s', socket_close_status)

                socket_id = await asyncio.wait_for(close_rfcomm_channel, timeout=5)
                logging.info('connection map : %s', self.connection_map)

                del self.connection_map[socket_id]

        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return empty_pb2.Empty()

    async def StopServer(self, request: rfcomm_pb2.StopServerRequest,
                         context: grpc.ServicerContext) -> rfcomm_pb2.StopServerResponse:

        class StopRFCOMMSocket(socket_manager.SocketManagerCallbacks):
            """Observer to observe the stop RFCOMM connection state."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_incoming_socket_closed(self, listener_id, reason):
                if reason is None or floss_enums.BtStatus(reason) != floss_enums.BtStatus.SUCCESS:
                    logging.error('Failed to create RFCOMM channel. status: %s', reason)

                future = self.task['stop_rfcomm_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, listener_id)

        socket_id = request.server.id

        try:
            if socket_id in self.server_map and socket_id in self.bluetooth.socket_manager.listening_sockets:
                stop_rfcomm_channel = asyncio.get_running_loop().create_future()
                observer = StopRFCOMMSocket({'stop_rfcomm_channel': stop_rfcomm_channel})
                name = utils.create_observer_name(observer)
                self.bluetooth.socket_manager.register_callback_observer(name, observer)

                socket_close_status = self.bluetooth.close(socket_id)
                logging.info('socket close status server: %s', socket_close_status)

                socket_id = await asyncio.wait_for(stop_rfcomm_channel, timeout=5)
                logging.info('server map: %s', self.server_map)
                del self.server_map[socket_id]

        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return empty_pb2.Empty()

    async def StartServer(self, request: rfcomm_pb2.ServerOptions,
                          context: grpc.ServicerContext) -> rfcomm_pb2.StartServerResponse:

        class StartServerObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe the start server."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_incoming_socket_ready(self, socket, status):
                if socket and 'id' in socket:
                    socket_id = socket['id']

                if status is None or floss_enums.BtStatus(status) != floss_enums.BtStatus.SUCCESS:
                    logging.error('Failed to listen RFCOMM channel. Status: %s', status)
                    socket_id = None

                future = self.task['start_rfcomm_server']
                future.get_loop().call_soon_threadsafe(future.set_result, socket_id)

        try:
            start_rfcomm_server = asyncio.get_running_loop().create_future()
            observer = StartServerObserver({'start_rfcomm_server': start_rfcomm_server})
            name = utils.create_observer_name(observer)
            self.bluetooth.socket_manager.register_callback_observer(name, observer)
            uuid = list(uuid_module.UUID(request.uuid).bytes)
            socket_result = self.bluetooth.listen_using_insecure_rfcomm_with_service_record(request.name, uuid)

            socket_id = await asyncio.wait_for(start_rfcomm_server, timeout=5)
            self.server_map[socket_id] = socket_result

        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return rfcomm_pb2.StartServerResponse(server=rfcomm_pb2.ServerId(id=socket_id))

    async def AcceptConnection(self, request: rfcomm_pb2.AcceptConnectionRequest,
                               context: grpc.ServicerContext) -> rfcomm_pb2.AcceptConnectionResponse:

        class AcceptConnectionObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe the accept RFCOMM connection."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_handle_incoming_connection(self, listener_id, connection, *, dbus_unix_fd_list=None):

                future = self.task['accept_rfcomm_connection']
                future.get_loop().call_soon_threadsafe(future.set_result, listener_id)

        try:
            accept_rfcomm_connection = asyncio.get_running_loop().create_future()
            observer = AcceptConnectionObserver({'accept_rfcomm_connection': accept_rfcomm_connection})
            name = utils.create_observer_name(observer)
            self.bluetooth.socket_manager.register_callback_observer(name, observer)
            socket_result = self.server_map[request.server.id]
            socket_id = socket_result['id']

            accept_socket_status = self.bluetooth.accept(socket_id, 5)

            if floss_enums.BtStatus(accept_socket_status) != floss_enums.BtStatus.SUCCESS:
                raise RuntimeError(f'Failed to accept the RFCOMM socket. Status: {accept_socket_status}.')

            listener_id = await asyncio.wait_for(accept_rfcomm_connection, timeout=3)

            connections_list = self.bluetooth.socket_manager.listening_sockets[listener_id][1]
            _, fd = connections_list[0]

            if listener_id != socket_id:
                raise RuntimeError(f'Failed to accept the correct RFCOMM channel with socket_id: {socket_id}.')

            server_socket = socket.fromfd(fd, socket.AF_UNIX, socket.SOCK_STREAM)
            self.connection_map[listener_id] = server_socket

        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return rfcomm_pb2.AcceptConnectionResponse(connection=rfcomm_pb2.RfcommConnection(id=socket_id))

    async def Send(self, request: rfcomm_pb2.TxRequest, context: grpc.ServicerContext) -> rfcomm_pb2.TxResponse:

        output_stream = self.connection_map.get(request.connection.id)
        if output_stream:
            try:
                output_stream.send(request.data)

            except Exception as e:
                logging.error('Exception during writing to sendDataPacket output stream', e)
        else:
            logging.error('Output stream not found for the connection')

        return empty_pb2.Empty()

    async def Receive(self, request: rfcomm_pb2.RxRequest, context: grpc.ServicerContext) -> rfcomm_pb2.RxResponse:
        input_stream = self.connection_map.get(request.connection.id)

        if input_stream:
            try:
                data = input_stream.recv(self.BUFFER_SIZE)

                if data:
                    return rfcomm_pb2.RxResponse(data=bytes(data))
            except Exception as e:
                logging.error('Exception during reading from input stream', e)
        else:
            logging.error('Input stream not found for the connection')

        # Return an empty byte array or an error response
        return rfcomm_pb2.RxResponse(data=b"")
