# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""RFCOMM grpc interface."""

import asyncio
import logging
import socket
import uuid as uuid_module

from floss.pandora.floss import floss_enums
from floss.pandora.floss import socket_manager
from floss.pandora.floss import utils
from floss.pandora.server import bluetooth as bluetooth_module
from google.protobuf import empty_pb2
import grpc
from pandora_experimental import rfcomm_grpc_aio
from pandora_experimental import rfcomm_pb2


class RFCOMMService(rfcomm_grpc_aio.RFCOMMServicer):
    """Service to trigger Bluetooth RFCOMM procedures.

    This class implements the Pandora bluetooth test interfaces,
    where the meta class definition is automatically generated by the protobuf.
    The interface definition can be found in:
    https://cs.android.com/android/platform/superproject/main/+/main:packages/modules/Bluetooth/pandora/interfaces/pandora_experimental/rfcomm.proto
    """

    def __init__(self, bluetooth: bluetooth_module.Bluetooth):
        self.bluetooth = bluetooth
        self.connection_map = dict()
        self.server_map = dict()
        self.BUFFER_SIZE = 512
        self.current_cookie = 0x12FC0

    async def ConnectToServer(self, request: rfcomm_pb2.ConnectionRequest,
                              context: grpc.ServicerContext) -> rfcomm_pb2.ConnectionResponse:

        class CreateRFCOMMObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe the connection state."""

            def __init__(self, client: socket_manager, task):
                self.client = client
                self.task = task

            @utils.glib_callback()
            def on_outgoing_connection_result(self, connecting_id, result, socket, *, dbus_unix_fd_list=None):
                if connecting_id != self.task['connecting_id']:
                    return

                if result is None or floss_enums.BtStatus(result) != floss_enums.BtStatus.SUCCESS:
                    logging.error('Failed to create RFCOMM channel. status: %s', result)

                socket_info = self.client.connecting_sockets.get(connecting_id)
                if socket_info is None:
                    logging.error('connecting id: %s not found in connecting_sockets: %s.', connecting_id,
                                  self.client.connecting_sockets)

                _, _, fd = socket_info
                future = self.task['create_rfcomm_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, fd)

        if request.address is None:
            raise ValueError('Request address field must be set.')
        address = utils.address_from(request.address)
        uuid = list(uuid_module.UUID(request.uuid).bytes)
        try:
            socket_result = self.bluetooth.create_insecure_rfcomm_socket_to_service_record(address, uuid)
            if socket_result is None:
                raise RuntimeError('Failed to call create_insecure_rfcomm_socket_to_service_record.')

            rfcomm_channel_creation = {
                'create_rfcomm_channel': asyncio.get_running_loop().create_future(),
                'connecting_id': socket_result['id']
            }
            observer = CreateRFCOMMObserver(self.bluetooth.socket_manager, rfcomm_channel_creation)
            name = utils.create_observer_name(observer)
            self.bluetooth.socket_manager.register_callback_observer(name, observer)

            fd = await asyncio.wait_for(rfcomm_channel_creation['create_rfcomm_channel'], timeout=5)

            client_socket_id = self.current_cookie
            self.current_cookie += 1

            client_socket = socket.fromfd(fd, socket.AF_UNIX, socket.SOCK_STREAM)
            self.connection_map[client_socket_id] = client_socket
        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return rfcomm_pb2.ConnectionResponse(connection=rfcomm_pb2.RfcommConnection(id=client_socket_id))

    async def Disconnect(self, request: rfcomm_pb2.DisconnectionRequest,
                         context: grpc.ServicerContext) -> rfcomm_pb2.DisconnectionResponse:

        connection_id = request.connection.id
        if connection_id in self.connection_map:
            connection_socket = self.connection_map[connection_id]
            try:
                connection_socket.shutdown(socket.SHUT_RDWR)
                connection_socket.close()
                del self.connection_map[connection_id]
            except asyncio.TimeoutError as e:
                logging.error('Disconnect: asyncio.TimeoutError %s', e)
        else:
            logging.error('Connection_id: %s not found in connection_map: %s', connection_id, self.connection_map)

        return empty_pb2.Empty()

    async def StopServer(self, request: rfcomm_pb2.StopServerRequest,
                         context: grpc.ServicerContext) -> rfcomm_pb2.StopServerResponse:

        class StopRFCOMMSocket(socket_manager.SocketManagerCallbacks):
            """Observer to observe the stop RFCOMM connection state."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_incoming_socket_closed(self, listener_id, reason):
                if listener_id != self.task['listener_id']:
                    return

                if reason is None or floss_enums.BtStatus(reason) != floss_enums.BtStatus.SUCCESS:
                    logging.error('Failed to stop RFCOMM channel. status: %s', reason)

                future = self.task['stop_rfcomm_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, None)

        listener_id = request.server.id
        try:
            if listener_id in self.server_map:
                rfcomm_channel_stop = {
                    'stop_rfcomm_channel': asyncio.get_running_loop().create_future(),
                    'listener_id': listener_id
                }
                observer = StopRFCOMMSocket(rfcomm_channel_stop)
                name = utils.create_observer_name(observer)
                self.bluetooth.socket_manager.register_callback_observer(name, observer)

                if not self.bluetooth.close(listener_id):
                    raise RuntimeError('Failed to call close.')

                await asyncio.wait_for(rfcomm_channel_stop['stop_rfcomm_channel'], timeout=5)
                del self.server_map[listener_id]
        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return empty_pb2.Empty()

    async def StartServer(self, request: rfcomm_pb2.ServerOptions,
                          context: grpc.ServicerContext) -> rfcomm_pb2.StartServerResponse:

        class StartServerObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe the start server."""

            def __init__(self, task):
                self.task = task

            @utils.glib_callback()
            def on_incoming_socket_ready(self, socket, status):
                if socket and 'id' in socket:
                    socket_id = socket['id']

                if socket_id != self.task['socket_id']:
                    return

                if status is None or floss_enums.BtStatus(status) != floss_enums.BtStatus.SUCCESS:
                    logging.error('Failed to listen RFCOMM channel. Status: %s', status)
                    socket_id = None

                future = self.task['start_rfcomm_server']
                future.get_loop().call_soon_threadsafe(future.set_result, (socket_id, socket))

        try:
            uuid = list(uuid_module.UUID(request.uuid).bytes)
            socket_result = self.bluetooth.listen_using_insecure_rfcomm_with_service_record(request.name, uuid)
            if socket_result is None:
                raise RuntimeError('Failed to call listen_using_insecure_rfcomm_with_service_record.')
            rfcomm_channel_request = {
                'start_rfcomm_server': asyncio.get_running_loop().create_future(),
                'socket_id': socket_result['id']
            }
            observer = StartServerObserver(rfcomm_channel_request)
            name = utils.create_observer_name(observer)
            self.bluetooth.socket_manager.register_callback_observer(name, observer)

            socket_id, socket = await asyncio.wait_for(rfcomm_channel_request['start_rfcomm_server'], timeout=5)
            self.server_map[socket_id] = socket
        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return rfcomm_pb2.StartServerResponse(server=rfcomm_pb2.ServerId(id=socket_id))

    async def AcceptConnection(self, request: rfcomm_pb2.AcceptConnectionRequest,
                               context: grpc.ServicerContext) -> rfcomm_pb2.AcceptConnectionResponse:

        class AcceptConnectionObserver(socket_manager.SocketManagerCallbacks):
            """Observer to observe the accept RFCOMM connection."""

            def __init__(self, client: socket_manager, task):
                self.client = client
                self.task = task

            @utils.glib_callback()
            def on_handle_incoming_connection(self, listener_id, connection, *, dbus_unix_fd_list=None):
                if listener_id != self.task['listener_id']:
                    return
                connections_info = self.client.listening_sockets.get(listener_id, ([], None))[1]
                if connections_info is None:
                    logging.error('Listener id: %s not found in listening sockets: %s', listener_id,
                                  self.client.listening_sockets)
                _, fd = connections_info[0]

                future = self.task['accept_rfcomm_channel']
                future.get_loop().call_soon_threadsafe(future.set_result, fd)

        listener_id = request.server.id
        try:
            if listener_id in self.server_map:
                rfcomm_channel_acceptance = {
                    'accept_rfcomm_channel': asyncio.get_running_loop().create_future(),
                    'listener_id': listener_id
                }

                observer = AcceptConnectionObserver(self.bluetooth.socket_manager, rfcomm_channel_acceptance)
                name = utils.create_observer_name(observer)
                self.bluetooth.socket_manager.register_callback_observer(name, observer)

                accept_socket_status = self.bluetooth.accept(listener_id, 5)
                if accept_socket_status != floss_enums.BtStatus.SUCCESS:
                    raise RuntimeError(f'Failed to accept the RFCOMM socket. Status: {accept_socket_status}.')

                fd = await asyncio.wait_for(rfcomm_channel_acceptance['accept_rfcomm_channel'], timeout=5)

                server_socket_id = self.current_cookie
                self.current_cookie += 1
                server_socket = socket.fromfd(fd, socket.AF_UNIX, socket.SOCK_STREAM)
                self.connection_map[server_socket_id] = server_socket

        except asyncio.TimeoutError as e:
            logging.error('AcceptConnection: asyncio.TimeoutError %s', e)
            return rfcomm_pb2.AcceptConnectionResponse(connection=rfcomm_pb2.RfcommConnection(id=None))
        finally:
            self.bluetooth.socket_manager.unregister_callback_observer(name, observer)

        return rfcomm_pb2.AcceptConnectionResponse(connection=rfcomm_pb2.RfcommConnection(id=server_socket_id))

    async def Send(self, request: rfcomm_pb2.TxRequest, context: grpc.ServicerContext) -> rfcomm_pb2.TxResponse:
        connection_id = request.connection.id
        output_stream = self.connection_map.get(connection_id)
        if output_stream:
            try:
                output_stream.send(request.data)

            except Exception as e:
                logging.error('Exception during writing to output stream %s', e)
        else:
            logging.error('Output stream: %s not found for the connection_id: %s', output_stream, connection_id)

        return empty_pb2.Empty()

    async def Receive(self, request: rfcomm_pb2.RxRequest, context: grpc.ServicerContext) -> rfcomm_pb2.RxResponse:
        connection_id = request.connection.id
        input_stream = self.connection_map.get(connection_id)
        if input_stream:
            try:
                data = input_stream.recv(self.BUFFER_SIZE)

                if data:
                    return rfcomm_pb2.RxResponse(data=bytes(data))
            except Exception as e:
                logging.error('Exception during reading from input stream %s', e)
        else:
            logging.error('Input stream: %s not found for the connection_id: %s', input_stream, connection_id)

        # Return an empty byte array or an error response
        return rfcomm_pb2.RxResponse(data=b"")
